import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuthorizationService } from '../common/authorization/authorization.service';
import { AuditService } from '../audit/audit.service';
import { DataLifecycleService } from '../common/data-lifecycle/data-lifecycle.service';
import { EntityResponseDto } from '../common/dto/entity-response.dto';
import { EventBusService } from '../event-bus/event-bus.service';
import { DOMAIN_EVENT_TYPES } from '../event-bus/event-bus.constants';
import { parsePagination } from '../common/pagination';

@Injectable()
export class ProjectsService {
  constructor(private readonly prisma:PrismaService,private readonly authorization:AuthorizationService,private readonly audit:AuditService,private readonly lifecycle:DataLifecycleService,private readonly eventBus:EventBusService){}
  private async assertProject(userId:string,p:any,permission='project.write'){if(!p||p.deletedAt)throw new NotFoundException('Project not found');if(p.organizationId)await this.authorization.assertPermission(userId,permission,{organizationId:p.organizationId,ownerId:p.ownerId??undefined});else if(p.ownerId!==userId)throw new NotFoundException('Project not found');}
  private normalizeProject(data:any,userId:string){const allowed=['name','description','status','priority','objective','startAt','targetAt','organizationId','ownerId'];const out:any={};for(const k of allowed)if(data[k]!==undefined)out[k]=data[k];out.ownerId??=userId;out.priority??='MEDIUM';if(out.startAt!==undefined)out.startAt=out.startAt?new Date(out.startAt):null;if(out.targetAt!==undefined)out.targetAt=out.targetAt?new Date(out.targetAt):null;return out;}
  async list(userId:string,page?:string,pageSize?:string){const ids=await this.authorization.accessibleOrganizationIds(userId);const p=parsePagination(page,pageSize,{page:1,pageSize:25});const where:Prisma.ProjectWhereInput={deletedAt:null,...(ids?{OR:[{organizationId:{in:ids}},{ownerId:userId}]}:{ownerId:userId})};const [items,total]=await this.prisma.$transaction([this.prisma.project.findMany({where,include:{organization:true,owner:true,requirements:{where:{deletedAt:null}},relationships:{include:{relationship:{include:{sourceOrganization:true,targetOrganization:true}}}},opportunities:true,actions:true,commitments:true,risks:true,milestones:true},orderBy:{updatedAt:'desc'},skip:p.skip,take:p.take}),this.prisma.project.count({where})]);return{items:EntityResponseDto.manyUnknown(items),page:p.page,pageSize:p.pageSize,total,totalPages:Math.ceil(total/p.pageSize)};}
  async get(userId:string,id:string){const p=await this.prisma.project.findUnique({where:{id},include:{organization:true,owner:true,requirements:{where:{deletedAt:null}},relationships:{include:{relationship:{include:{sourceOrganization:true,targetOrganization:true}}}},opportunities:true,actions:true,commitments:true,risks:true,milestones:true}});await this.assertProject(userId,p,'project.read');return EntityResponseDto.from('Project',p as any);}
  async create(userId:string,data:any){if(data.organizationId)await this.authorization.assertPermission(userId,'project.write',{organizationId:data.organizationId});const payload=this.normalizeProject(data,userId);const row=await this.eventBus.transaction(async tx=>{const created=await tx.project.create({data:payload});await this.audit.logMutation({userId,action:'CREATE',entityType:'Project',entityId:created.id,organizationId:created.organizationId??undefined,after:created},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.PROJECT_CREATED,aggregateType:'Project',aggregateId:created.id,organizationId:created.organizationId??undefined,actorId:userId,payload:created as any});return created;});return EntityResponseDto.from('Project',row);}
  async update(userId:string,id:string,data:any){const current=await this.prisma.project.findUnique({where:{id}});await this.assertProject(userId,current);if(data.organizationId)await this.authorization.assertPermission(userId,'project.write',{organizationId:data.organizationId,ownerId:current!.ownerId??undefined});const payload=this.normalizeProject(data,userId);delete payload.ownerId;const updated=await this.eventBus.transaction(async tx=>{const next=await tx.project.update({where:{id},data:payload});await this.audit.logMutation({userId,action:'UPDATE',entityType:'Project',entityId:id,organizationId:next.organizationId??undefined,before:current,after:next},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.PROJECT_UPDATED,aggregateType:'Project',aggregateId:id,organizationId:next.organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.from('Project',updated);}
  async remove(userId:string,id:string){const p=await this.prisma.project.findUnique({where:{id}});await this.assertProject(userId,p);const updated=await this.eventBus.transaction(async tx=>{const next=await this.lifecycle.softDelete(userId,'Project',id,'remove',tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.PROJECT_DELETED,aggregateType:'Project',aggregateId:id,organizationId:(next as any).organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.fromUnknown(updated);}
  async addRequirement(userId:string,data:any){const p=await this.prisma.project.findUnique({where:{id:data.projectId}});await this.assertProject(userId,p);const row=await this.eventBus.transaction(async tx=>{const r=await tx.projectRequirement.create({data:{projectId:data.projectId,title:data.title,description:data.description,category:data.category,status:data.status,priority:data.priority,organizationId:p!.organizationId??data.organizationId}});await this.audit.logMutation({userId,action:'CREATE',entityType:'ProjectRequirement',entityId:r.id,organizationId:p!.organizationId??undefined,after:r},tx);return r;});return EntityResponseDto.fromUnknown(row);}
  async updateRequirement(userId:string,id:string,data:any){const r=await this.prisma.projectRequirement.findUnique({where:{id},include:{project:true}});if(!r||r.deletedAt)throw new NotFoundException('Requirement not found');await this.assertProject(userId,r.project);const allowed=['title','description','category','status','priority'];const update:any={};for(const k of allowed)if(data[k]!==undefined)update[k]=data[k];const updated=await this.eventBus.transaction(async tx=>{const row=await tx.projectRequirement.update({where:{id},data:update});await this.audit.logMutation({userId,action:'UPDATE',entityType:'ProjectRequirement',entityId:id,organizationId:r.project.organizationId??undefined,before:r,after:row},tx);return row;});return EntityResponseDto.fromUnknown(updated);}
  async removeRequirement(userId:string,id:string){const r=await this.prisma.projectRequirement.findUnique({where:{id},include:{project:true}});if(!r||r.deletedAt)throw new NotFoundException('Requirement not found');await this.assertProject(userId,r.project);return EntityResponseDto.fromUnknown(await this.lifecycle.softDelete(userId,'ProjectRequirement',id,'remove'));}
  async linkRelationship(userId:string,id:string,data:any){const p=await this.prisma.project.findUnique({where:{id}});await this.assertProject(userId,p);const r=await this.prisma.relationship.findUnique({where:{id:data.relationshipId},select:{sourceOrganizationId:true,targetOrganizationId:true}});if(!r)throw new NotFoundException('Relationship not found');await this.authorization.assertAnyOrganizationAccess(userId,[r.sourceOrganizationId,r.targetOrganizationId]);const row=await this.eventBus.transaction(async tx=>{const link=await tx.projectRelationship.upsert({where:{projectId_relationshipId:{projectId:id,relationshipId:data.relationshipId}},create:{projectId:id,relationshipId:data.relationshipId,relevance:data.relevance??0,required:data.required??false,status:data.status??'UNENGAGED'},update:{relevance:data.relevance??0,required:data.required??false,status:data.status??'UNENGAGED'}});await this.audit.logMutation({userId,action:'UPDATE',entityType:'ProjectRelationship',entityId:`${id}:${data.relationshipId}`,after:link},tx);return link;});return EntityResponseDto.fromUnknown(row);}
  async unlinkRelationship(userId:string,id:string,relationshipId:string){const p=await this.prisma.project.findUnique({where:{id}});await this.assertProject(userId,p);const row=await this.eventBus.transaction(async tx=>{const link=await tx.projectRelationship.delete({where:{projectId_relationshipId:{projectId:id,relationshipId}}});await this.audit.logMutation({userId,action:'DELETE',entityType:'ProjectRelationship',entityId:`${id}:${relationshipId}`,before:link},tx);return link;});return EntityResponseDto.fromUnknown(row);}
  async addRisk(userId:string,projectId:string,data:any){const p=await this.prisma.project.findUnique({where:{id:projectId}});await this.assertProject(userId,p);const row=await this.prisma.projectRisk.create({data:{projectId,organizationId:p!.organizationId??undefined,ownerId:data.ownerId,title:data.title,description:data.description,probability:data.probability??0,impact:data.impact??0,score:data.score??((data.probability??0)*(data.impact??0)),mitigation:data.mitigation,status:data.status??'OPEN'}});await this.audit.logMutation({userId,action:'CREATE',entityType:'ProjectRisk',entityId:row.id,organizationId:p!.organizationId??undefined,after:row});return EntityResponseDto.fromUnknown(row);}
  async updateRisk(userId:string,id:string,data:any){const r=await this.prisma.projectRisk.findUnique({where:{id},include:{project:true}});if(!r)throw new NotFoundException('Risk not found');await this.assertProject(userId,r.project);const update:any={};for(const k of ['ownerId','title','description','probability','impact','mitigation','status'])if(data[k]!==undefined)update[k]=data[k];if(data.probability!==undefined||data.impact!==undefined)update.score=(data.probability??r.probability)*(data.impact??r.impact);const row=await this.prisma.projectRisk.update({where:{id},data:update});await this.audit.logMutation({userId,action:'UPDATE',entityType:'ProjectRisk',entityId:id,organizationId:r.project.organizationId??undefined,before:r,after:row});return EntityResponseDto.fromUnknown(row);}
  async removeRisk(userId:string,id:string){const r=await this.prisma.projectRisk.findUnique({where:{id},include:{project:true}});if(!r)throw new NotFoundException('Risk not found');await this.assertProject(userId,r.project);const row=await this.prisma.projectRisk.delete({where:{id}});await this.audit.logMutation({userId,action:'DELETE',entityType:'ProjectRisk',entityId:id,before:r});return EntityResponseDto.fromUnknown(row);}
  async addMilestone(userId:string,projectId:string,data:any){const p=await this.prisma.project.findUnique({where:{id:projectId}});await this.assertProject(userId,p);const row=await this.prisma.projectMilestone.create({data:{projectId,ownerId:data.ownerId??p!.ownerId??userId,title:data.title,description:data.description,status:data.status,dueAt:data.dueAt?new Date(data.dueAt):undefined,completedAt:data.completedAt?new Date(data.completedAt):undefined}});await this.audit.logMutation({userId,action:'CREATE',entityType:'ProjectMilestone',entityId:row.id,organizationId:p!.organizationId??undefined,after:row});return EntityResponseDto.fromUnknown(row);}
  async updateMilestone(userId:string,id:string,data:any){const m=await this.prisma.projectMilestone.findUnique({where:{id},include:{project:true}});if(!m)throw new NotFoundException('Milestone not found');await this.assertProject(userId,m.project);const update:any={};for(const k of ['ownerId','title','description','status'])if(data[k]!==undefined)update[k]=data[k];if(data.dueAt!==undefined)update.dueAt=data.dueAt?new Date(data.dueAt):null;if(data.completedAt!==undefined)update.completedAt=data.completedAt?new Date(data.completedAt):null;const row=await this.prisma.projectMilestone.update({where:{id},data:update});await this.audit.logMutation({userId,action:'UPDATE',entityType:'ProjectMilestone',entityId:id,organizationId:m.project.organizationId??undefined,before:m,after:row});return EntityResponseDto.fromUnknown(row);}
  async removeMilestone(userId:string,id:string){const m=await this.prisma.projectMilestone.findUnique({where:{id},include:{project:true}});if(!m)throw new NotFoundException('Milestone not found');await this.assertProject(userId,m.project);const row=await this.prisma.projectMilestone.delete({where:{id}});await this.audit.logMutation({userId,action:'DELETE',entityType:'ProjectMilestone',entityId:id,before:m});return EntityResponseDto.fromUnknown(row);}
}
