'use client';
import {useEffect,useState,useCallback} from 'react';
import {api,unwrapList} from '../_lib/api';
import {Badge,DataTable,Empty,ErrorCard,Loading,PageHeader} from '../_components/page-ui';
const PREF_FIELDS=['inAppEnabled','emailEnabled','pushEnabled','digestEnabled','criticalOnly','dailyDigest','weeklyDigest'] as const;
const PRIORITY_TONE:Record<string,'danger'|'warning'|'info'|'neutral'>={critical:'danger',important:'warning',recommendation:'info',reminder:'info',information:'neutral'};
export default function Notifications(){
 const [items,setItems]=useState<any[]>([]),[unread,setUnread]=useState(0),[prefs,setPrefs]=useState<Record<string,boolean>>({}),[log,setLog]=useState<any[]>([]);
 const [error,setError]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [n,u,pref,l]=await Promise.all([api('/notifications').then(unwrapList),api('/notifications/unread-count'),api<any>('/notifications/preferences'),api('/notifications/delivery-log').then(unwrapList)]);setItems(n);setUnread(typeof u==='number'?u:typeof (u as any)?.count==='number'?(u as any).count:0);setPrefs(pref&&typeof pref==='object'?pref:{});setLog(l);}catch(x){setError((x as Error).message)}finally{setLoading(false)}},[setItems,setUnread,setPrefs,setLog,setLoading,setError]);
 useEffect(()=>{load()},[load]);
 async function read(id:string){setBusy('read'+id);try{await api('/notifications/'+id+'/read',{method:'PATCH'});await load()}catch(x){setError((x as Error).message)}finally{setBusy('')}}
 async function readAll(){setBusy('readall');try{await api('/notifications/read-all',{method:'PATCH'});await load()}catch(x){setError((x as Error).message)}finally{setBusy('')}}
 async function savePrefs(){setBusy('prefs');setError('');setStatus('');try{await api('/notifications/preferences',{method:'PATCH',body:JSON.stringify(prefs)});setStatus('تنظیمات اعلان ذخیره شد.');await load()}catch(x){setError((x as Error).message)}finally{setBusy('')}}
 async function digest(cadence:string){setBusy(cadence);setError('');setStatus('');try{const r:any=await api(`/notifications/digest/${cadence}`,{method:'POST',body:JSON.stringify({})});setStatus(r?.sent?`Digest ${cadence} ارسال شد (${r?.count??0} مورد).`:r?.reason==='digest-disabled'?`Digest ${cadence} غیرفعال است یا ایمیل خاموش است.`:r?.reason==='empty'?'اعلانی برای Digest نبود.':r?.reason==='no-email'?'حساب شما ایمیل ندارد.':'Digest ارسال نشد.');}catch(x){setError((x as Error).message)}finally{setBusy('')}}
 const toggle=(k:string)=>setPrefs(p=>({...p,[k]:!p[k]}));
 return <main className="feature-page"><PageHeader eyebrow="NOTIFICATIONS" title="مرکز اعلان" description="اعلان‌ها در کانال‌های InApp/Email/Push، ترجیحات، Digest و Delivery Log با واقعیت Backend." actions={<div className="toolbar"><button className="secondary-action" onClick={readAll} disabled={!!busy}>{busy==='readall'?'در حال…':'علامت‌گذاری همه به‌عنوان خوانده‌شده'}</button><button className="secondary-action" onClick={load} disabled={!!busy}>بازخوانی</button></div>}/>
 <ErrorCard message={error}/>{status&&<div className="notice" role="status">{status}</div>}
 {loading?<Loading/>:<>
 <section className="stat-row"><div className="stat-box"><span>خوانده‌نشده</span><strong>{unread}</strong></div><div className="stat-box"><span>کل اعلان‌ها</span><strong>{items.length}</strong></div><div className="stat-box"><span>کانال‌ها</span><strong>{new Set(items.map(n=>n.channel).filter(Boolean)).size}</strong></div><div className="stat-box"><span>تحویل‌های ثبت‌شده</span><strong>{log.length}</strong></div></section>
 <section className="panel"><div className="panel-title"><div><h2>اعلان‌ها</h2><p>{unread} خوانده‌نشده</p></div></div>{items.length===0?<Empty>اعلانی وجود ندارد.</Empty>:<div className="list">{items.map(n=><article className="listRow" key={n.id}><div><strong>{n.title}</strong><small>{n.body} · {n.channel} · {new Date(n.createdAt).toLocaleString()}</small></div><span><Badge tone={PRIORITY_TONE[String(n.priority).toLowerCase()]??'neutral'}>{n.priority}</Badge>{!n.readAt&&<button className="secondary-action" onClick={()=>read(n.id)} disabled={!!busy}>خواندن</button>}</span></article>)}</div>}</section>
 <section className="split-panels">
  <article className="panel"><div className="panel-title"><div><h2>ترجیحات اعلان</h2></div></div><div className="entity-form">{PREF_FIELDS.map(k=>{const label=k==='dailyDigest'?'Digest روزانه (DAILY)':k==='weeklyDigest'?'Digest هفتگی (WEEKLY)':k==='inAppEnabled'?'اعلان درون‌برنامه (InApp)':k==='emailEnabled'?'ایمیل':k==='pushEnabled'?'Push':k==='criticalOnly'?'فقط بحرانی (Critical)':'Digest فعال';return <label key={k}><input type="checkbox" checked={!!prefs[k]} onChange={()=>toggle(k)}/><span> {label}</span></label>})}</div><div className="toolbar"><button className="primary-action" onClick={savePrefs} disabled={!!busy}>{busy==='prefs'?'در حال ذخیره…':'ذخیره ترجیحات'}</button><button className="secondary-action" onClick={()=>digest('DAILY')} disabled={!!busy}>ارسال Digest روزانه</button><button className="secondary-action" onClick={()=>digest('WEEKLY')} disabled={!!busy}>ارسال Digest هفتگی</button></div></article>
  <article className="panel"><div className="panel-title"><div><h2>Delivery Log</h2></div></div>{log.length===0?<Empty>لاگ تحویلی ثبت نشده است.</Empty>:<DataTable columns={['channel','provider','accepted','title','createdAt'].map(k=>({key:k,label:k}))} rows={log.map(l=>({...l,accepted:<Badge tone={l.accepted?'success':'danger'}>{l.accepted?'پذیرفته':'خطا'}</Badge>,createdAt:new Date(l.createdAt).toLocaleString()}))}/>}</article>
 </section>
 </>}
 </main>}