'use client';
import {useEffect,useState} from 'react';
import {api} from '../_lib/api';
export default function MFA(){
 const [required,setRequired]=useState<boolean|null>(null),[code,setCode]=useState(''),[label,setLabel]=useState('SRIP Web'),[deviceId,setDeviceId]=useState(''),[secret,setSecret]=useState<{secret:string;otpauthUrl:string}|null>(null),[recoveryCodes,setRecoveryCodes]=useState<string[]>([]),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[copied,setCopied]=useState('');
 useEffect(()=>{api<any>('/auth/mfa/required').then(x=>setRequired(!!x.required)).catch(x=>setError(x.message))},[]);
 async function enroll(){if(!label.trim()){setError('نام دستگاه را وارد کنید.');return}setBusy('enroll');setError('');setMsg('');try{const x=await api<any>('/auth/mfa/enroll',{method:'POST',body:JSON.stringify({label:label.trim()})});if(!x?.deviceId||!x?.secret||!x?.otpauthUrl)throw new Error('پاسخ Enrollment ناقص است.');setSecret({secret:x.secret,otpauthUrl:x.otpauthUrl});setDeviceId(x.deviceId);setMsg('دستگاه ایجاد شد. Secret را در برنامه Authenticator وارد یا URI را با یک QR سازگار تبدیل کنید، سپس کد شش‌رقمی را وارد کنید.')}catch(x){setError((x as Error).message)}finally{setBusy('')}}
 async function copyValue(value:string,label:string){try{await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(''),1600)}catch{setError('کپی خودکار انجام نشد؛ مقدار را به‌صورت دستی کپی کنید.')}}
 async function verifyEnrollment(){if(!deviceId||code.length!==6){setError('پس از Enrollment، کد شش‌رقمی Authenticator را وارد کنید.');return}setBusy('verify-enrollment');setError('');setMsg('');try{const x:any=await api('/auth/mfa/verify-enrollment',{method:'POST',body:JSON.stringify({deviceId,code})});setRecoveryCodes(Array.isArray(x.recoveryCodes)?x.recoveryCodes:[]);setRequired(true);setMsg('فعال‌سازی MFA با موفقیت تأیید شد. کدهای بازیابی را در محل امن ذخیره کنید.')}catch(x){setError((x as Error).message)}finally{setBusy('')}}
 async function verify(){if(code.length!==6){setError('کد باید شش رقم باشد.');return}setBusy('verify');setError('');setMsg('');try{await api('/auth/mfa/verify',{method:'POST',body:JSON.stringify({code})});setMsg('کد MFA معتبر است.')}catch(x){setError((x as Error).message)}finally{setBusy('')}}
 return <main className="auth-page"><section className="auth-card"><p className="eyebrow">SECURITY</p><h1>MFA</h1><p>احراز هویت چندمرحله‌ای با سرویس واقعی Backend.</p><p>الزام فعلی: <strong>{required===null?'—':required?'فعال':'غیرفعال'}</strong></p>{error&&<div className="error-card" role="alert">{error}</div>}{msg&&<div className="status-message" role="status">{msg}</div>}<label>نام دستگاه<input value={label} onChange={e=>setLabel(e.target.value)} disabled={!!busy}/></label><button className="primary-action" onClick={enroll} disabled={!!busy}>{busy==='enroll'?'در حال ایجاد…':'شروع Enrollment'}</button>{secret&&<section className="panel compact"><h2>اتصال Authenticator</h2><p className="muted">Secret زیر را فقط در برنامه Authenticator وارد کنید. آن را با دیگران به اشتراک نگذارید.</p><code className="secret-code">{secret.secret}</code><button type="button" className="secondary-action" onClick={()=>void copyValue(secret.secret,'secret')} disabled={!!busy}>{copied==='secret'?'کپی شد':'کپی Secret'}</button><details><summary>نمایش URI راه‌اندازی</summary><code className="secret-code">{secret.otpauthUrl}</code><button type="button" className="secondary-action" onClick={()=>void copyValue(secret.otpauthUrl,'uri')} disabled={!!busy}>{copied==='uri'?'کپی شد':'کپی URI'}</button></details></section>}<label>کد شش‌رقمی<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} disabled={!!busy}/></label><div className="toolbar"><button onClick={verifyEnrollment} disabled={!deviceId||code.length!==6||!!busy}>{busy==='verify-enrollment'?'در حال تأیید…':'تأیید Enrollment'}</button><button onClick={verify} disabled={code.length!==6||!!busy}>{busy==='verify'?'در حال بررسی…':'تأیید کد'}</button></div>{recoveryCodes.length>0&&<section className="panel compact"><h2>کدهای بازیابی</h2><p className="muted">هر کد فقط یک‌بار قابل استفاده است. این فهرست پس از خروج از صفحه دوباره نمایش داده نمی‌شود.</p><div className="recovery-codes">{recoveryCodes.map(value=><code key={value}>{value}</code>)}</div></section>}</section></main>
}
