'use client';
import { useEffect, useMemo, useState } from 'react';
import { apiGet } from '../_lib/api';

type Node={id:string;label:string;type:string}; type Edge={id:string;source:string;target:string;kind:string;weight:number;risk:number;strategicImportance:number;label?:string}; type Graph={nodes:Node[];edges:Edge[];meta:any};
export default function Page(){
 const [connectors,setConnectors]=useState<any[]>([]); const [graph,setGraph]=useState<Graph|null>(null); const [q,setQ]=useState(''); const [type,setType]=useState('all'); const [status,setStatus]=useState(''); const [focus,setFocus]=useState(''); const [mode,setMode]=useState<'shortest'|'best'>('shortest'); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [path,setPath]=useState<any>(null); const [analysis,setAnalysis]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const params=new URLSearchParams();if(q)params.set('q',q);if(type!=='all')params.set('type',type);if(status)params.set('status',status);if(focus)params.set('focus',focus);setGraph(await apiGet(`/network/graph?${params.toString()}`));}catch(e:any){setError(e?.message||'Unable to load network');}finally{setLoading(false)}};
 const runPath=async()=>{if(!from||!to)return;try{setPath(await apiGet(`/network/path?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&mode=${mode}`));}catch(e:any){setError(e?.message||'Unable to calculate path')}};
 const loadConnectors=async()=>{try{setConnectors(await apiGet('/network/connectors'))}catch(e:any){setError(e?.message||'Unable to load connectors')}};
 const runAnalysis=async(endpoint:string)=>{try{setAnalysis(await apiGet(`/network/${endpoint}`));}catch(e:any){setError(e?.message||'Unable to load analysis')}};
 useEffect(()=>{load()},[]);
 const positions=useMemo(()=>{if(!graph)return new Map<string,{x:number;y:number}>();const m=new Map<string,{x:number;y:number}>();graph.nodes.forEach((n,i)=>{const a=(i/Math.max(1,graph.nodes.length))*Math.PI*2;m.set(n.id,{x:300+220*Math.cos(a),y:220+160*Math.sin(a)})});return m},[graph]);
 return <main className="shell"><header className="topbar"><strong>SRIP</strong><a href="/">Dashboard</a></header><section className="hero"><p className="eyebrow">SRIP Workspace</p><h1>Network Intelligence</h1><p>Authorization-aware graph, filters, paths and network-risk analysis.</p></section><section className="card"><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input aria-label="Search network" placeholder="Search organizations, people, projects" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Node type" value={type} onChange={e=>setType(e.target.value)}><option value="all">All</option><option value="organization">Organizations</option><option value="person">People</option><option value="project">Projects</option></select><input aria-label="Relationship status" placeholder="Status" value={status} onChange={e=>setStatus(e.target.value)}/><select aria-label="Focus node" value={focus} onChange={e=>setFocus(e.target.value)}><option value="">No focus</option>{graph?.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select><button onClick={load}>Apply</button></div>{loading&&<p>Loading…</p>}{error&&<p role="alert">{error}</p>}{graph&&<>
 <p><strong>{graph.meta.organizationCount}</strong> organizations · <strong>{graph.meta.peopleCount}</strong> people · <strong>{graph.meta.projectCount}</strong> projects · <strong>{graph.meta.relationshipCount}</strong> relationships</p>
 <div className="card"><h2>Graph</h2><svg viewBox="0 0 600 440" width="100%" role="img" aria-label="Network graph" style={{minHeight:320}}>{graph.edges.slice(0,120).map((e,i)=>{const a=positions.get(e.source),b=positions.get(e.target);return a&&b?<line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} strokeWidth={Math.max(1,Math.min(6,e.weight/20))}/>:null})}{graph.nodes.slice(0,120).map(n=>{const p=positions.get(n.id)!;return <g key={n.id}><circle cx={p.x} cy={p.y} r="18"/><text x={p.x} y={p.y+32} textAnchor="middle" fontSize="9">{n.label.slice(0,22)}</text></g>})}</svg></div>
 <div className="card"><h2>Connection path</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={from} onChange={e=>setFrom(e.target.value)}><option value="">From</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)}><option value="">To</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select><select value={mode} onChange={e=>setMode(e.target.value as any)}><option value="shortest">Shortest</option><option value="best">Best</option></select><button onClick={runPath}>Find path</button></div>{path&&<p>{path.found?`${path.hops} hops · cost ${path.totalCost}`:'No visible path found'}</p>}</div>
 <div className="card"><h2>Network analysis</h2><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>runAnalysis('centrality')}>Centrality</button><button onClick={loadConnectors}>Connectors</button><button onClick={()=>runAnalysis('bridges')}>Bridge people</button><button onClick={()=>runAnalysis('bottlenecks')}>Bottlenecks</button><button onClick={()=>runAnalysis('single-points-of-failure')}>Single points of failure</button></div>{connectors.length>0&&<div><h3>Top connectors</h3><pre>{JSON.stringify(connectors,null,2)}</pre></div>}{analysis&&<pre style={{whiteSpace:'pre-wrap',overflow:'auto'}}>{JSON.stringify(analysis,null,2)}</pre>}</div>
 <div className="card"><h2>Visible nodes</h2>{graph.nodes.slice(0,120).map(n=><button key={n.id} onClick={()=>setFocus(n.id)} style={{display:'flex',width:'100%',justifyContent:'space-between',padding:6,background:'none',border:0}}><span>{n.label}</span><small>{n.type}</small></button>)}</div></>}</section></main>
}
