'use client';
import {use,useCallback,useEffect,useState} from 'react';
import {api} from '../../_lib/api';
import {Badge,ErrorCard,Loading,PageHeader} from '../../_components/page-ui';
import {RelatedNotes} from '../../_components/related-notes';
import {EntityPicker} from '../../_components/entity-picker';
import {useWorkspace} from '../../_components/workspace';
import {QuickCreate} from '../../_components/quick-create';
type Panel='org'|'contact';
export default function Page({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);
 const {scopeId}=useWorkspace();
 const [p,setP]=useState<any>(null),[orgs,setOrgs]=useState<any[]>([]),[contacts,setContacts]=useState<any[]>([]),[timeline,setTimeline]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[panel,setPanel]=useState<Panel|null>(null),[quickOpen,setQuickOpen]=useState(false);
 const [orgForm,setOrgForm]=useState({organizationId:'',roleTitle:'',department:'',isPrimary:false});
 const [ctForm,setCtForm]=useState({kind:'EMAIL',value:'',label:'',isPrimary:false});
 const arr=(x:any)=>Array.isArray(x)?x:Array.isArray(x?.items)?x.items:Array.isArray(x?.data)?x.data:Array.isArray(x?.rows)?x.rows:[];
 const load=useCallback(async()=>{setError('');try{const [person,orgRows,tl]=await Promise.all([api(`/people/${id}`),api(`/people/${id}/organizations`),api(`/people/${id}/timeline`)]);setP(person);setOrgs(arr(orgRows));setTimeline(arr(tl))}catch(e){setError((e as Error).message)}},[id]);
 const loadContacts=useCallback(async()=>{setError('');try{setContacts(arr(await api(`/core-domain/people/${id}/contacts`)))}catch(e){setError((e as Error).message)}},[id]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{loadContacts()},[loadContacts]);
 async function doIt(label:string,fn:()=>Promise<any>){setBusy(label);setError('');try{await fn();await load()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function addOrg(e:React.FormEvent){e.preventDefault();await doIt('org',()=>api(`/people/${id}/organizations`,{method:'POST',body:JSON.stringify({...orgForm,organizationId:orgForm.organizationId,isPrimary:orgForm.isPrimary})}));setOrgForm({organizationId:'',roleTitle:'',department:'',isPrimary:false});setPanel(null)}
 async function removeOrg(organizationId:string){if(!confirm('این انتساب سازمانی حذف شود؟'))return;await doIt('unorg',()=>api(`/people/${id}/organizations/${organizationId}`,{method:'DELETE'}))}
 async function addContact(e:React.FormEvent){e.preventDefault();await doIt('ct',()=>api(`/core-domain/people/${id}/contacts`,{method:'POST',body:JSON.stringify(ctForm)}));setCtForm({kind:'EMAIL',value:'',label:'',isPrimary:false});setPanel(null);await loadContacts()}
 const info=p?Object.entries(p).filter(([k])=>!['organizations'].includes(k)&&typeof p[k]!=='function'&&k!=='timeline').slice(0,24):[];
 return <main className="feature-page">
  <PageHeader eyebrow="PEOPLE" title={p?.displayName??p?.firstName?`${p.firstName} ${p.lastName??''}`:'Person'} description="جزئیات شخص، انتساب‌های سازمانی، تماس‌ها، یادداشت‌ها و Timeline عملیاتی." actions={<div className="toolbar"><button className="secondary-action" onClick={load} disabled={!!busy}>بازخوانی</button><button className="primary-action" onClick={()=>setQuickOpen(true)} disabled={!!busy}>+ ثبت سریع</button><button className="primary-action" onClick={()=>setPanel('org')} disabled={!!busy}>+ سازمان</button><button className="primary-action" onClick={()=>setPanel('contact')} disabled={!!busy}>+ تماس</button>{p?.deletedAt?<button className="primary-action" disabled={!!busy} onClick={()=>doIt('restore',()=>api(`/people/${id}/restore`,{method:'POST'}))}>بازیابی</button>:<button className="danger-action" disabled={!!busy} onClick={()=>{if(confirm('این شخص بایگانی شود؟'))doIt('archive',()=>api(`/people/${id}/archive`,{method:'PATCH'}))}}>بایگانی</button>}</div>}/>
  <ErrorCard message={error}/>
  {!p&&!error?<Loading/>:p&&<>
   <section className="panel"><div className="panel-title"><div><h2>اطلاعات شخص</h2><p>{info.find(([k])=>k==='title')?.[1]?String(info.find(([k])=>k==='title')![1]):''}</p></div></div><div className="detail-grid">{info.map(([k,v])=>{if(v==null||v==='')return null;return <div className="detail-item" key={k}><small>{k}</small><strong>{typeof v==='object'?JSON.stringify(v):String(v)}</strong></div>})}</div></section>
   <div className="split-panels">
    <section className="panel"><div className="panel-title"><div><h2>سازمان‌ها و نقش‌ها</h2><Badge>{orgs.length}</Badge></div></div>{orgs.length?<div className="list">{orgs.map((o:any)=><div className="listRow" key={o.organizationId}><Badge tone={o.isPrimary?'success':'neutral'}>{o.isPrimary?'Primary':o.status}</Badge><span><strong>{o.organization?.name??o.organizationId}</strong><small>{[o.roleTitle,o.department].filter(Boolean).join(' · ')||'بدون نقش'}</small></span><span className="resource-row-actions"><button onClick={()=>removeOrg(o.organizationId)}>حذف</button></span></div>)}</div>:<p className="empty-state">انتساب سازمانی ثبت نشده است.</p>}</section>
    <section className="panel"><div className="panel-title"><div><h2>اطلاعات تماس</h2><Badge>{contacts.length}</Badge></div></div>{contacts.length?<div className="list">{contacts.map((c:any)=><div className="listRow" key={c.id}><Badge tone={c.isPrimary?'success':'neutral'}>{c.kind}</Badge><span><strong>{c.value}</strong><small>{c.label||''}{c.isPrimary?' · تماس اصلی':''}</small></span></div>)}</div>:<p className="empty-state">تماسی ثبت نشده است.</p>}</section>
   </div>
   <section className="panel"><div className="panel-title"><div><h2>Timeline</h2><Badge>{timeline.length}</Badge></div></div>{timeline.length?<div className="list">{timeline.slice(0,50).map((x:any,i:number)=><div className="listRow" key={x.id??i}><Badge tone="neutral">{(x as any).kind??'EVENT'}</Badge><span><strong>{x.title||x.subject||x.description||x.name||x.eventType||'—'}</strong>{(x.date||x.createdAt)?<small>{new Date(x.date??x.createdAt).toLocaleString()}</small>:null}</span></div>)}</div>:<p className="empty-state">رویدادی ثبت نشده است.</p>}</section>
   <RelatedNotes notes={p.notes} title="یادداشت‌های شخص" />
   {panel==='org'&&<section className="panel"><div className="panel-title"><h2>انتساب سازمانی جدید</h2><button onClick={()=>setPanel(null)}>انصراف</button></div><form className="entity-form" onSubmit={addOrg}><EntityPicker label="سازمان" endpoint="/organizations" value={orgForm.organizationId} onChange={organizationId=>setOrgForm({...orgForm,organizationId})} scopeId={scopeId} required/><label>عنوان نقش<input value={orgForm.roleTitle} onChange={e=>setOrgForm({...orgForm,roleTitle:e.target.value})}/></label><label>دپارتمان<input value={orgForm.department} onChange={e=>setOrgForm({...orgForm,department:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={orgForm.isPrimary} onChange={e=>setOrgForm({...orgForm,isPrimary:e.target.checked})}/>سازمان اصلی</label><button className="primary-action" disabled={!!busy}>{busy==='org'?'در حال ذخیره…':'ثبت انتساب'}</button></form></section>}
   {panel==='contact'&&<section className="panel"><div className="panel-title"><h2>اطلاعات تماس جدید</h2><button onClick={()=>setPanel(null)}>انصراف</button></div><form className="entity-form" onSubmit={addContact}><label>نوع<select value={ctForm.kind} onChange={e=>setCtForm({...ctForm,kind:e.target.value})}>{['EMAIL','PHONE','MOBILE','ADDRESS','LINKEDIN','TELEGRAM','WHATSAPP','WEBSITE','OTHER'].map(k=><option key={k} value={k}>{k}</option>)}</select></label><label>مقدار<input required value={ctForm.value} onChange={e=>setCtForm({...ctForm,value:e.target.value})}/></label><label>برچسب<input value={ctForm.label} onChange={e=>setCtForm({...ctForm,label:e.target.value})} placeholder="مثلاً شخصی / کاری"/></label><label className="checkbox-label"><input type="checkbox" checked={ctForm.isPrimary} onChange={e=>setCtForm({...ctForm,isPrimary:e.target.checked})}/>تماس اصلی</label><button className="primary-action" disabled={!!busy}>{busy==='ct'?'در حال ذخیره…':'ثبت تماس'}</button></form></section>}
   <QuickCreate open={quickOpen} onClose={()=>setQuickOpen(false)} onCreated={load} context={{personId:id, organizationId:orgs.find(o=>o.isPrimary)?.organizationId ?? orgs[0]?.organizationId}} />
  </>}
 </main>;
}