'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { api,unwrapList } from '../_lib/api';

type Interaction={id:string;type:string;subject:string;summary?:string;outcome?:string;occurredAt:string;followUpRequired:boolean;followUpAt?:string;organization?:{name:string};person?:{firstName:string;lastName:string}};
const types=['CALL','EMAIL','MEETING','NOTE','MESSAGE','OTHER'];
export default function InteractionsPage(){
 const [items,setItems]=useState<Interaction[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [followUps,setFollowUps]=useState(false);
 const [form,setForm]=useState({type:'NOTE',subject:'',summary:'',occurredAt:new Date().toISOString().slice(0,16),followUpRequired:false,followUpAt:'',organizationId:'',personId:'',relationshipId:''});
 const load=()=>{setLoading(true);return api<Interaction[]>(`/interactions?followUpOnly=${followUps}`).then(x=>setItems(unwrapList<Interaction>(x))).catch(e=>setError(e.message)).finally(()=>setLoading(false))}; useEffect(()=>{load()},[followUps]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/interactions',{method:'POST',body:JSON.stringify({...form,occurredAt:new Date(form.occurredAt).toISOString(),followUpAt:form.followUpRequired&&form.followUpAt?new Date(form.followUpAt).toISOString():undefined,organizationId:form.organizationId||undefined,personId:form.personId||undefined,relationshipId:form.relationshipId||undefined})});setForm({...form,subject:'',summary:'',followUpAt:''});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="shell"><header className="topbar"><strong>SRIP</strong><nav><a href="/">Dashboard</a><a href="/meetings">Meetings</a><a href="/relationships">Relationships</a></nav></header><section className="hero"><p className="eyebrow">Interaction Timeline</p><h1>Interactions</h1><p>Record calls, emails, meetings, notes and follow-up commitments without leaving relationship context.</p></section>
 {error&&<section className="card"><strong>Unable to complete request</strong><p>{error}</p></section>}
 <section className="card"><h2>Log interaction</h2><form onSubmit={submit} className="form-grid"><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Occurred at<input type="datetime-local" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/></label><label>Organization ID<input value={form.organizationId} onChange={e=>setForm({...form,organizationId:e.target.value})}/></label><label>Person ID<input value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}/></label><label>Relationship ID<input value={form.relationshipId} onChange={e=>setForm({...form,relationshipId:e.target.value})}/></label><label className="full">Summary<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label><input type="checkbox" checked={form.followUpRequired} onChange={e=>setForm({...form,followUpRequired:e.target.checked})}/> Follow-up required</label>{form.followUpRequired&&<label>Follow-up at<input type="datetime-local" value={form.followUpAt} onChange={e=>setForm({...form,followUpAt:e.target.value})}/></label>}<button disabled={busy}>{busy?'Saving…':'Save interaction'}</button></form></section>
 <section className="toolbar"><button onClick={()=>setFollowUps(false)} aria-pressed={!followUps}>All</button><button onClick={()=>setFollowUps(true)} aria-pressed={followUps}>Follow-ups</button></section>
 {loading?<p>در حال بارگذاری…</p>:items.length===0?<p className="empty-state">تعاملی ثبت نشده است.</p>:<section className="grid">{items.map(x=><article className="card" key={x.id}><span className="badge">{x.type}</span><h2><Link href={`/interactions/${x.id}`}>{x.subject}</Link></h2><p>{x.summary||'No summary recorded.'}</p><small>{new Date(x.occurredAt).toLocaleString()} · {x.organization?.name||[x.person?.firstName,x.person?.lastName].filter(Boolean).join(' ')||'Unlinked'}</small>{x.followUpRequired&&<p><strong>Follow-up: {x.followUpAt?new Date(x.followUpAt).toLocaleString():'required'}</strong></p>}</article>)}</section>}</main>
}
