import { Injectable, ServiceUnavailableException } from '@nestjs/common';
import { IntegrationProviderPort, IntegrationKind, TokenSet, ExternalEvent } from './integration-provider.port';
@Injectable()
export class GoogleIntegrationProvider implements IntegrationProviderPort {
  readonly provider='GOOGLE' as const;
  private config(){const id=process.env.GOOGLE_CLIENT_ID,secret=process.env.GOOGLE_CLIENT_SECRET;if(!id||!secret)throw new ServiceUnavailableException('Google integration is not configured');return {id,secret};}
  buildAuthorizeUrl(kind:IntegrationKind,state:string,redirectUri:string){const {id}=this.config();const scopes:Record<IntegrationKind,string[]>={CALENDAR:['https://www.googleapis.com/auth/calendar.readonly'],EMAIL:['https://www.googleapis.com/auth/gmail.readonly'],DRIVE:['https://www.googleapis.com/auth/drive.readonly'],TEAMS:[],SHAREPOINT:[]}; if(!scopes[kind].length)throw new ServiceUnavailableException(`Google does not support ${kind}`);return `https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(id)}&redirect_uri=${encodeURIComponent(redirectUri)}&response_type=code&access_type=offline&prompt=consent&scope=${encodeURIComponent(scopes[kind].join(' '))}&state=${encodeURIComponent(state)}`;}
  async exchangeCode(_kind:IntegrationKind,code:string,redirectUri:string):Promise<TokenSet>{const {id,secret}=this.config();const body=new URLSearchParams({code,client_id:id,client_secret:secret,redirect_uri:redirectUri,grant_type:'authorization_code'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const data:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Google token exchange failed: ${data.error_description||data.error||r.status}`);return {accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:data.expires_in?new Date(Date.now()+data.expires_in*1000):undefined,scope:data.scope};}
  async refresh(refreshToken:string):Promise<TokenSet>{const {id,secret}=this.config();const body=new URLSearchParams({client_id:id,client_secret:secret,refresh_token:refreshToken,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const d:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Google token refresh failed: ${d.error_description||d.error||r.status}`);return {accessToken:d.access_token,expiresAt:d.expires_in?new Date(Date.now()+d.expires_in*1000):undefined,scope:d.scope};}
  async pull(kind:IntegrationKind,token:string,cursor?:string){const h={Authorization:`Bearer ${token}`}; if(kind==='CALENDAR'){const u=new URL('https://www.googleapis.com/calendar/v3/calendars/primary/events');u.searchParams.set('singleEvents','true');u.searchParams.set('showDeleted','true');u.searchParams.set('maxResults','250');if(cursor)u.searchParams.set('pageToken',cursor);const r=await fetch(u,{headers:h});const d:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Google Calendar sync failed: ${d.error?.message||r.status}`);return {events:(d.items||[]).map((e:any)=>({externalId:e.id,kind,title:e.summary,startsAt:e.start?.dateTime||e.start?.date,endsAt:e.end?.dateTime||e.end?.date,attendees:(e.attendees||[]).map((a:any)=>a.email).filter(Boolean),updatedAt:e.updated,etag:e.etag,cancelled:e.status==='cancelled',meetingUrl:e.hangoutLink||e.conferenceData?.entryPoints?.[0]?.uri,location:e.location,raw:e})),nextCursor:d.nextPageToken};}
    if(kind==='EMAIL'){const u=new URL('https://gmail.googleapis.com/gmail/v1/users/me/messages');u.searchParams.set('maxResults','100');u.searchParams.set('includeSpamTrash','false');if(cursor)u.searchParams.set('pageToken',cursor);const r=await fetch(u,{headers:h});const d:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Gmail sync failed: ${d.error?.message||r.status}`);const events:ExternalEvent[]=[];for(const m of d.messages||[]){const mr=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(m.id)}?format=metadata&metadataHeaders=Subject&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Date`,{headers:h});const md:any=await mr.json();const headers=(md.payload?.headers||[]).reduce((a:any,x:any)=>(a[x.name.toLowerCase()]=x.value,a),{});events.push({externalId:m.id,kind,title:headers.subject,subject:headers.subject,sender:headers.from,recipients:headers.to?[headers.to]:[],threadId:m.threadId,updatedAt:md.internalDate?new Date(Number(md.internalDate)).toISOString():undefined,raw:md});}return {events,nextCursor:d.nextPageToken};}
    if(kind==='DRIVE'){const u=new URL('https://www.googleapis.com/drive/v3/files');u.searchParams.set('pageSize','100');u.searchParams.set('fields','nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink,trashed,owners(emailAddress))');u.searchParams.set('orderBy','modifiedTime desc');if(cursor)u.searchParams.set('pageToken',cursor);const r=await fetch(u,{headers:h});const d:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Google Drive sync failed: ${d.error?.message||r.status}`);return {events:(d.files||[]).map((f:any)=>({externalId:f.id,kind,title:f.name,updatedAt:f.modifiedTime,cancelled:!!f.trashed,raw:f})),nextCursor:d.nextPageToken};}
    throw new ServiceUnavailableException(`Google resource ${kind} is not supported by Google provider`);
  }
}
