import { Injectable, ServiceUnavailableException } from '@nestjs/common';
import { IntegrationProviderPort, IntegrationKind, TokenSet, ExternalEvent } from './integration-provider.port';
@Injectable()
export class MicrosoftIntegrationProvider implements IntegrationProviderPort {
  readonly provider='MICROSOFT' as const;
  private config(){const id=process.env.MICROSOFT_CLIENT_ID,secret=process.env.MICROSOFT_CLIENT_SECRET;if(!id||!secret)throw new ServiceUnavailableException('Microsoft integration is not configured');return {id,secret,tenant:process.env.MICROSOFT_TENANT_ID||'common'};}
  buildAuthorizeUrl(kind:IntegrationKind,state:string,redirectUri:string){const {id,tenant}=this.config();const scopes:Record<IntegrationKind,string>={CALENDAR:'offline_access Calendars.Read',EMAIL:'offline_access Mail.Read',DRIVE:'offline_access Files.Read',TEAMS:'offline_access OnlineMeetings.Read',SHAREPOINT:'offline_access Sites.Read.All'};return `https://login.microsoftonline.com/${tenant}/oauth2/v2.0/authorize?client_id=${encodeURIComponent(id)}&response_type=code&redirect_uri=${encodeURIComponent(redirectUri)}&response_mode=query&scope=${encodeURIComponent(scopes[kind])}&state=${encodeURIComponent(state)}`;}
  async exchangeCode(_kind:IntegrationKind,code:string,redirectUri:string):Promise<TokenSet>{const {id,secret,tenant}=this.config();const body=new URLSearchParams({client_id:id,client_secret:secret,code,redirect_uri:redirectUri,grant_type:'authorization_code'});const r=await fetch(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const d:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Microsoft token exchange failed: ${d.error_description||d.error||r.status}`);return {accessToken:d.access_token,refreshToken:d.refresh_token,expiresAt:d.expires_in?new Date(Date.now()+d.expires_in*1000):undefined,scope:d.scope};}
  async refresh(refreshToken:string):Promise<TokenSet>{const {id,secret,tenant}=this.config();const body=new URLSearchParams({client_id:id,client_secret:secret,refresh_token:refreshToken,grant_type:'refresh_token',scope:'offline_access'});const r=await fetch(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const d:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Microsoft token refresh failed: ${d.error_description||d.error||r.status}`);return {accessToken:d.access_token,refreshToken:d.refresh_token,expiresAt:d.expires_in?new Date(Date.now()+d.expires_in*1000):undefined,scope:d.scope};}
  async pull(kind:IntegrationKind,token:string,cursor?:string){const h={Authorization:`Bearer ${token}`};let url=cursor; if(!url){url=kind==='CALENDAR'?'https://graph.microsoft.com/v1.0/me/calendarView/delta?startDateTime=2000-01-01T00:00:00Z&endDateTime=2100-01-01T00:00:00Z':kind==='EMAIL'?'https://graph.microsoft.com/v1.0/me/messages/delta':kind==='DRIVE'?'https://graph.microsoft.com/v1.0/me/drive/root/delta':kind==='TEAMS'?'https://graph.microsoft.com/v1.0/me/onlineMeetings?$top=100':'https://graph.microsoft.com/v1.0/sites?search=*';}
    const r=await fetch(url,{headers:h});const d:any=await r.json();if(!r.ok)throw new ServiceUnavailableException(`Microsoft Graph ${kind} sync failed: ${d.error?.message||r.status}`);const vals=d.value||[];const events:ExternalEvent[]=vals.map((e:any)=>{if(kind==='CALENDAR')return {externalId:e.id,kind,title:e.subject,startsAt:e.start?.dateTime,endsAt:e.end?.dateTime,attendees:(e.attendees||[]).map((a:any)=>a.emailAddress?.address).filter(Boolean),updatedAt:e.lastModifiedDateTime,etag:e['@odata.etag'],cancelled:!!e['@removed']||e.isCancelled===true,meetingUrl:e.onlineMeeting?.joinUrl,location:e.location?.displayName,raw:e};if(kind==='EMAIL')return {externalId:e.id,kind,title:e.subject,subject:e.subject,sender:e.from?.emailAddress?.address,recipients:(e.toRecipients||[]).map((x:any)=>x.emailAddress?.address).filter(Boolean),threadId:e.conversationId,updatedAt:e.lastModifiedDateTime,etag:e['@odata.etag'],cancelled:!!e['@removed'],raw:e};if(kind==='DRIVE')return {externalId:e.id,kind,title:e.name,updatedAt:e.lastModifiedDateTime,etag:e.eTag,cancelled:!!e.deleted,raw:e};if(kind==='TEAMS')return {externalId:e.id,kind,title:e.subject,updatedAt:e.creationDateTime,meetingUrl:e.joinWebUrl,raw:e};return {externalId:e.id,kind,title:e.displayName,updatedAt:e.lastModifiedDateTime,raw:e};});return {events,nextCursor:d['@odata.deltaLink']||d['@odata.nextLink']};}
}
