import { Injectable, NotFoundException } from '@nestjs/common';
import { CommitmentStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuthorizationService } from '../common/authorization/authorization.service';
import { AuditService } from '../audit/audit.service';
import { EventBusService } from '../event-bus/event-bus.service';
import { DOMAIN_EVENT_TYPES } from '../event-bus/event-bus.constants';
import { DataLifecycleService } from '../common/data-lifecycle/data-lifecycle.service';
import { NotificationsService } from '../notifications/notifications.service';
import { SYSTEM_USER_ID } from '../common/system-actor';
import { EntityResponseDto } from '../common/dto/entity-response.dto';
import { parsePagination } from '../common/pagination';

@Injectable()
export class CommitmentsService {
  constructor(private readonly prisma: PrismaService, private readonly authorization: AuthorizationService, private readonly audit: AuditService, private readonly notifications: NotificationsService, private readonly eventBus: EventBusService, private readonly lifecycle: DataLifecycleService) {}

  private async resolveContext(userId: string, data: any) {
    const orgIds: string[] = [];
    if (data.organizationId) orgIds.push(data.organizationId);
    if (data.relationshipId) { const r = await this.prisma.relationship.findUnique({ where: { id: data.relationshipId }, select: { sourceOrganizationId: true, targetOrganizationId: true } }); if (!r) throw new NotFoundException('Relationship not found'); orgIds.push(r.sourceOrganizationId, r.targetOrganizationId); }
    if (data.meetingId) { const m = await this.prisma.meeting.findUnique({ where: { id: data.meetingId }, select: { organizationId: true, relationshipId: true } }); if (!m) throw new NotFoundException('Meeting not found'); if (m.organizationId) orgIds.push(m.organizationId); if (m.relationshipId) { const r=await this.prisma.relationship.findUniqueOrThrow({where:{id:m.relationshipId},select:{sourceOrganizationId:true,targetOrganizationId:true}}); orgIds.push(r.sourceOrganizationId,r.targetOrganizationId); } }
    if (data.personId) { const p=await this.prisma.person.findUnique({where:{id:data.personId},select:{organizationId:true}}); if(!p)throw new NotFoundException('Person not found'); orgIds.push(p.organizationId); }
    if (data.projectId) { const p=await this.prisma.project.findUnique({where:{id:data.projectId},select:{organizationId:true,ownerId:true}}); if(!p)throw new NotFoundException('Project not found'); if(p.organizationId)orgIds.push(p.organizationId); else if(p.ownerId!==userId)throw new NotFoundException('Project not found'); }
    const unique=[...new Set(orgIds.filter(Boolean))]; if(unique.length)await this.authorization.assertAnyOrganizationAccess(userId,unique); return unique[0];
  }
  private normalize(data:any,userId:string,organizationId?:string){const allowed=['description','source','receiver','evidence','risk','status','dueAt','reminderAt','ownerId','relationshipId','meetingId','personId','projectId','organizationId','recommendationId','completionAt','attachments'];const out:any={};for(const k of allowed)if(data[k]!==undefined)out[k]=data[k];out.ownerId??=userId;if(organizationId&&!out.organizationId)out.organizationId=organizationId;for(const k of ['dueAt','reminderAt','completionAt'])if(out[k]!==undefined&&out[k]!==null)out[k]=new Date(out[k]);if(out.status===CommitmentStatus.FULFILLED&&!out.completionAt)out.completionAt=new Date();return out;}

  async list(userId:string,page?:string,pageSize?:string){const ids=await this.authorization.accessibleOrganizationIds(userId);const p=parsePagination(page,pageSize,{page:1,pageSize:50});const where:Prisma.CommitmentWhereInput={deletedAt:null,...(ids?{OR:[{ownerId:userId},{organizationId:{in:ids}},{relationship:{OR:[{sourceOrganizationId:{in:ids}},{targetOrganizationId:{in:ids}}]}},{meeting:{organizationId:{in:ids}}},{project:{organizationId:{in:ids}}}]}:{ownerId:userId})};const [items,total]=await this.prisma.$transaction([this.prisma.commitment.findMany({where,include:{owner:true,relationship:true,meeting:true,project:true,person:true,organization:true},orderBy:{dueAt:'asc'},skip:p.skip,take:p.take}),this.prisma.commitment.count({where})]);return{items:EntityResponseDto.many('Commitment',items),page:p.page,pageSize:p.pageSize,total,totalPages:Math.ceil(total/p.pageSize)};}
  async get(userId:string,id:string){const row=await this.prisma.commitment.findUnique({where:{id},include:{owner:true,relationship:true,meeting:true,project:true,person:true,organization:true}});if(!row||row.deletedAt)throw new NotFoundException('Commitment not found');await this.resolveContext(userId,row);if(!row.relationship&&!row.meeting&&!row.project&&!row.organizationId&&row.ownerId!==userId)throw new NotFoundException('Commitment not found');return EntityResponseDto.from('Commitment',row);}
  async create(userId:string,data:any){const organizationId=await this.resolveContext(userId,data);const payload=this.normalize(data,userId,organizationId);const row=await this.eventBus.transaction(async tx=>{const created=await tx.commitment.create({data:payload});await this.audit.logMutation({userId,action:'CREATE',entityType:'Commitment',entityId:created.id,organizationId:created.organizationId??undefined,after:created},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.COMMITMENT_CREATED,aggregateType:'Commitment',aggregateId:created.id,organizationId:created.organizationId??undefined,actorId:userId,payload:created as any});return created;});return EntityResponseDto.from('Commitment',row);}
  async update(userId:string,id:string,data:any){const current=await this.prisma.commitment.findUnique({where:{id}});if(!current||current.deletedAt)throw new NotFoundException('Commitment not found');await this.resolveContext(userId,current);const org=await this.resolveContext(userId,{...current,...data});const payload=this.normalize(data,userId,org);const updated=await this.eventBus.transaction(async tx=>{const next=await tx.commitment.update({where:{id},data:payload});await this.audit.logMutation({userId,action:'UPDATE',entityType:'Commitment',entityId:id,organizationId:next.organizationId??undefined,before:current,after:next},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.COMMITMENT_UPDATED,aggregateType:'Commitment',aggregateId:next.id,organizationId:next.organizationId??undefined,actorId:userId,payload:next as any});if(current.status!==CommitmentStatus.FULFILLED&&next.status===CommitmentStatus.FULFILLED)await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.COMMITMENT_COMPLETED,aggregateType:'Commitment',aggregateId:next.id,organizationId:next.organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.from('Commitment',updated);}
  async remove(userId:string,id:string){const row=await this.get(userId,id);const updated=await this.eventBus.transaction(async tx=>{const next=await this.lifecycle.softDelete(userId,'Commitment',row.id,'remove',tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.COMMITMENT_DELETED,aggregateType:'Commitment',aggregateId:row.id,organizationId:(next as any).organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.from('Commitment',updated);}
  async markOverdue(userId:string,id:string){const row=await this.get(userId,id);if(row.status!==CommitmentStatus.OPEN||!row.dueAt||row.dueAt>new Date())return row;const updated=await this.eventBus.transaction(async tx=>{const next=await tx.commitment.update({where:{id},data:{status:'OVERDUE'}});await this.audit.logMutation({userId,action:'UPDATE',entityType:'Commitment',entityId:id,before:row,after:next,reason:'commitment_marked_overdue'},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.COMMITMENT_OVERDUE,aggregateType:'Commitment',aggregateId:id,organizationId:(next as any).organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.from('Commitment',updated);}
  async listOverdue(userId:string,page?:string,pageSize?:string){const ids=await this.authorization.accessibleOrganizationIds(userId);const p=parsePagination(page,pageSize);const where:Prisma.CommitmentWhereInput={deletedAt:null,status:'OVERDUE',...(ids?{OR:[{ownerId:userId},{organizationId:{in:ids}},{relationship:{OR:[{sourceOrganizationId:{in:ids}},{targetOrganizationId:{in:ids}}]}},{meeting:{organizationId:{in:ids}}},{project:{organizationId:{in:ids}}}]}:{ownerId:userId})};const [items,total]=await this.prisma.$transaction([this.prisma.commitment.findMany({where,include:{owner:true,relationship:true,meeting:true,project:true,person:true,organization:true},orderBy:{dueAt:'asc'},skip:p.skip,take:p.take}),this.prisma.commitment.count({where})]);return{items:EntityResponseDto.many('Commitment',items),page:p.page,pageSize:p.pageSize,total,totalPages:Math.ceil(total/p.pageSize)};}
  async listDueSoon(userId:string,days=7,page?:string,pageSize?:string){const ids=await this.authorization.accessibleOrganizationIds(userId);const p=parsePagination(page,pageSize);const horizon=new Date(Date.now()+Math.max(1,days)*86400000);const where:Prisma.CommitmentWhereInput={deletedAt:null,status:'OPEN',dueAt:{gte:new Date(),lte:horizon},...(ids?{OR:[{ownerId:userId},{organizationId:{in:ids}},{relationship:{OR:[{sourceOrganizationId:{in:ids}},{targetOrganizationId:{in:ids}}]}},{meeting:{organizationId:{in:ids}}},{project:{organizationId:{in:ids}}}]}:{ownerId:userId})};const [items,total]=await this.prisma.$transaction([this.prisma.commitment.findMany({where,include:{owner:true,relationship:true,meeting:true,project:true,person:true,organization:true},orderBy:{dueAt:'asc'},skip:p.skip,take:p.take}),this.prisma.commitment.count({where})]);return{items:EntityResponseDto.many('Commitment',items),page:p.page,pageSize:p.pageSize,total,totalPages:Math.ceil(total/p.pageSize)};}
  async sweepOverdue(actorId:string=SYSTEM_USER_ID){const batchSize=250;const results:string[]=[];let cursor:string|undefined;for(;;){const due=await this.prisma.commitment.findMany({where:{deletedAt:null,status:'OPEN',dueAt:{lt:new Date()}},select:{id:true,ownerId:true,description:true,organizationId:true},orderBy:{id:'asc'},take:batchSize,...(cursor?{cursor:{id:cursor},skip:1}:{})});if(!due.length)break;for(const row of due){await this.eventBus.transaction(async tx=>{const claimed=await tx.commitment.updateMany({where:{id:row.id,deletedAt:null,status:'OPEN'},data:{status:'OVERDUE'}});if(!claimed.count)return;const next=await tx.commitment.findUniqueOrThrow({where:{id:row.id}});await this.audit.logMutation({userId:actorId,action:'UPDATE',entityType:'Commitment',entityId:row.id,before:row,after:next,reason:'scheduled_overdue_sweep'},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.COMMITMENT_OVERDUE,aggregateType:'Commitment',aggregateId:row.id,organizationId:row.organizationId??undefined,actorId:actorId,payload:next as any});});await this.notifications.create(row.ownerId,{type:'ALERT',title:'تعهد عقب‌افتاده',body:`تعهد «${row.description}» از سررسید خود عبور کرده و نیاز به پیگیری دارد.`,priority:'HIGH',deepLink:`/commitments/${row.id}`,channel:'IN_APP'}).catch(()=>undefined);results.push(row.id);}cursor=due[due.length-1].id;if(due.length<batchSize)break;}return{swept:results.length,commitmentIds:results};}
}
