'use client'; import {useEffect,useState,useCallback} from 'react'; import {api} from '../_lib/api'; import {Badge,Empty,ErrorCard,Loading,PageHeader} from '../_components/page-ui'; import {useWorkspace} from '../_components/workspace';
type Run={id:string;connectionId:string;kind:string;startedAt:string;completedAt?:string|null;status:string;seen:number;created:number;updated:number;matchedPeople:number;matchedOrganizations:number;linkedRelationships:number;errors?:unknown[]|string|null};
export default function Integrations(){const {scopeId,can}=useWorkspace();const canRead=can('integration.read');const canWrite=can('integration.write');const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[runs,setRuns]=useState<Record<string,Run[]>>({}),[openRuns,setOpenRuns]=useState<Record<string,boolean>>({});
 const[provider,setProvider]=useState('GOOGLE'),[kind,setKind]=useState('CALENDAR');
 const load=useCallback(async()=>{if(!canRead){setItems([]);return}try{setItems(await api<any[]>('/integrations'))}catch(e){setError(e instanceof Error?e.message:String(e))}},[canRead]);useEffect(()=>{void load()},[load]);
 async function connect(){if(!canWrite)return;setBusy('connect');setError('');try{const r=await api<any>('/integrations/authorize',{method:'POST',body:JSON.stringify({provider,kind,organizationId:scopeId!=='all'?scopeId:undefined})});window.location.href=r.authorizeUrl}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 async function sync(id:string){if(!canWrite)return;setBusy('sync'+id);setError('');try{await api('/integrations/'+id+'/sync',{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 async function disconnect(x:any){if(!canWrite)return;if(!window.confirm(`اتصال ${x.provider} · ${x.kind} قطع شود؟`))return;setBusy('del'+x.id);setError('');try{await api('/integrations/'+x.id,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 async function toggleRuns(x:any){if(!canRead)return;const id=x.id,open=!openRuns[id];setOpenRuns(r=>({...r,[id]:open}));if(!open||runs[id])return;setBusy('runs'+id);setError('');try{const list:any=await api('/integrations/'+id+'/sync-runs');setRuns(r=>({...r,[id]:Array.isArray(list)?list:list?.items??[]}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 const runTone=(s:string)=>{if(s==='SUCCESS'||s==='COMPLETED')return'success';if(s==='ERROR')return'danger';if(s==='PARTIAL'||s==='RUNNING')return'warning';return'neutral'};
 if(!canRead)return <main className="feature-page"><PageHeader eyebrow="INTEGRATIONS" title="Calendar & Email Connections" description="اتصال‌های سازمانی و تاریخچه همگام‌سازی."/><section className="panel"><Empty>مجوز مشاهده یکپارچه‌سازی‌ها برای شما فعال نیست.</Empty></section></main>;
 return <main className="feature-page"><PageHeader eyebrow="INTEGRATIONS" title="Calendar & Email Connections" description="OAuth state، tenant scope، sync cursor، Sync Run history و health به‌صورت server-side مدیریت می‌شوند."/>
 <ErrorCard message={error}/>
 {canWrite&&<section className="panel">
  <div className="panel-title"><div><h2>اتصال جدید</h2><p>پس از OAuth callback، اتصال ثبت و قابل Sync می‌شود.</p></div></div>
  <div className="toolbar"><select aria-label="Provider" value={provider} onChange={e=>setProvider(e.target.value)}><option value="GOOGLE">Google</option><option value="MICROSOFT">Microsoft</option></select><select aria-label="Kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="CALENDAR">Calendar</option><option value="EMAIL">Email</option></select><button className="primary-action" onClick={connect} disabled={!!busy}>{busy==='connect'?'در حال هدایت به OAuth…':'Connect'}</button></div>
 </section>}
 <section className="panel">
  <div className="panel-title"><div><h2>اتصال‌ها</h2><p>{items.length} اتصال</p></div><button className="secondary-action" onClick={load} disabled={!!busy}>بازخوانی</button></div>
  {items.length===0?<Empty>اتصالی ثبت نشده است.</Empty>:<div className="list">{items.map(x=><article className="panel compact" key={x.id}>
   <div className="panel-title"><div><strong>{x.provider} · {x.kind}</strong><small className="muted">{x.status} · آخرین Sync: {x.lastSyncAt||'—'}{x.lastError?` · ${x.lastError}`:''}</small></div><span><Badge tone={x.status==='CONNECTED'?'success':x.status==='ERROR'?'danger':'neutral'}>{x.status}</Badge>{canWrite&&<button className="secondary-action" onClick={()=>sync(x.id)} disabled={!!busy}>Sync</button>}<button className="secondary-action" onClick={()=>toggleRuns(x)} disabled={!!busy}>{openRuns[x.id]?'بستن تاریخچه':'تاریخچه Sync'}</button>{canWrite&&<button className="danger-action" onClick={()=>disconnect(x)} disabled={!!busy}>Disconnect</button>}</span></div>
   {openRuns[x.id]&&<div className="list">{runs[x.id]&&runs[x.id].length===0?<Empty>هیچ Sync Run ثبت نشده.</Empty>:runs[x.id]?.map(r=>{const errs=r.errors;return <article className="detail-item" key={r.id}><div className="row"><strong>{r.kind}</strong><Badge tone={runTone(r.status)}>{r.status}</Badge></div><small className="muted">شروع {new Date(r.startedAt).toLocaleString()}{r.completedAt?` · پایان ${new Date(r.completedAt).toLocaleString()}`:''}</small><div className="detail-grid"><div><small>seen</small><strong>{r.seen}</strong></div><div><small>created</small><strong>{r.created}</strong></div><div><small>updated</small><strong>{r.updated}</strong></div><div><small>matchedPeople</small><strong>{r.matchedPeople}</strong></div><div><small>matchedOrganizations</small><strong>{r.matchedOrganizations}</strong></div><div><small>linkedRelationships</small><strong>{r.linkedRelationships}</strong></div></div>{errs&&Array.isArray(errs)&&errs.length>0&&<small className="muted">خطاها: {errs.join('، ')}</small>}</article>})}</div>}
  </article>)}</div>}
 </section>
 </main>}