'use client'; import {useEffect,useState,useCallback} from 'react'; import {api} from '../_lib/api'; import {fa} from '../_lib/fa'; import {Badge,Empty,ErrorCard,Loading,PageHeader} from '../_components/page-ui';
type Run={id:string;connectionId:string;kind:string;startedAt:string;completedAt?:string|null;status:string;seen:number;created:number;updated:number;matchedPeople:number;matchedOrganizations:number;linkedRelationships:number;errors?:unknown[]|string|null};
export default function Integrations(){const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[runs,setRuns]=useState<Record<string,Run[]>>({}),[openRuns,setOpenRuns]=useState<Record<string,boolean>>({});
 const[provider,setProvider]=useState('GOOGLE'),[kind,setKind]=useState('CALENDAR');
 const load=useCallback(async()=>{try{setItems(await api<any[]>('/integrations'))}catch(e){setError(e instanceof Error?e.message:String(e))}},[setItems,setError]);useEffect(()=>{load()},[load]);
 async function connect(){setBusy('connect');setError('');try{const r=await api<any>('/integrations/authorize',{method:'POST',body:JSON.stringify({provider,kind})});window.location.href=r.authorizeUrl}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 async function sync(id:string){setBusy('sync'+id);setError('');try{await api('/integrations/'+id+'/sync',{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 async function disconnect(x:any){if(!window.confirm(`اتصال ${fa(x.provider)} · ${fa(x.kind)} قطع شود؟`))return;setBusy('del'+x.id);setError('');try{await api('/integrations/'+x.id,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 async function toggleRuns(x:any){const id=x.id,open=!openRuns[id];setOpenRuns(r=>({...r,[id]:open}));if(!open||runs[id])return;setBusy('runs'+id);setError('');try{const list:any=await api('/integrations/'+id+'/sync-runs');setRuns(r=>({...r,[id]:Array.isArray(list)?list:list?.items??[]}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 const runTone=(s:string)=>{if(s==='SUCCESS'||s==='COMPLETED')return'success';if(s==='ERROR')return'danger';if(s==='PARTIAL'||s==='RUNNING')return'warning';return'neutral'};
 return <main className="feature-page"><PageHeader eyebrow="یکپارچه‌سازی" title="اتصال تقویم و ایمیل" description="وضعیت OAuth، محدودهٔ مستأجر، نشانگر همگام‌سازی، تاریخچهٔ اجرای همگام‌سازی و سلامت به‌صورت سمت سرور مدیریت می‌شوند."/>
 <ErrorCard message={error}/>
 <section className="panel">
  <div className="panel-title"><div><h2>اتصال جدید</h2><p>پس از بازگشت OAuth، اتصال ثبت و قابل همگام‌سازی می‌شود.</p></div></div>
  <div className="toolbar"><select aria-label="سرویس‌دهنده" value={provider} onChange={e=>setProvider(e.target.value)}><option value="GOOGLE">گوگل</option><option value="MICROSOFT">مایکروسافت</option></select><select aria-label="نوع" value={kind} onChange={e=>setKind(e.target.value)}><option value="CALENDAR">تقویم</option><option value="EMAIL">ایمیل</option></select><button className="primary-action" onClick={connect} disabled={!!busy}>{busy==='connect'?'در حال هدایت به OAuth…':'اتصال'}</button></div>
 </section>
 <section className="panel">
  <div className="panel-title"><div><h2>اتصال‌ها</h2><p>{items.length} اتصال</p></div><button className="secondary-action" onClick={load} disabled={!!busy}>بازخوانی</button></div>
  {items.length===0?<Empty>اتصالی ثبت نشده است.</Empty>:<div className="list">{items.map(x=><article className="panel compact" key={x.id}>
   <div className="panel-title"><div><strong>{fa(x.provider)} · {fa(x.kind)}</strong><small className="muted">{fa(x.status)} · آخرین همگام‌سازی: {x.lastSyncAt||'—'}{x.lastError?` · ${x.lastError}`:''}</small></div><span><Badge tone={x.status==='CONNECTED'?'success':x.status==='ERROR'?'danger':'neutral'}>{fa(x.status)}</Badge><button className="secondary-action" onClick={()=>sync(x.id)} disabled={!!busy}>همگام‌سازی</button><button className="secondary-action" onClick={()=>toggleRuns(x)} disabled={!!busy}>{openRuns[x.id]?'بستن تاریخچه':'تاریخچهٔ همگام‌سازی'}</button><button className="danger-action" onClick={()=>disconnect(x)} disabled={!!busy}>قطع اتصال</button></span></div>
   {openRuns[x.id]&&<div className="list">{runs[x.id]&&runs[x.id].length===0?<Empty>هیچ اجرای همگام‌سازی ثبت نشده است.</Empty>:runs[x.id]?.map(r=>{const errs=r.errors;return <article className="detail-item" key={r.id}><div className="row"><strong>{fa(r.kind)}</strong><Badge tone={runTone(r.status)}>{fa(r.status)}</Badge></div><small className="muted">شروع {new Date(r.startedAt).toLocaleString()}{r.completedAt?` · پایان ${new Date(r.completedAt).toLocaleString()}`:''}</small><div className="detail-grid"><div><small>مشاهده‌شده</small><strong>{r.seen}</strong></div><div><small>ایجادشده</small><strong>{r.created}</strong></div><div><small>به‌روزرسانی‌شده</small><strong>{r.updated}</strong></div><div><small>اشخاص تطبیق‌یافته</small><strong>{r.matchedPeople}</strong></div><div><small>سازمان‌های تطبیق‌یافته</small><strong>{r.matchedOrganizations}</strong></div><div><small>روابط پیوندخورده</small><strong>{r.linkedRelationships}</strong></div></div>{errs&&Array.isArray(errs)&&errs.length>0&&<small className="muted">خطاها: {errs.join('، ')}</small>}</article>})}</div>}
  </article>)}</div>}
 </section>
 </main>}