import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InteractionKind, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuthorizationService } from '../common/authorization/authorization.service';
import { AuditService } from '../audit/audit.service';
import { EventBusService } from '../event-bus/event-bus.service';
import { DOMAIN_EVENT_TYPES } from '../event-bus/event-bus.constants';
import { DataLifecycleService } from '../common/data-lifecycle/data-lifecycle.service';
import { EntityResponseDto } from '../common/dto/entity-response.dto';
import { parsePagination } from '../common/pagination';

@Injectable()
export class InteractionsService {
  constructor(private readonly prisma: PrismaService, private readonly authorization: AuthorizationService, private readonly audit: AuditService, private readonly eventBus: EventBusService, private readonly lifecycle: DataLifecycleService) {}
  private async assertAccess(userId:string,row:any,write=false){const orgIds=[row.organizationId,row.relationship?.sourceOrganizationId,row.relationship?.targetOrganizationId,row.person?.organizationId].filter(Boolean) as string[];if(orgIds.length)return this.authorization.assertAnyOrganizationAccess(userId,orgIds);if(row.userId!==userId)throw new NotFoundException('Interaction not found');}
  private async resolveOrg(userId:string,data:any){const ids:string[]=[];if(data.organizationId)ids.push(data.organizationId);if(data.personId){const p=await this.prisma.person.findUnique({where:{id:data.personId},select:{organizationId:true}});if(!p)throw new NotFoundException('Person not found');ids.push(p.organizationId);}if(data.relationshipId){const r=await this.prisma.relationship.findUnique({where:{id:data.relationshipId},select:{sourceOrganizationId:true,targetOrganizationId:true}});if(!r)throw new NotFoundException('Relationship not found');ids.push(r.sourceOrganizationId,r.targetOrganizationId);}if(ids.length)await this.authorization.assertAnyOrganizationAccess(userId,[...new Set(ids)]);return ids[0];}
  private normalize(data:any){const allowed=['type','subject','summary','outcome','durationMinutes','followUpRequired','followUpAt','attachments','importance','sentiment','occurredAt','organizationId','personId','relationshipId'];const out:any={};for(const k of allowed)if(data[k]!==undefined)out[k]=data[k];if(out.occurredAt!==undefined)out.occurredAt=new Date(out.occurredAt);if(out.followUpAt!==undefined)out.followUpAt=out.followUpAt?new Date(out.followUpAt):null;return out;}
  async list(userId:string,relationshipId?:string,followUpOnly=false,page?:string,pageSize?:string){const ids=await this.authorization.accessibleOrganizationIds(userId);const p=parsePagination(page,pageSize,{page:1,pageSize:50});const where:Prisma.InteractionWhereInput={deletedAt:null,...(relationshipId?{relationshipId}:{}),...(followUpOnly?{followUpRequired:true,followUpAt:{not:null}}:{}),...(ids?{OR:[{organizationId:{in:ids}},{userId},{person:{organizationId:{in:ids}}},{relationship:{OR:[{sourceOrganizationId:{in:ids}},{targetOrganizationId:{in:ids}}]}}]}:{userId})};const [items,total]=await this.prisma.$transaction([this.prisma.interaction.findMany({where,orderBy:{occurredAt:'desc'},skip:p.skip,take:p.take,include:{organization:true,person:true,relationship:true}}),this.prisma.interaction.count({where})]);return{items:EntityResponseDto.many('Interaction',items),page:p.page,pageSize:p.pageSize,total,totalPages:Math.ceil(total/p.pageSize)};}
  async timeline(userId:string,relationshipId:string,page?:string,pageSize?:string){const relationship=await this.prisma.relationship.findUnique({where:{id:relationshipId},select:{id:true,sourceOrganizationId:true,targetOrganizationId:true}});if(!relationship)throw new NotFoundException('Relationship not found');await this.authorization.assertAnyOrganizationAccess(userId,[relationship.sourceOrganizationId,relationship.targetOrganizationId]);const p=parsePagination(page,pageSize,{page:1,pageSize:50});const where={relationshipId,deletedAt:null};const [items,total]=await this.prisma.$transaction([this.prisma.interaction.findMany({where,orderBy:{occurredAt:'desc'},skip:p.skip,take:p.take,include:{organization:true,person:true}}),this.prisma.interaction.count({where})]);return{items:EntityResponseDto.many('Interaction',items),page:p.page,pageSize:p.pageSize,total,totalPages:Math.ceil(total/p.pageSize)};}
  async get(userId:string,id:string){const row=await this.prisma.interaction.findUnique({where:{id},include:{relationship:{select:{sourceOrganizationId:true,targetOrganizationId:true}},organization:true,person:true}});if(!row||row.deletedAt)throw new NotFoundException('Interaction not found');await this.assertAccess(userId,row);return EntityResponseDto.from('Interaction',row);}
  async create(userId:string,data:any){if(!data.organizationId&&!data.relationshipId&&!data.personId)throw new ForbiddenException('Interaction must be linked to an organization, relationship or person');const organizationId=await this.resolveOrg(userId,data);const type=await this.prisma.interactionType.findUnique({where:{key:data.type}});if(!type)throw new ForbiddenException('Unknown interaction type');const payload={...this.normalize(data),interactionTypeId:type.id,userId,organizationId:data.organizationId??organizationId};const created=await this.eventBus.transaction(async tx=>{const row=await tx.interaction.create({data:payload});await this.audit.logMutation({userId,action:'CREATE',entityType:'Interaction',entityId:row.id,organizationId:row.organizationId??undefined,after:row},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.INTERACTION_CREATED,aggregateType:'Interaction',aggregateId:row.id,organizationId:row.organizationId??undefined,actorId:userId,payload:row as any});return row;});return EntityResponseDto.from('Interaction',created);}
  async update(userId:string,id:string,data:any){const row=await this.prisma.interaction.findUnique({where:{id},include:{relationship:{select:{sourceOrganizationId:true,targetOrganizationId:true}},person:{select:{organizationId:true}}}});if(!row||row.deletedAt)throw new NotFoundException('Interaction not found');await this.assertAccess(userId,row,true);const merged={...row,...data};const organizationId=await this.resolveOrg(userId,merged);const payload=this.normalize(data);delete payload.userId;const type=data.type?await this.prisma.interactionType.findUnique({where:{key:data.type}}):null;if(data.type&&!type)throw new ForbiddenException('Unknown interaction type');if(type)payload.interactionTypeId=type.id;if(data.organizationId===undefined&&organizationId)payload.organizationId=organizationId;const updated=await this.eventBus.transaction(async tx=>{const next=await tx.interaction.update({where:{id},data:payload});await this.audit.logMutation({userId,action:'UPDATE',entityType:'Interaction',entityId:id,organizationId:next.organizationId??undefined,before:row,after:next},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.INTERACTION_UPDATED,aggregateType:'Interaction',aggregateId:next.id,organizationId:next.organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.from('Interaction',updated);}
  async remove(userId:string,id:string){const row=await this.get(userId,id);const archived=await this.eventBus.transaction(async tx=>{const next=await this.lifecycle.softDelete(userId,'Interaction',id,'archive',tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.INTERACTION_DELETED,aggregateType:'Interaction',aggregateId:next.id,organizationId:(next as any).organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.fromUnknown(archived);}
}
