import { BadRequestException, Injectable, UnauthorizedException } from '@nestjs/common';
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from 'node:crypto';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../../audit/audit.service';

function base32Encode(input: Buffer){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0,out='';for(const b of input){value=(value<<8)|b;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5}}if(bits>0)out+=alphabet[(value<<(5-bits))&31];return out;}
function base32Decode(input:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0,out:number[]=[];for(const c of input.replace(/=+$/,'').toUpperCase()){const n=alphabet.indexOf(c);if(n<0)throw new BadRequestException('Invalid TOTP secret');value=(value<<5)|n;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8}}return Buffer.from(out);}
function totp(secret:string, counter:number){const key=base32Decode(secret);const msg=Buffer.alloc(8);msg.writeBigUInt64BE(BigInt(counter));const h=createHmac('sha1',key).update(msg).digest();const o=h[h.length-1]&15;const code=((h[o]&127)<<24)|((h[o+1]&255)<<16)|((h[o+2]&255)<<8)|(h[o+3]&255);return String(code%1_000_000).padStart(6,'0');}
@Injectable()
export class MfaService {
  private key(){const raw=process.env.MFA_ENCRYPTION_KEY;if(!raw)throw new Error('MFA_ENCRYPTION_KEY is required');return createHash('sha256').update(raw).digest();}
  private encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key(),iv);const body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${body.toString('base64url')}`;}
  private decrypt(value:string){const [iv,tag,body]=value.split('.');const decipher=createDecipheriv('aes-256-gcm',this.key(),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(body,'base64url')),decipher.final()]).toString('utf8');}
  constructor(private readonly prisma:PrismaService, private readonly audit:AuditService){}
  createRecoveryCodes(count=10){return Array.from({length:count},()=>randomBytes(6).toString('hex').toUpperCase());}
  hashRecoveryCode(code:string){return createHash('sha256').update(code.trim()).digest('hex');}
  async enroll(userId:string,label='Authenticator'){const secret=base32Encode(randomBytes(20));const device=await this.prisma.mfaDevice.create({data:{userId,label,secretEncrypted:this.encrypt(secret),enabled:true}});await this.audit.logMutation({userId,action:'TOKEN_CHANGE',entityType:'MfaDevice',entityId:device.id,after:{enabled:true,label},reason:'mfa-enrolled'});return {deviceId:device.id,secret,otpauthUrl:`otpauth://totp/SRIP:${encodeURIComponent(label)}?secret=${secret}&issuer=SRIP&algorithm=SHA1&digits=6&period=30`};}
  async verifyEnrollment(userId:string,deviceId:string,code:string){const d=await this.prisma.mfaDevice.findFirst({where:{id:deviceId,userId,enabled:true}});if(!d)throw new UnauthorizedException('MFA device not found');const secret=this.decrypt(d.secretEncrypted);if(!this.verifyCode(secret,code))throw new UnauthorizedException('Invalid MFA code');const codes=this.createRecoveryCodes();await this.prisma.$transaction([this.prisma.mfaDevice.update({where:{id:d.id},data:{verifiedAt:new Date()}}),...codes.map(c=>this.prisma.recoveryCode.create({data:{userId,codeHash:this.hashRecoveryCode(c)}}))]);await this.audit.logMutation({userId,action:'TOKEN_CHANGE',entityType:'MfaDevice',entityId:d.id,after:{verified:true,recoveryCodesIssued:codes.length},reason:'mfa-enrollment-verified'});return {verified:true,recoveryCodes:codes};}
  async verify(userId:string,code:string){const devices=await this.prisma.mfaDevice.findMany({where:{userId,enabled:true,verifiedAt:{not:null}}});if(!devices.length)return true;for(const d of devices){if(this.verifyCode(this.decrypt(d.secretEncrypted),code)){await this.prisma.mfaDevice.update({where:{id:d.id},data:{lastUsedAt:new Date()}});await this.audit.logMutation({userId,action:'TOKEN_CHANGE',entityType:'MfaDevice',entityId:d.id,after:{used:true},reason:'mfa-verified'});return true;}}const recovery=await this.prisma.recoveryCode.findFirst({where:{userId,codeHash:this.hashRecoveryCode(code),usedAt:null}});if(recovery){await this.prisma.recoveryCode.update({where:{id:recovery.id},data:{usedAt:new Date()}});await this.audit.logMutation({userId,action:'TOKEN_CHANGE',entityType:'RecoveryCode',entityId:recovery.id,after:{used:true},reason:'mfa-recovery-code-used'});return true;}throw new UnauthorizedException('Invalid MFA code');}
  async required(userId:string){return (await this.prisma.mfaDevice.count({where:{userId,enabled:true,verifiedAt:{not:null}}}))>0;}
  private verifyCode(secret:string,code:string){const now=Math.floor(Date.now()/1000/30);return [now-1,now,now+1].some(c=>totp(secret,c)===code.trim());}
}
