'use client';
import {FormEvent,useState} from 'react';
import {api} from '../_lib/api';
import {PageHeader,ErrorCard} from '../_components/page-ui';

function passwordError(value:string){if(value.length<12)return 'رمز عبور باید حداقل ۱۲ کاراکتر باشد.';if(!/[A-Z]/.test(value)||!/[a-z]/.test(value)||!/[0-9]/.test(value))return 'رمز عبور باید حروف بزرگ، حروف کوچک و عدد داشته باشد.';return ''}
export default function Register(){
 const[f,setF]=useState({email:'',password:'',name:''}),[e,setE]=useState(''),[ok,setOk]=useState(false),[verificationHref,setVerificationHref]=useState(''),[busy,setBusy]=useState(false);
 async function submit(x:FormEvent){x.preventDefault();setE('');const pwError=passwordError(f.password);if(pwError){setE(pwError);return}setBusy(true);try{const result:any=await api('/auth/register',{method:'POST',body:JSON.stringify({email:f.email.trim(),password:f.password,name:f.name.trim()})});setOk(true);if(result?.developmentVerificationToken)setVerificationHref(`/verify-email?token=${encodeURIComponent(result.developmentVerificationToken)}`)}catch(z){setE((z as Error).message)}finally{setBusy(false)}}
 return <main className="login"><section className="panel"><PageHeader eyebrow="IDENTITY" title="ایجاد حساب" description="ایجاد حساب طبق سیاست‌های امنیتی Backend."/><ErrorCard message={e}/>{ok?<div className="status-message" role="status"><p>ثبت‌نام انجام شد.</p>{verificationHref?<><p>در این محیط، لینک تأیید آماده است:</p><a className="primary-action" href={verificationHref}>تأیید ایمیل</a></>:<p>لطفاً ایمیل خود را برای تأیید بررسی کنید.</p>}</div>:<form className="entity-form" onSubmit={submit}><label>نام<input value={f.name} onChange={x=>setF({...f,name:x.target.value})} minLength={2} required/></label><label>ایمیل<input type="email" autoComplete="email" value={f.email} onChange={x=>setF({...f,email:x.target.value})} required/></label><label>رمز عبور<input type="password" autoComplete="new-password" value={f.password} onChange={x=>setF({...f,password:x.target.value})} minLength={12} required/><small className="muted">حداقل ۱۲ کاراکتر، شامل حروف بزرگ، حروف کوچک و عدد</small></label><button className="primary-action" disabled={busy}>{busy?'در حال ثبت‌نام…':'ثبت‌نام'}</button></form>}<a href="/login">بازگشت به ورود</a></section></main>
}
