import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, SafeAreaView, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Link } from 'expo-router';
import { apiGet, apiPost } from '../../services/api-client';
import { useSession } from '../../state/session';
import { colors, styles } from '../../lib/ui';

export default function Interactions(){
 const {token}=useSession(); const [items,setItems]=useState<any[]>([]); const [error,setError]=useState<string|null>(null); const [refreshing,setRefreshing]=useState(false); const [subject,setSubject]=useState(''); const [summary,setSummary]=useState(''); const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;setError(null);try{const x:any=await apiGet<any>('/interactions',token);setItems(x.items??(Array.isArray(x)?x:[]))}catch(e){setError(e instanceof Error?e.message:'Request failed')}},[token]); useEffect(()=>{load()},[load]);
 const save=async()=>{if(!token||!subject.trim())return;setBusy(true);setError(null);try{await apiPost('/interactions',{type:'NOTE',subject:subject.trim(),summary:summary.trim()||undefined},token);setSubject('');setSummary('');await load()}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}};
 return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>}><Text style={styles.title}>Interactions</Text><Text style={styles.subtitle}>Capture notes and interaction history from mobile.</Text>
 <View style={{ flexDirection: 'row', gap: 10, marginBottom: 8 }}><Link href="/add-interaction" asChild><TouchableOpacity style={[styles.button, { flex: 1, paddingVertical: 10 }]}><Text style={styles.buttonText}>+ Add interaction</Text></TouchableOpacity></Link><Link href="/add-note" asChild><TouchableOpacity style={[styles.button, { flex: 1, paddingVertical: 10 }]}><Text style={styles.buttonText}>+ Add note</Text></TouchableOpacity></Link></View>
 {error&&<Text style={styles.error}>{error}</Text>}<View style={styles.card}><Text style={styles.label}>New note</Text><TextInput style={styles.input} placeholder="Subject" value={subject} onChangeText={setSubject}/><TextInput style={styles.input} placeholder="Summary" value={summary} onChangeText={setSummary} multiline/><TouchableOpacity style={styles.button} onPress={save} disabled={busy}><Text style={styles.buttonText}>{busy?'Saving…':'Save note'}</Text></TouchableOpacity></View>{!items.length&&!error&&<ActivityIndicator/>}{items.map((item:any)=><Link key={item.id} href={{pathname:'/interaction/[id]',params:{id:item.id}}} asChild><TouchableOpacity activeOpacity={0.7}><View style={styles.card}><Text style={styles.label}>{item.type}</Text><Text style={styles.value}>{item.subject}</Text><Text style={styles.subtitle}>{item.summary||'No summary recorded.'}</Text><Text style={styles.subtitle}>{item.occurredAt?new Date(item.occurredAt).toLocaleString():''}</Text><Text style={{color:colors.accent,fontWeight:'700'}}>Open detail →</Text></View></TouchableOpacity></Link>)}</ScrollView></SafeAreaView>
}
