import { Injectable, NotFoundException } from '@nestjs/common';
import { OpportunityStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuthorizationService } from '../common/authorization/authorization.service';
import { AuditService } from '../audit/audit.service';
import { EventBusService } from '../event-bus/event-bus.service';
import { DOMAIN_EVENT_TYPES } from '../event-bus/event-bus.constants';
import { DataLifecycleService } from '../common/data-lifecycle/data-lifecycle.service';
import { EntityResponseDto } from '../common/dto/entity-response.dto';
import { parsePagination } from '../common/pagination';
@Injectable()
export class OpportunitiesService {
 constructor(private readonly prisma:PrismaService,private readonly authorization:AuthorizationService,private readonly audit:AuditService,private readonly eventBus:EventBusService,private readonly lifecycle:DataLifecycleService){}
 private async resolveOrg(userId:string,data:any){const ids:string[]=[];if(data.organizationId)ids.push(data.organizationId);if(data.projectId){const p=await this.prisma.project.findUnique({where:{id:data.projectId},select:{organizationId:true}});if(!p)throw new NotFoundException('Project not found');if(p.organizationId)ids.push(p.organizationId);}if(data.relationshipId){const r=await this.prisma.relationship.findUnique({where:{id:data.relationshipId},select:{sourceOrganizationId:true,targetOrganizationId:true}});if(!r)throw new NotFoundException('Relationship not found');ids.push(r.sourceOrganizationId,r.targetOrganizationId);}if(ids.length)await this.authorization.assertAnyOrganizationAccess(userId,[...new Set(ids)]);return ids[0];}
 private normalize(data:any,organizationId?:string){const allowed=['name','description','status','value','probability','organizationId','projectId','relationshipId'];const out:any={};for(const k of allowed)if(data[k]!==undefined)out[k]=data[k];if(organizationId&&!out.organizationId)out.organizationId=organizationId;return out;}
 async list(userId:string,page?:string,pageSize?:string){const ids=await this.authorization.accessibleOrganizationIds(userId);const p=parsePagination(page,pageSize,{page:1,pageSize:50});const where:Prisma.OpportunityWhereInput={deletedAt:null,...(ids?{OR:[{organizationId:{in:ids}},{project:{organizationId:{in:ids}}},{relationship:{OR:[{sourceOrganizationId:{in:ids}},{targetOrganizationId:{in:ids}}]}}]}:{})};const [items,total]=await this.prisma.$transaction([this.prisma.opportunity.findMany({where,include:{organization:true,project:true,relationship:true},orderBy:{updatedAt:'desc'},skip:p.skip,take:p.take}),this.prisma.opportunity.count({where})]);return{items:EntityResponseDto.many('Opportunity',items),page:p.page,pageSize:p.pageSize,total,totalPages:Math.ceil(total/p.pageSize)};}
 async get(userId:string,id:string){const row=await this.prisma.opportunity.findUnique({where:{id},include:{organization:true,project:true,relationship:true}});if(!row||row.deletedAt)throw new NotFoundException('Opportunity not found');await this.resolveOrg(userId,row);return EntityResponseDto.from('Opportunity',row);}
 async create(userId:string,data:any){const org=await this.resolveOrg(userId,data);const payload=this.normalize(data,org);const row=await this.eventBus.transaction(async tx=>{const created=await tx.opportunity.create({data:payload});await this.audit.logMutation({userId,action:'CREATE',entityType:'Opportunity',entityId:created.id,organizationId:created.organizationId??undefined,after:created},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.OPPORTUNITY_CREATED,aggregateType:'Opportunity',aggregateId:created.id,organizationId:created.organizationId??undefined,actorId:userId,payload:created as any});return created;});return EntityResponseDto.from('Opportunity',row);}
 async update(userId:string,id:string,data:any){const current=await this.prisma.opportunity.findUnique({where:{id},include:{relationship:true}});if(!current||current.deletedAt)throw new NotFoundException('Opportunity not found');await this.resolveOrg(userId,current);const org=await this.resolveOrg(userId,{...current,...data});const payload=this.normalize(data,org);const updated=await this.eventBus.transaction(async tx=>{const next=await tx.opportunity.update({where:{id},data:payload});await this.audit.logMutation({userId,action:'UPDATE',entityType:'Opportunity',entityId:id,organizationId:next.organizationId??undefined,before:current,after:next},tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.OPPORTUNITY_UPDATED,aggregateType:'Opportunity',aggregateId:next.id,organizationId:next.organizationId??undefined,actorId:userId,payload:next as any});if(current.status!==next.status)await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.OPPORTUNITY_STATUS_CHANGED,aggregateType:'Opportunity',aggregateId:next.id,organizationId:next.organizationId??undefined,actorId:userId,payload:{before:current.status,after:next.status}});return next;});return EntityResponseDto.from('Opportunity',updated);}
 async remove(userId:string,id:string){const row=await this.get(userId,id);const updated=await this.eventBus.transaction(async tx=>{const next=await this.lifecycle.softDelete(userId,'Opportunity',id,'remove',tx);await this.eventBus.publishInTransaction(tx,{eventType:DOMAIN_EVENT_TYPES.OPPORTUNITY_DELETED,aggregateType:'Opportunity',aggregateId:id,organizationId:(next as any).organizationId??undefined,actorId:userId,payload:next as any});return next;});return EntityResponseDto.from('Opportunity',updated);}
}
