'use client';
import {useEffect,useState,useCallback} from 'react';import{api}from'../_lib/api';import{Badge,ErrorCard,Loading,PageHeader}from'../_components/page-ui';import{EntityPicker}from'../_components/entity-picker';import{useWorkspace}from'../_components/workspace';
const unwrap=(x:any)=>Array.isArray(x)?x:x?.items??x?.rows??x?.data??[];
const ACTION_TYPES:Array<[string,string]>=[['SENSITIVE_RELATIONSHIP_CREATE','ایجاد رابطه حساس'],['STRATEGIC_SCORE_CHANGE','تغییر امتیاز استراتژیک'],['DATA_SHARING','اشتراک داده'],['DATA_IMPORT','ورود داده'],['EXPORT','خروجی'],['DELETE','حذف داده']];
export default function Page(){const{scopeId}=useWorkspace();const[d,setD]=useState<any[]>([]),[e,setE]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[showCreate,setShowCreate]=useState(false);
 const[form,setForm]=useState({actionType:'STRATEGIC_SCORE_CHANGE',entityType:'Relationship',entityId:'',organizationId:'',reason:''});
 const entityEndpoint=({Relationship:'/relationships',Organization:'/organizations',Person:'/people',Action:'/actions',Commitment:'/commitments',Project:'/projects',Meeting:'/meetings'} as Record<string,string>)[form.entityType];
 const load=useCallback(async()=>{setLoading(true);setE('');try{setD(unwrap(await api('/approvals')))}catch(x){setE((x as Error).message)}finally{setLoading(false)}},[setLoading,setD,setE]);useEffect(()=>{load()},[load]);
 async function decide(id:string,decision:'approve'|'reject'){setBusy(id+decision);setE('');try{await api(`/approvals/${id}/${decision}`,{method:'POST',body:JSON.stringify({})});setStatus(`درخواست ${id} ${decision==='approve'?'تأیید':'رد'} شد.`);await load()}catch(x){setE((x as Error).message)}finally{setBusy('')}}
 async function createRequest(){setBusy('create');setE('');setStatus('');if(!form.entityId.trim()){setE('یک موجودیت مرتبط را انتخاب کنید.');setBusy('');return}try{await api('/approvals',{method:'POST',body:JSON.stringify({...form,organizationId:form.organizationId.trim()||undefined,reason:form.reason.trim()||undefined})});setStatus('درخواست تأیید ثبت شد.');setForm(f=>({...f,entityId:'',reason:''}));setShowCreate(false);await load()}catch(x){setE((x as Error).message)}finally{setBusy('')}}
 const tone=(s?:string)=>{if(s==='APPROVED')return'success';if(s==='REJECTED')return'danger';if(s==='PENDING')return'warning';return'neutral'};
 return <main className="feature-page"><PageHeader eyebrow="APPROVALS" title="تأییدها" description="برای Relationship حساس، تغییر Strategic Score، Export و حذف داده، Approval می‌تواند الزامی باشد." actions={<button className="primary-action" onClick={()=>setShowCreate(s=>!s)}>{showCreate?'بستن':'+ درخواست تأیید'}</button>}/>
 <ErrorCard message={e}/>{status&&<div className="notice" role="status">{status}</div>}
 {showCreate&&<section className="panel"><div className="panel-title"><div><h2>درخواست تأیید جدید</h2></div></div><div className="form-grid"><label>نوع اقدام<select value={form.actionType} onChange={x=>setForm(f=>({...f,actionType:x.target.value}))}>{ACTION_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>نوع موجودیت<select value={form.entityType} onChange={x=>setForm(f=>({...f,entityType:x.target.value,entityId:''}))}>{['Relationship','Organization','Person','Action','Commitment','Project','Meeting'].map(type=><option key={type} value={type}>{type}</option>)}</select></label>{entityEndpoint?<EntityPicker label="موجودیت مرتبط" endpoint={entityEndpoint} value={form.entityId} onChange={entityId=>setForm(f=>({...f,entityId}))} scopeId={scopeId} required/>:<label>موجودیت مرتبط<input value={form.entityId} onChange={x=>setForm(f=>({...f,entityId:x.target.value}))} required placeholder="انتخاب موجودیت"/></label>}<EntityPicker label="سازمان (اختیاری)" endpoint="/organizations" value={form.organizationId} onChange={organizationId=>setForm(f=>({...f,organizationId}))} scopeId={scopeId}/><label className="full">دلیل<textarea value={form.reason} onChange={x=>setForm(f=>({...f,reason:x.target.value}))} placeholder="شرح دلیل"/></label><button className="primary-action" onClick={createRequest} disabled={!!busy}>{busy==='create'?'در حال ثبت…':'ثبت درخواست'}</button></div></section>}
 {loading?<Loading/>:<div className="list">{d.length===0?<div className="panel"><p className="empty-state">درخواست تأیید فعالی وجود ندارد.</p></div>:d.map(x=><article className="panel compact" key={x.id}><div className="panel-title"><div><strong>{x.actionType??'Approval'}</strong><small className="muted">{x.entityType} · ثبت‌شده در {new Date(x.createdAt).toLocaleString()}</small></div><span><Badge tone={tone(x.status)}>{x.status??'PENDING'}</Badge>{x.status==='PENDING'&&<button className="secondary-action" onClick={()=>decide(x.id,'approve')} disabled={!!busy}>تأیید</button>}{x.status==='PENDING'&&<button className="danger-action" onClick={()=>decide(x.id,'reject')} disabled={!!busy}>رد</button>}</span></div>{x.reason&&<p className="muted">{x.reason}</p>}</article>)}</div>}
 </main>}