'use client';
import {use,useCallback,useEffect,useState} from 'react';
import {api} from '../../_lib/api';
import {Badge,ErrorCard,Loading,PageHeader} from '../../_components/page-ui';
import {EntityPicker} from '../../_components/entity-picker';
import {useWorkspace} from '../../_components/workspace';
type Prompt='outcome'|'participant';
type Decision={text:string;ownerId?:string;dueAt?:string};
export default function Page({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);
 const {scopeId}=useWorkspace();
 const [m,setM]=useState<any>(null),[minutes,setMinutes]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[prompt,setPrompt]=useState<Prompt|null>(null);
 const [outForm,setOutForm]=useState({notes:'',outcome:'',transcript:''});
 const [participantId,setParticipantId]=useState('');
 const [decisions,setDecisions]=useState<Decision[]>([]);
 const [candidates,setCandidates]=useState<any[]>([]),[]=useState([]);
 const load=useCallback(async()=>{setError('');try{setM(await api(`/meetings/${id}`))}catch(e){setError((e as Error).message)}},[id]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{
   if(!m?.decisions || !Array.isArray(m.decisions)) return;
   setDecisions(m.decisions.map((decision:any)=>typeof decision==='string'?{text:decision}:{text:decision.text??decision.title??'',ownerId:decision.ownerId,dueAt:decision.dueAt}));
 },[m?.decisions]);
 async function refreshMinutes(){setError('');try{setMinutes(await api(`/meetings/${id}/minutes`))}catch(e){setError((e as Error).message)}}
 async function act(label:string,fn:()=>Promise<any>){setBusy(label);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function submitOutcome(e:React.FormEvent){e.preventDefault();const cleanDecisions=decisions.filter(decision=>decision.text.trim()).map(decision=>({...decision,text:decision.text.trim(),ownerId:decision.ownerId||undefined,dueAt:decision.dueAt||undefined}));await act('outcome',async()=>{await api(`/meetings/${id}/outcome`,{method:'POST',body:JSON.stringify({notes:outForm.notes.trim()||undefined,outcome:outForm.outcome.trim()||undefined,decisions:cleanDecisions,transcript:outForm.transcript.trim()||undefined})});setMinutes(null);await Promise.all([load(),refreshMinutes()])})}
 async function addParticipant(personId:string){await act('participant',async()=>{const ids=[...(m?.participants??[]).map((p:any)=>p.personId),personId].filter(Boolean);await api(`/meetings/${id}/participants`,{method:'PUT',body:JSON.stringify({personIds:ids})});await load()})}
 async function extract(){await act('extract',async()=>{const x:any=await api(`/meetings/${id}/action-items/extract`,{method:'POST',body:'{}'});setCandidates(x.candidates??[])})}
 function updateDecision(index:number, patch:Partial<Decision>){setDecisions(current=>current.map((decision,i)=>i===index?{...decision,...patch}:decision));}
 function addDecision(){setDecisions(current=>[...current,{text:''}]);}
 function removeDecision(index:number){setDecisions(current=>current.filter((_,i)=>i!==index));}
 const [checked,setChecked]=useState<Record<number,boolean>>({});
 async function applySelected(){const items=(candidates??[]).filter((_,i)=>checked[i]).map((c:any,i:number)=>({title:c.suggestedTitle,dueAt:c.suggestedDueAt,asCommitment:c.isCommitmentLike,priority:'MEDIUM',description:c.text}));if(!items.length)return;await act('apply',async()=>{await api(`/meetings/${id}/action-items/apply`,{method:'POST',body:JSON.stringify({items})});setCandidates([]);setChecked({});await refreshMinutes()})}
 const pending=m?.status==='COMPLETED'?false:true;
 const items=m?.actions??[];
 return <main className="feature-page">
  <PageHeader eyebrow="MEETING" title={m?.title??'Meeting'} description={`وضعیت: ${m?.status??'…'}`} actions={<div className="toolbar"><button className="secondary-action" onClick={load} disabled={!!busy}>بازخوانی</button><button className="secondary-action" onClick={refreshMinutes} disabled={!!busy}>خروجی (Minutes)</button>{pending&&<button className="primary-action" onClick={()=>setPrompt('outcome')} disabled={!!busy}>ثبت خروجی</button>}<button className="primary-action" onClick={extract} disabled={!!busy}>استخراج اقدامات</button></div>}/>
  <ErrorCard message={error}/>
  {!m&&!error?<Loading/>:m&&<>
   <section className="panel"><div className="panel-title"><div><h2>اطلاعات جلسه</h2><p>{m.objective??'بدون هدف ثبت‌شده'}</p></div>{m.status===undefined?<Badge>{m.status}</Badge>:<Badge tone="success">{m.status}</Badge>}</div><div className="detail-grid">{Object.entries({title:m.title,objective:m.objective,agenda:m.agenda,location:m.location,meetingUrl:m.meetingUrl,startAt:m.startAt,endAt:m.endAt,status:m.status,completedAt:m.completedAt}).filter(([,v])=>v!=null&&v!=='').map(([k,v])=><div className="detail-item" key={k}><small>{k}</small><strong>{typeof v==='object'?JSON.stringify(v):String(v)}</strong></div>)}</div></section>
   <div className="split-panels">
    <section className="panel"><div className="panel-title"><div><h2>شرکت‌کنندگان</h2><Badge>{(m.participants??[]).length}</Badge></div><button className="secondary-action" onClick={()=>setPrompt('participant')}>افزودن</button></div>{(m.participants??[]).length?<div className="list">{(m.participants??[]).map((p:any,i:number)=><div className="listRow" key={p.personId??i}><span>{p.person?.displayName??([p.person?.firstName,p.person?.lastName].filter(Boolean).join(' ')||'شرکت‌کننده ثبت‌شده')}</span></div>)}</div>:<p className="empty-state">شرکت‌کننده‌ای ثبت نشده است.</p>}</section>
    <section className="panel"><div className="panel-title"><div><h2>اقدامات مرتبط</h2><Badge>{items.length}</Badge></div></div>{items.length?<div className="list">{items.map((a:any,i:number)=><div className="listRow" key={a.id??i}><span><Badge tone={a.status==='DONE'?'success':a.status==='OVERDUE'?'danger':'neutral'}>{a.status??'OPEN'}</Badge></span><strong>{a.title}</strong><span>{a.dueAt?new Date(a.dueAt).toLocaleDateString():'—'}</span></div>)}</div>:<p className="empty-state">اقدام مرتبطی نیست.</p>}</section>
   </div>
   {prompt==='outcome'&&<section className="panel"><div className="panel-title"><h2>ثبت خروجی / تکمیل جلسه</h2><button onClick={()=>setPrompt(null)}>انصراف</button></div><form className="entity-form" onSubmit={submitOutcome}><label>نتیجه کلی جلسه<textarea value={outForm.outcome} onChange={e=>setOutForm({...outForm,outcome:e.target.value})} placeholder="نتیجه کلی جلسه"/></label><label>یادداشت‌های جلسه<textarea value={outForm.notes} onChange={e=>setOutForm({...outForm,notes:e.target.value})} placeholder="یادداشت‌های جلسه"/></label><label>Transcript<textarea value={outForm.transcript} onChange={e=>setOutForm({...outForm,transcript:e.target.value})} placeholder="متن مذاکره (اختیاری)"/></label><div className="meeting-decisions"><div className="panel-title"><div><h3>تصمیم‌ها</h3><p>هر تصمیم را به‌صورت قابل پیگیری ثبت کنید؛ JSON خام لازم نیست.</p></div><button type="button" className="secondary-action" onClick={addDecision}>افزودن تصمیم</button></div>{decisions.length===0?<p className="empty-state">تصمیمی اضافه نشده است.</p>:decisions.map((decision,index)=><div className="meeting-decision" key={index}><input value={decision.text} onChange={e=>updateDecision(index,{text:e.target.value})} placeholder="شرح تصمیم"/><EntityPicker value={decision.ownerId??''} onChange={ownerId=>updateDecision(index,{ownerId})} endpoint="/users/picker" label="مسئول" scopeId={scopeId}/><input type="date" value={decision.dueAt??''} onChange={e=>updateDecision(index,{dueAt:e.target.value})} aria-label="موعد تصمیم"/><button type="button" className="danger-action" onClick={()=>removeDecision(index)}>حذف</button></div>)}</div><button className="primary-action" disabled={!!busy}>{busy==='outcome'?'در حال ذخیره…':'تکمیل و ثبت خروجی'}</button></form></section>}
   {prompt==='participant'&&<section className="panel"><div className="panel-title"><h2>افزودن شرکت‌کننده</h2><button onClick={()=>setPrompt(null)}>انصراف</button></div><form className="entity-form" onSubmit={async e=>{e.preventDefault();if(!participantId)return;await addParticipant(participantId);setParticipantId('');setPrompt(null)}}><EntityPicker value={participantId} onChange={setParticipantId} endpoint="/people" label="شرکت‌کننده" scopeId={scopeId} required/><button className="primary-action" disabled={!!busy||!participantId}>افزودن</button></form></section>}
   {candidates.length>0&&<section className="panel"><div className="panel-title"><div><h2>اقدامات پیشنهادی ({candidates.length})</h2><p>استخراج قطعی از notes/transcript/outcome — فقط با تأیید شما ثبت می‌شوند.</p></div><button className="primary-action" onClick={applySelected} disabled={!!busy||!Object.values(checked).some(Boolean)}>ثبت انتخاب‌شده‌ها</button></div><div className="list">{candidates.map((c:any,i:number)=><label className="listRow" key={i}><input type="checkbox" checked={!!checked[i]} onChange={e=>setChecked({...checked,[i]:e.target.checked})}/><span><strong>{c.suggestedTitle}</strong><small>{c.text} · سررسید پیشنهادی {new Date(c.suggestedDueAt).toLocaleDateString()} · {c.isCommitmentLike?'تعهد':'اقدام'} · کلیدواژه: {c.matchedKeyword}</small></span></label>)}</div></section>}
   {minutes&&<section className="panel"><div className="panel-title"><div><h2>Minutes{minutes.isFinalized?' (نهایی)':''}</h2></div><button className="secondary-action" onClick={async()=>{await act('finalize',async()=>{await api(`/meetings/${id}/finalize`,{method:'POST',body:'{}'});await refreshMinutes()})}} disabled={!!busy}>Finalize</button></div><div className="detail-grid">{Object.entries({title:minutes.title,objective:minutes.objective,startAt:minutes.startAt,endAt:minutes.endAt,location:minutes.location,notes:minutes.notes,outcome:minutes.outcome,decisions:minutes.decisions?.length?JSON.stringify(minutes.decisions):null,generatedAt:minutes.generatedAt}).filter(([,v])=>v!=null&&v!=='').map(([k,v])=><div className="detail-item" key={k}><small>{k}</small><strong>{String(v)}</strong></div>)}</div><div className="stat-row">{[['اقدام باز',minutes.actionItems?.open?.length??0],['اقدام بازِ عقب‌افتاده',minutes.actionItems?.overdueOpen?.length??0],['اقدام تکمیل‌شده',minutes.actionItems?.completed?.length??0],['تعهد باز',minutes.commitments?.open?.length??0],['تعهد بازِ عقب‌افتاده',minutes.commitments?.overdue?.length??0],['تعهد انجام‌شده',minutes.commitments?.fulfilled?.length??0]].map(([k,v])=><div className="stat-box" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div></section>}
  </>}
 </main>;
}