'use client';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { api, ApiError } from '../_lib/api';
import { Badge, DataTable, Empty, ErrorCard, Loading, PageHeader } from './page-ui';
import { EntityPicker } from './entity-picker';
import { useWorkspace } from './workspace';

type Field={name:string;label:string;type?:'text'|'number'|'date'|'datetime-local'|'textarea'|'select';required?:boolean;options?:string[];entityEndpoint?:string};
export type EntityConfig={title:string;eyebrow:string;description:string;endpoint:string;permission?:string;fields:Field[];columns?:string[];columnLabels?:Record<string,string>;createLabel?:string;extra?:()=>React.ReactNode;delete?:boolean};

function unwrap(value:any):any[]{if(Array.isArray(value))return value;if(Array.isArray(value?.items))return value.items;if(Array.isArray(value?.rows))return value.rows;if(Array.isArray(value?.data))return value.data;return value?[value]:[]}
function pretty(v:any,key?:string){if(v===null||v===undefined||v==='')return '—'; if(typeof v==='object'){if(Array.isArray(v))return v.length?`${v.length} مورد`:'—';return v.name??v.displayName??v.title??v.label??'جزئیات موجود';} if(key?.endsWith('Id'))return 'موجودیت انتخاب‌شده'; return String(v)}
function writePermission(permission?:string){return permission?.endsWith('.read')?`${permission.slice(0,-5)}.write`:permission}
function errorText(value:unknown){if(value instanceof ApiError&&value.requestId)return `${value.message} (کد پیگیری: ${value.requestId.slice(0,8)})`;return value instanceof Error?value.message:'عملیات انجام نشد.'}
function emptyForm(fields:Field[]){return Object.fromEntries(fields.map(field=>[field.name,'']))}

export function EntityWorkspace({config}:{config:EntityConfig}){
 const {scopeId,can}=useWorkspace();
 const readable=!config.permission||can(config.permission);
 const writable=readable&&(!config.permission||can(writePermission(config.permission) ?? ''));
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<any|null>(null);
 const [form,setForm]=useState<Record<string,string>>(()=>emptyForm(config.fields));
 const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams({page:'1',pageSize:'100'});if(scopeId!=='all')params.set('organizationId',scopeId);setRows(unwrap(await api(`${config.endpoint}?${params.toString()}`)));}catch(e){setError(errorText(e))}finally{setLoading(false)}},[config.endpoint,scopeId]);
 useEffect(()=>{void load()},[load]);
 const columns=useMemo(()=>config.columns??(rows[0]?Object.keys(rows[0]).filter(k=>!k.startsWith('_')&&!k.endsWith('Id')).slice(0,7):[]),[rows,config.columns]);
 function reset(){setEditing(null);setForm(emptyForm(config.fields));}
 function beginEdit(row:any){if(!writable)return;setEditing(row);setNotice('');setForm(Object.fromEntries(config.fields.map(field=>[field.name,row[field.name]===undefined?'':String(row[field.name])])))}
 async function submit(e:FormEvent){e.preventDefault();if(!writable)return;setSaving(true);setError('');setNotice('');try{const payload:any={};for(const field of config.fields){const value=form[field.name]?.trim?.()??form[field.name];if(field.required&&!value)throw new Error(`فیلد «${field.label}» الزامی است.`);if(value!==undefined&&value!==''){if(field.type==='number'){const number=Number(value);if(!Number.isFinite(number))throw new Error(`مقدار «${field.label}» معتبر نیست.`);payload[field.name]=number}else if(field.type==='datetime-local'){const date=new Date(value);if(Number.isNaN(date.getTime()))throw new Error(`زمان «${field.label}» معتبر نیست.`);payload[field.name]=date.toISOString()}else payload[field.name]=value}}const path=editing?`${config.endpoint}/${encodeURIComponent(editing.id)}`:config.endpoint;await api(path,{method:editing?'PATCH':'POST',body:JSON.stringify(payload)});setNotice(editing?'تغییرات ذخیره شد.':'رکورد ثبت شد.');reset();await load()}catch(e){setError(errorText(e))}finally{setSaving(false)}}
 async function remove(row:any){if(!writable||!config.delete||!row.id||!window.confirm('این مورد حذف یا بایگانی شود؟'))return;setSaving(true);setError('');setNotice('');try{await api(`${config.endpoint}/${encodeURIComponent(row.id)}`,{method:'DELETE'});setNotice('رکورد حذف یا بایگانی شد.');if(editing?.id===row.id)reset();await load()}catch(e){setError(errorText(e))}finally{setSaving(false)}}
 if(!readable)return <main className="feature-page"><PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description}/><section className="panel"><Empty>مجوز مشاهده این بخش برای شما فعال نیست.</Empty></section></main>;
 return <main className="feature-page"><PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description}/>{notice&&<div className="notice" role="status">{notice}</div>}<ErrorCard message={error}/><div className="entity-layout">
  {writable&&<section className="panel"><div className="panel-title"><div><h2>{editing?'ویرایش':'ثبت جدید'}</h2><p>انتخاب موجودیت با نام انجام می‌شود؛ Scope و مجوز در Backend enforce می‌شود.</p></div>{editing&&<button type="button" className="secondary-action" onClick={reset}>انصراف</button>}</div><form className="entity-form" onSubmit={submit}>{config.fields.map(field=>field.entityEndpoint?<EntityPicker key={field.name} label={field.label} value={form[field.name]??''} onChange={value=>setForm({...form,[field.name]:value})} endpoint={field.entityEndpoint} required={field.required} disabled={saving} scopeId={scopeId}/>:field.type==='textarea'?<label key={field.name}>{field.label}<textarea value={form[field.name]??''} onChange={e=>setForm({...form,[field.name]:e.target.value})} required={field.required}/></label>:field.type==='select'?<label key={field.name}>{field.label}<select value={form[field.name]??''} onChange={e=>setForm({...form,[field.name]:e.target.value})} required={field.required}><option value="">انتخاب کنید</option>{field.options?.map(option=><option key={option} value={option}>{option}</option>)}</select></label>:<label key={field.name}>{field.label}<input type={field.type??'text'} value={form[field.name]??''} onChange={e=>setForm({...form,[field.name]:e.target.value})} required={field.required}/></label>)}<button className="primary-action" disabled={saving}>{saving?'در حال ذخیره…':editing?'ذخیره تغییرات':config.createLabel??'ثبت'}</button></form></section>}
  <section className="panel"><div className="panel-title"><div><h2>داده‌های فعلی</h2><p>{rows.length} مورد در محدوده فعلی</p></div><button className="secondary-action" onClick={()=>void load()} disabled={loading}>بازخوانی</button></div>{loading?<Loading/>:rows.length===0?<Empty>موردی پیدا نشد.</Empty>:<><DataTable columns={columns.map(key=>({key,label:config.columnLabels?.[key]??key}))} rows={rows.map(row=>Object.fromEntries(columns.map(key=>[key,pretty(row[key],key)])))} /><div className="crud-actions">{rows.map(row=><div className="crud-row-actions" key={String(row.id)}><span>{pretty(row[columns[0]],columns[0])}</span><div>{writable&&<button onClick={()=>beginEdit(row)}>ویرایش</button>}{writable&&config.delete&&<button className="danger-action" onClick={()=>void remove(row)} disabled={saving}>حذف</button>}</div></div>)}</div></>}</section>
 </div></main>
}
