'use client';
import {useCallback,useEffect,useState} from 'react';import {api,ApiError} from '../_lib/api';import {Badge,DataTable,Empty,ErrorCard,Loading,PageHeader} from './page-ui';
const arr=(x:any)=>Array.isArray(x)?x:Array.isArray(x?.items)?x.items:Array.isArray(x?.data)?x.data:Array.isArray(x?.rows)?x.rows:[];
const value=(x:any)=>x==null?'—':typeof x==='object'?(x.name??x.title??x.label??x.id??JSON.stringify(x)):String(x);
export function EntityDetail({title,eyebrow,endpoint,id,actions=[],timelineEndpoint}:{title:string;eyebrow:string;endpoint:string;id:string;actions?:{label:string;method:'POST'|'PATCH'|'DELETE';path:string;body?:unknown;confirm?:string}[];timelineEndpoint?:string}){
 const[d,setD]=useState<any>(null),[timeline,setTimeline]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{setError('');setD(await api(`${endpoint}/${encodeURIComponent(id)}`));if(timelineEndpoint)setTimeline(arr(await api(`${timelineEndpoint.replace(':id',encodeURIComponent(id))}`)))}catch(e){setError(e instanceof ApiError?e.message:(e as Error).message)}},[endpoint,id,timelineEndpoint]);useEffect(()=>{load()},[load]);
 async function act(a:any){if(a.confirm&&!confirm(a.confirm))return;setBusy(true);try{await api(a.path.replace(':id',encodeURIComponent(id)),{method:a.method,body:a.method==='DELETE'?undefined:JSON.stringify(a.body??{})});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const fields=d?Object.entries(d).filter(([k])=>!k.startsWith('_')&&k!=='timeline'&&typeof d[k]!=='function').slice(0,30):[];
 return <main className="feature-page"><PageHeader eyebrow={eyebrow} title={title} description="جزئیات رکورد و عملیات مجاز در این محدوده." actions={<div className="toolbar"><button onClick={load}>بازخوانی</button>{actions.map(a=><button key={a.label} disabled={busy} className={a.method==='DELETE'?'danger-action':'primary-action'} onClick={()=>act(a)}>{a.label}</button>)}</div>}/><ErrorCard message={error}/>{!d&&!error?<Loading/>:d?<><section className="panel"><div className="detail-grid">{fields.map(([k,v])=><div className="detail-item" key={k}><small>{k}</small><strong>{value(v)}</strong></div>)}</div></section>{timelineEndpoint&&<section className="panel"><div className="panel-title"><h2>Timeline</h2><Badge>{timeline.length}</Badge></div>{timeline.length?<DataTable columns={Object.keys(timeline[0]).slice(0,7).map(k=>({key:k,label:k}))} rows={timeline}/>:<Empty/>}</section>}</>:null}</main>
}
