'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';import{api}from'../_lib/api';import{DataTable,ErrorCard,PageHeader}from'../_components/page-ui';
export default function DataManagement(){const[q,setQ]=useState<any>(null),[e,setE]=useState('');useEffect(()=>{api<any>('/data/quality').then(setQ).catch(x=>setE(x.message))},[]);const m=q?.metrics??q??{};const dups=Array.isArray(m.duplicateOrganizations)?m.duplicateOrganizations.length:m.duplicateOrganizations?.length??0;const num=(v:any)=>typeof v==='number'?v:typeof v==='object'&&v&&typeof v.total==='number'?v.total:0;const cards:[string,string,number][]=[['duplicates','نامزدهای تکراری',dups],['missingOwners','بدون مالک',num(m.missingOwners)],['staleRelationships','رابطه‌های کهنه',num(m.staleRelationships)],['invalidEmails','ایمیل‌های نامعتبر',num(m.invalidEmails)],['incomplete','پروفایل‌های ناقص',num(m.incompleteProfiles?.organizations)+num(m.incompleteProfiles?.people)]];const issues=[...(Array.isArray(m.missingOwners?.values)?m.missingOwners.values.map((id:any)=>({kind:'بدون مالک',id})):[]),...(Array.isArray(m.staleRelationships?.values)?m.staleRelationships.values.map((r:any)=>({kind:'رابطهٔ کهنه',id:r.id})):[]),...(Array.isArray(m.invalidEmails?.values)?m.invalidEmails.values.map((v:any)=>({kind:'ایمیل نامعتبر',entity:v.entityType,id:v.id})):[])];return <main className="admin-layout"><PageHeader eyebrow="حاکمیت داده" title="مدیریت داده" description="کیفیت داده، ورود داده، شناسایی موارد تکراری و چرخهٔ حیات تحت یک فضای کاری." actions={<Link className="primary-action" href="/data-management/import">+ ورود داده</Link>}/><ErrorCard message={e}/>{!q?null:<>
<section className="stat-row">{cards.map(([k,l,v])=><div className="stat-box" key={k}><span>{l}</span><strong>{v}</strong></div>)}</section>
<section className="split-panels">
<article className="panel executive-card"><h2>مشکلات</h2>{issues.length===0?<p className="muted">هیچ مورد کیفیتی یافت نشد.</p>:<DataTable columns={['kind','id','entity'].map(k=>({key:k,label:k}))} rows={issues}/>}</article>
<article className="panel executive-card"><h2>حاکمیت</h2><p className="muted">Classification، Retention، Export Controls و Privacy از Backend enforce می‌شوند.</p><Link className="secondary-action" href="/privacy">حریم خصوصی</Link></article>
</section>
<section className="panel"><h2>پوشش</h2><div className="metric-list">{(Object.entries(m.coverage??{})).map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v)}</strong></div>)}</div></section>
</>}</main>}