'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api } from '../_lib/api';

type Org = { id:string; name:string; type:string; industry?:string; country?:string; owner?:{name:string}; _count:{people:number;sourceRelationships:number;targetRelationships:number;projects:number;opportunities:number} };
export default function Page(){
 const [items,setItems]=useState<Org[]>([]); const [name,setName]=useState(''); const [type,setType]=useState('OTHER'); const [parent,setParent]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{setItems(await api<Org[]>('/organizations'))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();setError('');try{await api('/organizations',{method:'POST',body:JSON.stringify({name,type,parentOrganizationId:parent||undefined})});setName('');setParent('');await load()}catch(e){setError((e as Error).message)}}
 return <main className="shell"><header className="topbar"><strong>SRIP</strong><nav><a href="/">Dashboard</a><a href="/people">People</a><a href="/relationships">Relationships</a></nav></header><section className="hero"><p className="eyebrow">Phase 7 · Core Domain</p><h1>Organizations</h1><p>Organization hierarchy, ownership, people and relationship context.</p></section><section className="grid2"><form className="card" onSubmit={create}><h2>افزودن سازمان</h2><label>نام<input value={name} onChange={e=>setName(e.target.value)} minLength={2} required/></label><label>نوع<select value={type} onChange={e=>setType(e.target.value)}><option>HOLDING</option><option>SUBSIDIARY</option><option>CUSTOMER</option><option>PARTNER</option><option>BANK</option><option>GOVERNMENT</option><option>INVESTOR</option><option>SUPPLIER</option><option>OTHER</option></select></label><label>Parent Organization ID (اختیاری)<input value={parent} onChange={e=>setParent(e.target.value)}/></label><button type="submit">ایجاد سازمان</button>{error&&<p className="error">{error}</p>}</form><section className="card"><h2>Directory</h2>{loading?<p>در حال بارگذاری…</p>:items.length===0?<p>سازمانی ثبت نشده است.</p>:<div className="list">{items.map(o=><article className="listRow" key={o.id}><div><strong><a href={`/organizations/${o.id}`}>{o.name}</a></strong><small>{o.type}{o.industry?` · ${o.industry}`:''}</small></div><span>{o._count.people} people · {o._count.sourceRelationships+o._count.targetRelationships} relationships</span></article>)}</div>}</section></section></main>}
