'use client';import{FormEvent,useEffect,useState}from'react';import{api,unwrapList}from'../_lib/api';import{Badge,DataTable,ErrorCard,Loading,PageHeader}from'../_components/page-ui';
const unwrapOf=(x:any)=>unwrapList(x);
export default function Privacy(){const[policies,setPolicies]=useState<any[]>([]),[consents,setConsents]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[loading,setLoading]=useState(true),[e,setE]=useState(''),[busy,setBusy]=useState(false),[type,setType]=useState('ACCESS'),[reason,setReason]=useState('');
 async function load(){setLoading(true);setE('');try{const [p,c,r]=await Promise.all([api('/privacy/policies').then(unwrapOf),api('/privacy/consents').then(unwrapOf),api('/privacy/requests').then(unwrapOf)]);setPolicies(p);setConsents(c);setRequests(r)}catch(x){setE((x as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function createRequest(x:FormEvent){x.preventDefault();setBusy(true);setE('');try{await api('/privacy/requests',{method:'POST',body:JSON.stringify({type,reason})});setReason('');await load()}catch(err){setE((err as Error).message)}finally{setBusy(false)}}
 const granted=consents.filter(c=>c.status==='GRANTED').length;const open=requests.filter(r=>['PENDING','PROCESSING'].includes(r.status)).length;
 return <main className="admin-layout"><PageHeader eyebrow="PRIVACY / GDPR" title="Privacy & Data Lifecycle" description="Data Minimization، Purpose Limitation، Retention، Access و Deletion تحت Policyهای Backend و با Authorization، Scope و Audit."/>
 <ErrorCard message={e}/>{loading?<Loading/>:<>
 <section className="stat-row"><div className="stat-box"><span>Processing Policies</span><strong>{policies.length}</strong></div><div className="stat-box"><span>Active Consents</span><strong>{granted}</strong></div><div className="stat-box"><span>Open Requests</span><strong>{open}</strong></div><div className="stat-box"><span>All Requests</span><strong>{requests.length}</strong></div></section>
 <section className="split-panels">
  <article className="panel executive-card"><h2>Processing Policies</h2>{policies.length===0?<p className="muted">هیچ Policy فعالی ثبت نشده است.</p>:<DataTable columns={['entityType','purpose','legalBasis','classification','retentionDays','erasable'].map(k=>({key:k,label:k}))} rows={policies.map(p=>({entityType:p.entityType,purpose:p.purpose,legalBasis:p.legalBasis,classification:p.classification,retentionDays:p.retentionDays??'—',erasable:p.erasable?'بله':'خیر'}))}/>}</article>
  <article className="panel executive-card"><h2>درخواست حق داده</h2><form className="entity-form" onSubmit={createRequest}><label>نوع درخواست<select value={type} onChange={x=>setType(x.target.value)}><option>ACCESS</option><option>EXPORT</option><option>ERASURE</option></select></label><label>دلیل<textarea value={reason} onChange={x=>setReason(x.target.value)} placeholder="شرح دلیل درخواست"/></label><button className="primary-action" disabled={busy}>{busy?'در حال ثبت…':'ثبت درخواست'}</button></form></article>
 </section>
 <section className="panel"><h2>Privacy Requests</h2>{requests.length===0?<p className="muted">درخواستی ثبت نشده است.</p>:<div className="list">{requests.map(r=><article className="listRow" key={r.id}><div><strong>{r.type}</strong><small>{(r.reason??'').slice(0,80)}</small></div><Badge tone={r.status==='COMPLETED'?'success':r.status==='REJECTED'?'danger':'info'}>{r.status}</Badge><span>{new Date(r.createdAt).toLocaleString()}</span></article>)}</div>}</section>
 <section className="panel"><h2>حساب امن</h2><p className="muted">Session/Device management و Global Logout.</p><a className="secondary-action" href="/sessions">Sessions & Devices</a></section>
 </>}</main>}