'use client';import{FormEvent,useEffect,useState,useCallback}from'react';import{api,unwrapList}from'../_lib/api';import{Badge,DataTable,Empty,ErrorCard,Loading,PageHeader}from'../_components/page-ui';import{useWorkspace}from'../_components/workspace';
const unwrapOf=(x:any)=>unwrapList(x);
export default function Privacy(){const{can}=useWorkspace();const canRead=can('privacy.read'),canAccess=can('privacy.access'),canExport=can('privacy.export'),canErase=can('privacy.erase');const[policies,setPolicies]=useState<any[]>([]),[consents,setConsents]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[loading,setLoading]=useState(true),[e,setE]=useState(''),[busy,setBusy]=useState(''),[statusMsg,setStatusMsg]=useState('');
 const[type,setType]=useState('ACCESS'),[reason,setReason]=useState('');
 const[purpose,setPurpose]=useState(''),[version,setVersion]=useState('v1'),[grantSource,setGrantSource]=useState('USER');
 const load=useCallback(async()=>{if(!canRead){setPolicies([]);setConsents([]);setRequests([]);setLoading(false);return}setLoading(true);setE('');try{const[p,c,r]=await Promise.all([api('/privacy/policies').then(unwrapOf),api('/privacy/consents').then(unwrapOf),api('/privacy/requests').then(unwrapOf)]);setPolicies(p);setConsents(c);setRequests(r);}catch(x){setE((x as Error).message)}finally{setLoading(false)}},[canRead]);
 useEffect(()=>{void load()},[load]);
 async function createRequest(x:FormEvent){x.preventDefault();if(!canAccess)return;setBusy('create');setE('');setStatusMsg('');try{await api('/privacy/requests',{method:'POST',body:JSON.stringify({type,reason})});setReason('');await load()}catch(err){setE((err as Error).message)}finally{setBusy('')}}
 async function grant(x:FormEvent){x.preventDefault();if(!canAccess)return;setBusy('grant');setE('');setStatusMsg('');try{if(!purpose||!version)throw new Error('هدف و نسخه رضایت الزامی است.');await api('/privacy/consents',{method:'POST',body:JSON.stringify({purpose,version,source:grantSource})});await load();setStatusMsg('رضایت ثبت شد.')}catch(err){setE((err as Error).message)}finally{setBusy('')}}
 async function revoke(c:any){if(!canAccess)return;if(!window.confirm(`ابطال رضایت «${c.purpose}» نسخه ${c.version}؟`))return;setBusy('revoke'+c.id);setE('');setStatusMsg('');try{await api('/privacy/consents/revoke',{method:'POST',body:JSON.stringify({purpose:c.purpose,version:c.version})});await load()}catch(err){setE((err as Error).message)}finally{setBusy('')}}
 async function requestAction(r:any,verb:string){if((verb==='erase'&&!canErase)||(verb==='export'&&!canExport)||(verb==='access'&&!canAccess))return;if(verb==='erase'&&!window.confirm('حساب و داده‌های شخصی شما ناشناس‌سازی و غیرفعال می‌شود. تأیید می‌کنید؟'))return;setBusy(verb+r.id);setE('');setStatusMsg('');try{const res:any=await api(`/privacy/requests/${r.id}/${verb}`,{method:'POST',body:JSON.stringify({})});setStatusMsg(res?.status==='PROCESSING'?`در حال پردازش (job ${res?.jobId??''})…`:res?.status||'عملیات انجام شد.');await load()}catch(err){setE((err as Error).message)}finally{setBusy('')}}
 async function showExport(r:any){if(!canExport)return;setBusy('status'+r.id);setE('');setStatusMsg('');try{const st:any=await api(`/privacy/requests/${r.id}/export/status`);setStatusMsg(st?.manifestUrl?`خروجی آماده است: ${st.manifestUrl}`:`وضعیت: ${st?.status??'—'}${st?.totalRecords!=null?` (${st.totalRecords} رکورد)`:''}`)}catch(err){setE((err as Error).message)}finally{setBusy('')}}
 const granted=consents.filter(c=>c.status==='GRANTED').length;const open=requests.filter(r=>['PENDING','PROCESSING'].includes(r.status)).length;
 const purposes=Array.from(new Set(policies.map(p=>p.purpose))).filter(Boolean);
 const statusTone=(s:string)=>{if(s==='COMPLETED'||s==='GRANTED')return'success';if(s==='REJECTED'||s==='ERASED')return'danger';if(s==='PROCESSING')return'warning';return'info'};
 if(!canRead)return <main className="feature-page"><PageHeader eyebrow="PRIVACY / GDPR" title="Privacy & Data Lifecycle" description="مدیریت حریم خصوصی و چرخه عمر داده."/><section className="panel"><Empty>مجوز مشاهده حریم خصوصی برای شما فعال نیست.</Empty></section></main>;
 return <main className="admin-layout"><PageHeader eyebrow="PRIVACY / GDPR" title="Privacy & Data Lifecycle" description="Data Minimization، Purpose Limitation، Retention، Access و Deletion تحت Policyهای Backend و با Authorization، Scope و Audit."/>
 <ErrorCard message={e}/>{statusMsg&&<div className="notice" role="status">{statusMsg}</div>}{loading?<Loading/>:<>
 <section className="stat-row"><div className="stat-box"><span>Processing Policies</span><strong>{policies.length}</strong></div><div className="stat-box"><span>Active Consents</span><strong>{granted}</strong></div><div className="stat-box"><span>Open Requests</span><strong>{open}</strong></div><div className="stat-box"><span>All Requests</span><strong>{requests.length}</strong></div></section>
 <section className="split-panels">
  <article className="panel executive-card"><h2>Processing Policies</h2>{policies.length===0?<Empty>هیچ Policy فعالی ثبت نشده است.</Empty>:<DataTable columns={['entityType','purpose','legalBasis','classification','retentionDays','erasable'].map(k=>({key:k,label:k}))} rows={policies.map(p=>({entityType:p.entityType,purpose:p.purpose,legalBasis:p.legalBasis,classification:p.classification,retentionDays:p.retentionDays??'—',erasable:p.erasable?'بله':'خیر'}))}/>}</article>
  {canAccess&&<article className="panel executive-card"><h2>درخواست حق داده</h2><form className="entity-form" onSubmit={createRequest}><label>نوع درخواست<select value={type} onChange={x=>setType(x.target.value)}><option>ACCESS</option><option>EXPORT</option><option>ERASURE</option></select></label><label>دلیل<textarea value={reason} onChange={x=>setReason(x.target.value)} placeholder="شرح دلیل درخواست"/></label><button className="primary-action" disabled={!!busy}>{busy==='create'?'در حال ثبت…':'ثبت درخواست'}</button></form></article>}
 </section>
 <section className="split-panels">
  <article className="panel executive-card"><h2>رضایت‌ها (Consents)</h2>{consents.length===0?<Empty>رضایتی ثبت نشده است.</Empty>:<div className="list">{consents.map(c=><article className="listRow" key={c.id}><div><strong>{c.purpose}</strong><small>نسخه {c.version} · منبع {c.source??'—'} · {(c.grantedAt??c.createdAt??'').slice(0,10)||'—'}</small></div><span><Badge tone={statusTone(c.status)}>{c.status}</Badge>{canAccess&&c.status==='GRANTED'&&<button className="danger-action" onClick={()=>revoke(c)} disabled={!!busy}>Revoke</button>}</span></article>)}</div>}</article>
  {canAccess&&<article className="panel executive-card"><h2>ثبت رضایت جدید</h2><form className="entity-form" onSubmit={grant}><label>هدف (Purpose)<select value={purpose} onChange={x=>setPurpose(x.target.value)} required><option value="">انتخاب کنید</option>{purposes.map(p=><option key={p} value={p}>{p}</option>)}</select></label><label>نسخه<input value={version} onChange={x=>setVersion(x.target.value)} required placeholder="مثلاً v1"/></label><button className="primary-action" disabled={!!busy}>{busy==='grant'?'در حال ثبت…':'ثبت رضایت'}</button></form></article>}
 </section>
 <section className="panel"><h2>Privacy Requests</h2>{requests.length===0?<Empty>درخواستی ثبت نشده است.</Empty>:<div className="list">{requests.map(r=><article className="listRow" key={r.id}><div><strong>{r.type}</strong><small>{(r.reason??'').slice(0,80)}</small></div><span><Badge tone={statusTone(r.status)}>{r.status}</Badge>{r.type==='ACCESS'&&r.status==='PENDING'&&canAccess&&<button className="secondary-action" onClick={()=>requestAction(r,'access')} disabled={!!busy}>اجرا</button>}{r.type==='EXPORT'&&r.status==='PENDING'&&canExport&&<button className="secondary-action" onClick={()=>requestAction(r,'export')} disabled={!!busy}>اجرا</button>}{(r.type==='ACCESS'||r.type==='EXPORT')&&r.status==='COMPLETED'&&canExport&&<button className="secondary-action" onClick={()=>showExport(r)} disabled={!!busy}>مشاهده نتیجه</button>}{r.type==='ERASURE'&&canErase&&<button className="danger-action" onClick={()=>requestAction(r,'erase')} disabled={!!busy}>Erase</button>}</span><small className="muted">{new Date(r.createdAt).toLocaleDateString()}</small></article>)}</div>}</section>
 </>}</main>}