-- Correct schema-vs-DB enum drift: these AuditAction values exist in
-- schema.prisma but were never added to the database enum.
-- Add them non-destructively.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPROVAL_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPROVAL_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPROVAL_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOM_FIELD_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOM_FIELD_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOM_FIELD_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOM_FIELD_VALUE_SET';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOM_FIELD_VALUE_REMOVED';
