import { AuthorizationAdminModule } from './authorization/authorization-admin.module'; import { PrivacyModule } from './privacy/privacy.module'; import { IntegrationsModule } from './integrations/integrations.module'; import { MfaModule } from './common/mfa/mfa.module'; import { EnterpriseModule } from './enterprise/enterprise.module'; import { RequirementsModule } from './requirements/requirements.module'; import { JobsModule } from './jobs/jobs.module'; import { IntelligenceModule } from './intelligence/intelligence.module'; import { UsersModule } from './users/users.module'; import { OpportunitiesModule } from './opportunities/opportunities.module'; import { NotificationsModule } from './notifications/notifications.module'; import { DocumentsModule } from './documents/documents.module'; import { AnalyticsModule } from './analytics/analytics.module'; import { AiModule } from './ai/ai.module'; import { RecommendationsModule } from './recommendations/recommendations.module'; import { SecurityModule } from './security/security.module'; import { ReportingModule } from './reporting/reporting.module'; import { EventBusModule } from './event-bus/event-bus.module'; import { ScoringModule } from './scoring/scoring.module'; import { ObservabilityModule } from './observability/observability.module'; import { ObservabilityMiddleware } from './observability/observability.middleware';
import { Module, MiddlewareConsumer, RequestMethod } from '@nestjs/common';
import { RequestContextModule } from './common/request-context.module';
import { APP_FILTER, APP_INTERCEPTOR } from '@nestjs/core'; import { DataManagementModule } from './data-management/data-management.module'; import { AdminModule } from './admin/admin.module';
import { ProductionHardeningMiddleware, OriginVerificationMiddleware } from './production-hardening';
import { ApiContractModule } from './common/api-contract/api-contract.module';
import { ApiContractInterceptor } from './common/api-contract/api-contract.interceptor';
import { ApiContractExceptionFilter } from './common/api-contract/api-contract.filter';
import { ApiContractContextMiddleware } from './common/api-contract/api-contract.middleware'; import { MetricsController } from './metrics.controller'; import { ConfigModule } from '@nestjs/config'; import { PrismaService } from './prisma/prisma.service'; import { HealthService } from './health/health.service'; import { S3Storage } from './documents/s3.storage'; import { HealthController } from './health/health.controller'; import { AuthModule } from './auth/auth.module'; import { OrganizationsModule } from './organizations/organizations.module'; import { CoreDomainModule } from './organizations/core-domain.module'; import { RelationshipsModule } from './relationships/relationships.module'; import { PeopleModule } from './people/people.module'; import { InteractionsModule } from './interactions/interactions.module'; import { MeetingsModule } from './meetings/meetings.module'; import { ActionsModule } from './actions/actions.module'; import { CommitmentsModule } from './commitments/commitments.module'; import { ProjectsModule } from './projects/projects.module'; import { AuditModule } from './audit/audit.module'; import { SessionsModule } from './sessions/sessions.module'; import { PermissionsModule } from './permissions/permissions.module'; import { SearchModule } from './search/search.module'; import { NetworkModule } from './network/network.module'; import { WorkflowsModule } from './workflows/workflows.module'; import { TagsModule } from './tags/tags.module'; import { CustomFieldsModule } from './custom-fields/custom-fields.module'; import { DataLifecycleModule } from './common/data-lifecycle/data-lifecycle.module'; import { FeatureFlagModule } from './common/feature-flags/feature-flag.module'; import { ApprovalModule } from './approvals/approval.module'; import { RateLimitModule } from './common/rate-limit/rate-limit.module'; import { InternalMetricsGuard } from './common/guards/internal-metrics.guard'; import { PerformanceModule } from './common/performance/performance.module';
@Module({imports:[ConfigModule.forRoot({isGlobal:true}), RequestContextModule, ObservabilityModule, PerformanceModule, ApiContractModule,AuthModule,OrganizationsModule, CoreDomainModule,RelationshipsModule,PeopleModule,InteractionsModule,MeetingsModule,ActionsModule,CommitmentsModule,ProjectsModule,AuditModule,SessionsModule,PermissionsModule,SearchModule,NetworkModule,WorkflowsModule,TagsModule,CustomFieldsModule,DataLifecycleModule,FeatureFlagModule,RateLimitModule,ApprovalModule,IntelligenceModule,UsersModule,OpportunitiesModule,NotificationsModule,DocumentsModule,AnalyticsModule,AiModule,RecommendationsModule,SecurityModule,IntegrationsModule,EnterpriseModule,RequirementsModule,JobsModule,MfaModule,AuthorizationAdminModule,PrivacyModule,ReportingModule,EventBusModule,ScoringModule,DataManagementModule,AdminModule],controllers:[HealthController,MetricsController],providers:[PrismaService,S3Storage,HealthService,InternalMetricsGuard,{provide:APP_INTERCEPTOR,useClass:ApiContractInterceptor},{provide:APP_FILTER,useClass:ApiContractExceptionFilter}],}) export class AppModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(ApiContractContextMiddleware, ObservabilityMiddleware, ProductionHardeningMiddleware, OriginVerificationMiddleware).forRoutes({ path: '*', method: RequestMethod.ALL });
  }
}
