#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
test -f "$root/docs/PHASE_14_SEARCH_NOTIFICATIONS_ANALYTICS.md"
test -f "$root/apps/api/src/search/search.service.ts"
test -f "$root/apps/api/src/notifications/notifications.service.ts"
test -f "$root/apps/api/src/notifications/notification-provider.port.ts"
test -f "$root/apps/api/src/analytics/analytics.service.ts"
test -f "$root/apps/api/src/workflows/workflows.service.ts"
test -f "$root/apps/web/app/search/page.tsx"
test -f "$root/apps/web/app/notifications/page.tsx"
test -f "$root/apps/web/app/analytics/page.tsx"
test -f "$root/apps/web/app/workflows/page.tsx"
test -f "$root/apps/mobile/src/app/search.tsx"
test -f "$root/apps/mobile/src/app/notifications.tsx"
grep -q "model SavedSearch" "$root/apps/api/prisma/schema.prisma"
grep -q "model NotificationPreference" "$root/apps/api/prisma/schema.prisma"
grep -q "model AnalyticsEvent" "$root/apps/api/prisma/schema.prisma"
grep -q 'channel String @default("IN_APP")' "$root/apps/api/prisma/schema.prisma"
grep -q 'priority String @default("MEDIUM")' "$root/apps/api/prisma/schema.prisma"
grep -q "resumeAt DateTime" "$root/apps/api/prisma/schema.prisma"
grep -q "saved/:id/run" "$root/apps/api/src/search/search.controller.ts"
grep -q "preferences" "$root/apps/api/src/notifications/notifications.controller.ts"
grep -q "analytics.read" "$root/apps/api/src/common/authorization/access.constants.ts"
grep -q "WAIT" "$root/apps/api/src/workflows/workflows.service.ts"
grep -q "resume" "$root/apps/api/src/workflows/workflows.controller.ts"
grep -q "plainto_tsquery" "$root/apps/api/src/search/search.service.ts"
grep -q "RECOMMENDATION_ACCEPTED" "$root/apps/api/src/analytics/analytics.service.ts"
grep -q "CREATE INDEX IF NOT EXISTS \"Organization_search_fts_idx\"" "$root/apps/api/prisma/migrations/20260112120000_phase14_completion/migration.sql"
if grep -RIn --exclude-dir=node_modules -E '<<<<<<<|=======|>>>>>>>' "$root/apps/api/src" "$root/apps/web/app" "$root/apps/mobile/src" >/dev/null; then echo "Conflict markers found"; exit 1; fi
echo "PHASE 14 ENHANCED STATIC VERIFICATION OK"
