#!/usr/bin/env bash
# =============================================================================
# scripts/verify-backend-complete.sh
#
# این تنها راه واقعی برای گفتن «بک‌اند ۱۰۰٪ کار می‌کند» است. هیچ ابزار
# چت/کدنویسی بدون اجرای واقعی روی Postgres/Redis واقعی نمی‌تواند این را
# تضمین کند. این اسکریپت را روی سیستم خودتان (نه در چت) اجرا کنید.
#
# پیش‌نیاز:
#   - Docker + docker-compose (برای Postgres/Redis محلی) یا اتصال به
#     Postgres/Redis واقعی از طریق DATABASE_URL / REDIS_URL در .env
#   - Node.js 20+ و pnpm یا Corepack
#
# استفاده:
#   bash scripts/verify-backend-complete.sh
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
step() { echo -e "\n${YELLOW}==> $1${NC}"; }
ok() { echo -e "${GREEN}✓ $1${NC}"; }
fail() { echo -e "${RED}✗ $1${NC}"; exit 1; }

FAILURES=0
mark() { if [ "$1" -ne 0 ]; then FAILURES=$((FAILURES+1)); echo -e "${RED}✗ $2${NC}"; else ok "$2"; fi; }

# pnpm 10 may be provided by Corepack rather than installed globally. Keep the
# verification command portable so the release gate behaves the same locally and
# in CI/container builds.
pnpm_cmd() {
  if command -v pnpm >/dev/null 2>&1; then
    command pnpm "$@"
  elif command -v corepack >/dev/null 2>&1; then
    corepack pnpm "$@"
  else
    echo "pnpm یا Corepack نصب نیست. ابتدا Node.js 20+ و pnpm را نصب کنید." >&2
    return 127
  fi
}

# Run every release-gate command and collect all failures. The old script used
# `set -e` with a trailing `mark`, which meant the first failure exited before
# the release report could identify the remaining failures.
run_mark() {
  local label="$1"
  shift
  local code=0
  set +e
  "$@"
  code=$?
  set -e
  mark "$code" "$label"
  return 0
}

step "1/9 نصب وابستگی‌ها (pnpm install)"
run_mark "pnpm install" pnpm_cmd install --frozen-lockfile
if [ "$FAILURES" -gt 0 ]; then
  # A non-frozen install is a deliberate fallback for a lockfile generated by a
  # different pnpm patch version; it is still reported as the install result.
  FAILURES=$((FAILURES-1))
  run_mark "pnpm install (fallback بدون frozen lockfile)" pnpm_cmd install
fi

step "2/9 بالا آوردن Postgres/Redis محلی (در صورت نبود DATABASE_URL/REDIS_URL خارجی)"
compose=()
if [ -f docker-compose.yml ] && [ -z "${DATABASE_URL:-}" ]; then
  compose=()
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    compose=(docker compose)
  elif command -v docker-compose >/dev/null 2>&1; then
    compose=(docker-compose)
  fi
  if [ "${#compose[@]}" -eq 0 ]; then
    mark 127 "Docker Compose نصب نیست؛ Postgres/Redis محلی قابل راه‌اندازی نیستند"
  else
    "${compose[@]}" up -d postgres redis 2>/dev/null || true
    echo "منتظر آماده شدن Postgres و Redis..."
    postgres_ready=1
    redis_ready=1
    for i in $(seq 1 30); do
      if "${compose[@]}" exec -T postgres pg_isready >/dev/null 2>&1; then postgres_ready=0; fi
      if "${compose[@]}" exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then redis_ready=0; fi
      if [ "$postgres_ready" -eq 0 ] && [ "$redis_ready" -eq 0 ]; then break; fi
      sleep 2
    done
    mark "$postgres_ready" "آمادگی Postgres"
    mark "$redis_ready" "آمادگی Redis"
  fi
else
  ok "از DATABASE_URL خارجی استفاده می‌شود یا docker-compose موجود نیست"
fi

step "3/9 Prisma generate"
run_mark "prisma generate" pnpm_cmd --filter @srip/api prisma:generate

step "4/9 Prisma migrate deploy (روی دیتابیس واقعی — این‌جا واقعاً migration اجرا می‌شود)"
run_mark "prisma migrate deploy — شامل migrationهای schema فعلی" pnpm_cmd --filter @srip/api exec prisma migrate deploy

step "5/9 بررسی وجود System User (باید توسط migration درج شده باشد)"
set +e
if [ -n "${DATABASE_URL:-}" ] && command -v psql >/dev/null 2>&1; then
  SYSTEM_USER_CHECK=$(psql "$DATABASE_URL" -tAc "SELECT count(*) FROM \"User\" WHERE id='00000000-0000-0000-0000-000000000099';" 2>&1)
  system_user_code=$?
elif [ "${#compose[@]}" -gt 0 ]; then
  SYSTEM_USER_CHECK=$("${compose[@]}" exec -T postgres psql -U "${POSTGRES_USER:-srip}" -d "${POSTGRES_DB:-srip}" -tAc "SELECT count(*) FROM \"User\" WHERE id='00000000-0000-0000-0000-000000000099';" 2>&1)
  system_user_code=$?
else
  SYSTEM_USER_CHECK='psql یا Docker Compose برای query در دسترس نیست'
  system_user_code=127
fi
set -e
if [ "$system_user_code" -eq 0 ] && printf '%s' "$SYSTEM_USER_CHECK" | grep -Eq '(^|[^0-9])1([^0-9]|$)'; then
  mark 0 "System User موجود است"
else
  echo "خروجی بررسی System User: ${SYSTEM_USER_CHECK:-<خالی>}"
  mark 1 "System User موجود نیست یا query شکست خورد"
fi

step "6/9 Seed داده نمونه"
run_mark "prisma seed" pnpm_cmd --filter @srip/api prisma:seed

step "7/9 Typecheck کل Monorepo"
run_mark "typecheck" pnpm_cmd typecheck

step "8/9 اجرای کامل تست‌های Unit بک‌اند"
run_mark "jest unit tests" pnpm_cmd --filter @srip/api test

step "9/9 Build نهایی بک‌اند"
run_mark "nest build" pnpm_cmd --filter @srip/api build

echo ""
if [ "$FAILURES" -eq 0 ]; then
  echo -e "${GREEN}=========================================================${NC}"
  echo -e "${GREEN} همه مراحل با موفقیت رد شدند. اکنون می‌توانید با اطمینان${NC}"
  echo -e "${GREEN} بگویید بک‌اند روی این محیط به‌درستی نصب، migrate و تست شد.${NC}"
  echo -e "${GREEN}=========================================================${NC}"
  echo ""
  echo "برای بالا آوردن سرور واقعی:"
  echo "  pnpm --filter @srip/api start"
  echo ""
  echo "برای بالا آوردن Worker پس‌زمینه (Overdue Sweep / Analytics / Search maintenance):"
  echo "  QUEUE_WORKER_ENABLED=true pnpm --filter @srip/api start:worker"
else
  echo -e "${RED}=========================================================${NC}"
  echo -e "${RED} $FAILURES مرحله شکست خورد. لاگ بالا را بررسی کنید.${NC}"
  echo -e "${RED}=========================================================${NC}"
  exit 1
fi
