import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { DataClassification } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuthorizationService } from '../common/authorization/authorization.service';
import { AuditService } from '../audit/audit.service';
import { NetworkService } from '../network/network.service';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { EntityResponseDto } from '../common/dto/entity-response.dto'; import { ApprovalService, APPROVAL_ACTIONS } from '../approvals/approval.service';

export const REPORT_KINDS = ['relationship-health','relationship-risk','network','meeting','commitment','action','opportunity','project','company','contact','risk','influence','referral','subsidiary-comparison','executive','holding','executive-summary'] as const;
export type ReportKind = typeof REPORT_KINDS[number];
export type ExportFormat = 'csv'|'xlsx'|'pdf'|'json';

function csvEscape(value: unknown): string { const text = value == null ? '' : typeof value === 'object' ? JSON.stringify(value) : String(value); return /[",\n\r]/.test(text) ? `"${text.replace(/"/g,'""')}"` : text; }
export function toCsv(rows: Array<Record<string, unknown>>): string { const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))]; return `\uFEFF${[keys.map(csvEscape).join(','),...rows.map(r=>keys.map(k=>csvEscape(r[k])).join(','))].join('\r\n')}\r\n`; }
function flatten(value: unknown, prefix=''): Record<string,unknown> { if(value===null||typeof value!=='object'||value instanceof Date) return {[prefix||'value']: value instanceof Date ? value.toISOString() : value}; if(Array.isArray(value)) return {[prefix||'value']:JSON.stringify(value)}; const out:Record<string,unknown>={}; for(const [k,v] of Object.entries(value as Record<string,unknown>)) Object.assign(out,flatten(v,prefix?`${prefix}.${k}`:k)); return out; }

@Injectable()
export class ReportingService {
  constructor(private readonly prisma: PrismaService, private readonly authorization: AuthorizationService, private readonly audit: AuditService, private readonly network: NetworkService, private readonly approvals: ApprovalService) {}
  validateKind(kind:string):ReportKind { if(!(REPORT_KINDS as readonly string[]).includes(kind)) throw new BadRequestException(`Unsupported report kind: ${kind}`); return kind as ReportKind; }
  validateFormat(format:string):ExportFormat { if(!['csv','xlsx','pdf','json'].includes(format)) throw new BadRequestException(`Unsupported export format: ${format}`); return format as ExportFormat; }
  private async scope(userId:string, organizationId?:string) { await this.authorization.assertPermission(userId, 'report.read', { organizationId: organizationId }); const ids=await this.authorization.accessibleOrganizationIds(userId); if(organizationId){ if(ids && !ids.includes(organizationId)) throw new BadRequestException('Organization outside scope'); return [organizationId]; } return ids; }
  private relScope(ids:string[]|null){ return ids?{OR:[{sourceOrganizationId:{in:ids}},{targetOrganizationId:{in:ids}}]}:{}; }
  private pageLimit(value?: number){ return Math.max(25, Math.min(Number(value)||200, 500)); }
  private pageOffset(page?: number, limit?: number){ const p=Math.max(1,Number(page)||1); const l=this.pageLimit(limit); return { page:p, limit:l, skip:(p-1)*l }; }

  private async relationshipRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.relationship.findMany({where:{deletedAt:null,...this.relScope(ids),...(organizationId?{OR:[{sourceOrganizationId:organizationId},{targetOrganizationId:organizationId}]}:{})},include:{sourceOrganization:{select:{id:true,name:true}},targetOrganization:{select:{id:true,name:true}},relationshipTypeRef:{select:{key:true,name:true}}},orderBy:[{healthScore:'asc'},{updatedAt:'desc'}],skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    return rows.map(r=>({id:r.id,sourceOrganization:r.sourceOrganization.name,targetOrganization:r.targetOrganization.name,relationshipType:r.relationshipTypeRef?.name??r.relationshipType,status:r.status,healthScore:r.healthScore,riskScore:r.riskScore,strategicScore:r.strategicScore,trustScore:r.trustScore,accessScore:r.accessScore,influenceScore:r.influenceScore,opportunityScore:r.opportunityScore,resilienceScore:r.resilienceScore,engagementScore:r.engagementScore,lastInteractionAt:r.lastInteractionAt,nextReviewAt:r.nextReviewAt,nextActionAt:r.nextActionAt}));
  }
  private async meetingRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.meeting.findMany({where:{deletedAt:null,...(ids?{organizationId:{in:ids}}:{}),...(organizationId?{organizationId}: {})},include:{organization:{select:{id:true,name:true}},relationship:{include:{sourceOrganization:{select:{name:true}},targetOrganization:{select:{name:true}}}},participants:{include:{person:{select:{firstName:true,lastName:true}}}}},orderBy:{startAt:'desc'},skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    return rows.map(m=>({id:m.id,title:m.title,startAt:m.startAt,endAt:m.endAt,status:m.status,organization:m.organization?.name??null,relationship:m.relationship?`${m.relationship.sourceOrganization.name} → ${m.relationship.targetOrganization.name}`:null,participants:m.participants.map(p=>`${p.person.firstName} ${p.person.lastName}`).join('; ')}));
  }
  private async opportunityRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.opportunity.findMany({where:{deletedAt:null,...(ids?{organizationId:{in:ids}}:{}),...(organizationId?{organizationId}:{})},include:{organization:{select:{name:true}},project:{select:{name:true}},relationship:{include:{sourceOrganization:{select:{name:true}},targetOrganization:{select:{name:true}}}}},orderBy:{updatedAt:'desc'},skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    return rows.map(o=>({id:o.id,name:o.name,status:o.status,value:o.value?.toString()??null,probability:o.probability,organization:o.organization?.name??null,project:o.project?.name??null,relationship:o.relationship?`${o.relationship.sourceOrganization.name} → ${o.relationship.targetOrganization.name}`:null,createdAt:o.createdAt,updatedAt:o.updatedAt}));
  }
  private async projectRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.project.findMany({where:{deletedAt:null,...(ids?{organizationId:{in:ids}}:{}),...(organizationId?{organizationId}:{})},include:{organization:{select:{name:true}},owner:{select:{name:true}},risks:true,milestones:true,actions:{select:{id:true,status:true,dueAt:true}},commitments:{select:{id:true,status:true,dueAt:true}}},orderBy:{updatedAt:'desc'},skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    const now=new Date(); return rows.map(p=>({id:p.id,name:p.name,status:p.status,priority:p.priority,objective:p.objective,organization:p.organization?.name??null,owner:p.owner?.name??null,risks:p.risks.length,openRisks:p.risks.filter(r=>r.status!=='CLOSED').length,milestones:p.milestones.length,overdueMilestones:p.milestones.filter(m=>m.dueAt&&m.dueAt<now&&m.status!=='COMPLETED').length,actions:p.actions.length,overdueActions:p.actions.filter(a=>a.dueAt&&a.dueAt<now&&!['DONE','COMPLETED','CANCELLED'].includes(a.status)).length,commitments:p.commitments.length,openCommitments:p.commitments.filter(c=>!['DONE','COMPLETED','CANCELLED'].includes(c.status)).length,startAt:p.startAt,targetAt:p.targetAt,updatedAt:p.updatedAt}));
  }

  private async actionRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.action.findMany({where:{deletedAt:null,...(ids?{organizationId:{in:ids}}:{}),...(organizationId?{organizationId}:{})},include:{organization:{select:{name:true}},owner:{select:{name:true}},project:{select:{name:true}},relationship:{select:{id:true}}},orderBy:[{dueAt:'asc'},{updatedAt:'desc'}],skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    const now=new Date();
    return rows.map(a=>({id:a.id,title:a.title,status:a.status,priority:a.priority,dueAt:a.dueAt,reminderAt:a.reminderAt,owner:a.owner?.name??null,organization:a.organization?.name??null,project:a.project?.name??null,relationshipId:a.relationshipId,overdue:!!a.dueAt&&a.dueAt<now&&!['DONE','COMPLETED','CANCELLED'].includes(a.status),completionAt:a.completionAt,outcome:a.outcome}));
  }
  private async commitmentRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.commitment.findMany({where:{deletedAt:null,...(ids?{organizationId:{in:ids}}:{}),...(organizationId?{organizationId}:{})},include:{organization:{select:{name:true}},owner:{select:{name:true}}},orderBy:[{dueAt:'asc'},{updatedAt:'desc'}],skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    const now=new Date();
    return rows.map(c=>({id:c.id,description:c.description,source:c.source,receiver:c.receiver,status:c.status,dueAt:c.dueAt,reminderAt:c.reminderAt,owner:c.owner.name,organization:c.organization?.name??null,risk:c.risk,overdue:!!c.dueAt&&c.dueAt<now&&!['DONE','COMPLETED','CANCELLED'].includes(c.status),completionAt:c.completionAt}));
  }
  private async contactRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.person.findMany({where:{deletedAt:null,...(ids?{organizationId:{in:ids}}:{}),...(organizationId?{organizationId}:{})},include:{organization:{select:{name:true}},_count:{select:{interactions:true,meetingParticipants:true,actions:true,commitments:true}}},orderBy:[{influenceScore:'desc'},{updatedAt:'desc'}],skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    return rows.map(p=>({id:p.id,name:p.displayName??`${p.firstName} ${p.lastName}`,email:p.email,title:p.title,organization:p.organization.name,influenceScore:p.influenceScore,decisionPower:p.decisionPower,accessibilityScore:p.accessibilityScore,interactions:p._count.interactions,meetings:p._count.meetingParticipants,actions:p._count.actions,commitments:p._count.commitments}));
  }
  private async riskRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.relationship.findMany({where:{deletedAt:null,...this.relScope(ids),...(organizationId?{OR:[{sourceOrganizationId:organizationId},{targetOrganizationId:organizationId}]}:{})},include:{sourceOrganization:{select:{name:true}},targetOrganization:{select:{name:true}}},orderBy:[{riskScore:'desc'},{healthScore:'asc'}],skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    return rows.map(r=>({id:r.id,sourceOrganization:r.sourceOrganization.name,targetOrganization:r.targetOrganization.name,riskScore:r.riskScore,healthScore:r.healthScore,strategicScore:r.strategicScore,ownerId:r.ownerId,nextReviewAt:r.nextReviewAt,nextActionAt:r.nextActionAt}));
  }
  private async influenceRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    return this.executiveRows(ids,organizationId);
  }
  private async referralRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.referral.findMany({where:{deletedAt:null,...(ids?{OR:[{sourceOrganizationId:{in:ids}},{targetOrganizationId:{in:ids}}]}:{}),...(organizationId?{OR:[{sourceOrganizationId:organizationId},{targetOrganizationId:organizationId}]}:{})},include:{sourceOrganization:{select:{name:true}},targetOrganization:{select:{name:true}},sourcePerson:{select:{displayName:true,firstName:true,lastName:true}},targetPerson:{select:{displayName:true,firstName:true,lastName:true}}},orderBy:{createdAt:'desc'},skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    const success=rows.filter(x=>x.status==='COMPLETED').length;
    return {summary:{total:rows.length,successful:success,successRate:rows.length?Number((success/rows.length*100).toFixed(2)):0},data:rows.map(x=>({id:x.id,status:x.status,title:x.title,sourceOrganization:x.sourceOrganization?.name??null,targetOrganization:x.targetOrganization?.name??null,sourcePerson:x.sourcePerson?.displayName??(`${x.sourcePerson?.firstName??''} ${x.sourcePerson?.lastName??''}`.trim()||null),targetPerson:x.targetPerson?.displayName??(`${x.targetPerson?.firstName??''} ${x.targetPerson?.lastName??''}`.trim()||null),relationshipId:x.relationshipId,completedAt:x.completedAt,createdAt:x.createdAt}))};
  }

  private async companyRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.organization.findMany({where:{deletedAt:null,...(ids?{id:{in:ids}}:{}),...(organizationId?{id:organizationId}:{})},include:{_count:{select:{people:true,sourceRelationships:true,targetRelationships:true,meetings:true,projects:true,opportunities:true,documents:true}},owner:{select:{name:true}}},orderBy:{name:'asc'},skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    return (rows as Array<(typeof rows)[number] & { _count: { people: number; sourceRelationships: number; targetRelationships: number; meetings: number; projects: number; opportunities: number; documents: number } }>).map(o=>({id:o.id,name:o.name,legalName:o.legalName,type:o.type,status:o.status,industry:o.industry,country:o.country,city:o.city,website:o.website,strategicImportance:o.strategicImportance,registrationId:o.registrationId,owner:o.owner?.name??null,people:o._count.people,relationships:o._count.sourceRelationships+o._count.targetRelationships,meetings:o._count.meetings,projects:o._count.projects,opportunities:o._count.opportunities,documents:o._count.documents,createdAt:o.createdAt,updatedAt:o.updatedAt}));
  }
  private async executiveRows(ids:string[]|null, organizationId?:string, page=1, limit=200){
    const rows=await this.prisma.person.findMany({where:{deletedAt:null,...(ids?{organizationId:{in:ids}}:{}),...(organizationId?{organizationId}:{})},include:{organization:{select:{name:true}},_count:{select:{interactions:true,meetingParticipants:true,actions:true,commitments:true,notes:true}}},orderBy:[{influenceScore:'desc'},{decisionPower:'desc'}],skip:this.pageOffset(page,limit).skip,take:this.pageOffset(page,limit).limit});
    return rows.map(p=>({id:p.id,name:p.displayName??`${p.firstName} ${p.lastName}`,title:p.title,organization:p.organization.name,department:p.department,influenceScore:p.influenceScore,decisionPower:p.decisionPower,accessibilityScore:p.accessibilityScore,interactions:p._count.interactions,meetings:p._count.meetingParticipants,actions:p._count.actions,commitments:p._count.commitments,notes:p._count.notes,createdAt:p.createdAt,updatedAt:p.updatedAt}));
  }
  private async holdingReport(ids:string[]|null, organizationId?:string){
    const rows=await this.prisma.organization.findMany({where:{deletedAt:null,...(ids?{id:{in:ids}}:{}),...(organizationId?{id:organizationId}:{})},select:{id:true,name:true,parentOrganizationId:true,status:true,strategicImportance:true,country:true,type:true},orderBy:{id:'asc'},take:this.pageLimit(1000)}); const map=new Map<string,any[]>(); for(const r of rows){const k=r.parentOrganizationId??'ROOT'; map.set(k,[...(map.get(k)??[]),r]);} const build=(parent:string|null):any[]=>(map.get(parent??'ROOT')??[]).map(r=>({...r,children:build(r.id)})); return {generatedAt:new Date().toISOString(),organizations:rows.length,roots:build(null)};
  }
  private async networkReport(userId:string, ids:string[]|null, organizationId?:string){ const [graph,centrality,connectors,bridges,bottlenecks,singlePointsOfFailure]=await Promise.all([this.network.graph(userId,organizationId),this.network.centrality(userId,organizationId,20),this.network.connectors(userId,organizationId,20),this.network.bridgePeople(userId,organizationId,20),this.network.bottlenecks(userId,organizationId,20),this.network.singlePointsOfFailure(userId,organizationId,20)]); return {generatedAt:new Date().toISOString(),graph,centrality,connectors,bridges,bottlenecks,singlePointsOfFailure,accessibleOrganizationCount:ids?.length??'all'}; }

  private async executiveSummary(ids:string[]|null, organizationId?:string){
    const [companies,relationships,opportunities,meetings,projects]=await Promise.all([this.companyRows(ids,organizationId),this.relationshipRows(ids,organizationId),this.opportunityRows(ids,organizationId),this.meetingRows(ids,organizationId),this.projectRows(ids,organizationId)]); const now=Date.now(); const risks=relationships.filter(r=>r.riskScore>=50||r.healthScore<50); const open=opportunities.filter(o=>!['WON','LOST'].includes(String(o.status))); const upcoming=meetings.filter(m=>m.startAt&&new Date(m.startAt).getTime()>=now).slice(0,20); const overdue=projects.filter(p=>p.overdueActions>0||p.overdueMilestones>0).length;
    return {generatedAt:new Date().toISOString(),summary:{companies:companies.length,relationships:relationships.length,healthyRelationships:relationships.filter(r=>r.healthScore>=70).length,atRiskRelationships:risks.length,openOpportunities:open.length,projects:projects.length,projectsWithOverdueWork:overdue,upcomingMeetings:upcoming.length},kpi:{averageRelationshipHealth:relationships.length?Math.round(relationships.reduce((a,r)=>a+r.healthScore,0)/relationships.length):0,averageRelationshipRisk:relationships.length?Math.round(relationships.reduce((a,r)=>a+r.riskScore,0)/relationships.length):0,weightedOpportunityValue:open.reduce((a,o)=>a+Number(o.value??0)*(o.probability/100),0)},trends:{relationshipHealth:{average:relationships.length?relationships.reduce((a,r)=>a+r.healthScore,0)/relationships.length:0},opportunityPipeline:{count:open.length}},risks:risks.slice(0,50),opportunities:open.slice(0,50),recommendations:risks.slice(0,20).map(r=>({relationshipId:r.id,recommendation:'Review relationship health and next action',nextReviewAt:r.nextReviewAt,nextActionAt:r.nextActionAt})),supportingData:{companies:companies.slice(0,100),projects:projects.slice(0,100),meetings:upcoming}};
  }
  async report(userId:string, kindInput:string, organizationId?:string, page=1, limit=200){ const kind=this.validateKind(kindInput); const ids=await this.scope(userId,organizationId); switch(kind){case'relationship-health':return{report:kind,generatedAt:new Date().toISOString(),data:await this.relationshipRows(ids,organizationId,page,limit)};case'relationship-risk':return{report:kind,generatedAt:new Date().toISOString(),data:(await this.relationshipRows(ids,organizationId,page,limit)).filter(r=>r.riskScore>=50||r.healthScore<50)};case'network':return{report:kind,...await this.networkReport(userId,ids,organizationId)};case'meeting':return{report:kind,generatedAt:new Date().toISOString(),data:await this.meetingRows(ids,organizationId,page,limit)};case'commitment':return{report:kind,generatedAt:new Date().toISOString(),data:await this.commitmentRows(ids,organizationId,page,limit)};case'action':return{report:kind,generatedAt:new Date().toISOString(),data:await this.actionRows(ids,organizationId,page,limit)};case'opportunity':return{report:kind,generatedAt:new Date().toISOString(),data:await this.opportunityRows(ids,organizationId,page,limit)};case'project':return{report:kind,generatedAt:new Date().toISOString(),data:await this.projectRows(ids,organizationId,page,limit)};case'company':return{report:kind,generatedAt:new Date().toISOString(),data:await this.companyRows(ids,organizationId,page,limit)};case'contact':return{report:kind,generatedAt:new Date().toISOString(),data:await this.contactRows(ids,organizationId,page,limit)};case'risk':return{report:kind,generatedAt:new Date().toISOString(),data:await this.riskRows(ids,organizationId,page,limit)};case'influence':return{report:kind,generatedAt:new Date().toISOString(),data:await this.influenceRows(ids,organizationId,page,limit)};case'referral':return{report:kind,...await this.referralRows(ids,organizationId)};case'subsidiary-comparison':return{report:kind,generatedAt:new Date().toISOString(),data:await this.companyRows(ids,organizationId,page,limit)};case'executive':return{report:kind,generatedAt:new Date().toISOString(),data:await this.executiveRows(ids,organizationId)};case'holding':return{report:kind,...await this.holdingReport(ids,organizationId)};case'executive-summary':return{report:kind,...await this.executiveSummary(ids,organizationId)};} }
  private rows(payload:any):Array<Record<string,unknown>>{ if(Array.isArray(payload?.data)) return payload.data.map((r:any)=>flatten(r)); const out:Array<Record<string,unknown>>=[]; for(const [section,value] of Object.entries(payload??{})){if(['report','generatedAt'].includes(section))continue;if(Array.isArray(value))(value as unknown[]).forEach(v=>out.push({section,...flatten(v)}));else if(value&&typeof value==='object')out.push({section,...flatten(value)});else out.push({section,value});} return out; }
  private async pdf(payload:any){return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:40,info:{Title:`SRIP ${payload.report??'Report'}`,Author:'SRIP Reporting Engine'}});const chunks:Buffer[]=[];doc.on('data',(c:Buffer)=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);doc.fontSize(18).text(`SRIP Report: ${payload.report??'Report'}`);doc.moveDown().fontSize(9).text(`Generated: ${payload.generatedAt??new Date().toISOString()}`);doc.moveDown();for(const row of this.rows(payload)){const line=Object.entries(row).map(([k,v])=>`${k}: ${typeof v==='object'?JSON.stringify(v):String(v??'')}`).join(' | ');if(doc.y>740)doc.addPage();doc.fontSize(8).text(line,{width:515});doc.moveDown(.15);}doc.end();});}
  private async xlsx(payload:any){const wb=new ExcelJS.Workbook();wb.creator='SRIP Reporting Engine';const ws=wb.addWorksheet(String(payload.report??'report').slice(0,31));const rows=this.rows(payload);const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];ws.columns=keys.map(k=>({header:k,key:k,width:Math.min(60,Math.max(12,k.length+2))}));rows.forEach(r=>ws.addRow(r));ws.views=[{state:'frozen',ySplit:1}];if(keys.length)ws.autoFilter={from:'A1',to:`${String.fromCharCode(64+Math.min(keys.length,26))}1`};return Buffer.from(await wb.xlsx.writeBuffer());}
  async export(userId:string,kindInput:string,formatInput:string,organizationId?:string,requestId?:string,ipAddress?:string,approvalId?:string){const kind=this.validateKind(kindInput);const format=this.validateFormat(formatInput);const payload=await this.report(userId,kind,organizationId);await this.authorization.assertPermission(userId, 'report.export', { organizationId: organizationId, classification:'INTERNAL' });
    if (format === 'json') await this.authorization.assertPermission(userId, 'enterprise.admin', { organizationId });
    if (!approvalId) throw new ForbiddenException('Approved export request is required');
    await this.approvals.assertApproved(userId, approvalId, APPROVAL_ACTIONS.EXPORT, 'Report', kind);const rows=this.rows(payload);let body:Buffer;let contentType:string;switch(format){case'csv':body=Buffer.from(toCsv(rows),'utf8');contentType='text/csv; charset=utf-8';break;case'json':body=Buffer.from(JSON.stringify(payload,null,2),'utf8');contentType='application/json; charset=utf-8';break;case'xlsx':body=await this.xlsx(payload);contentType='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';break;case'pdf':body=await this.pdf(payload);contentType='application/pdf';break;}const filename=`srip-${kind}-${new Date().toISOString().replace(/[:.]/g,'-')}.${format}`;const log=await this.prisma.dataExportLog.create({data:{userId,organizationId,exportType:format.toUpperCase(),entityType:kind,recordCount:rows.length,classification:'INTERNAL',requestId,ipAddress}});await this.audit.logMutation({userId,action:'EXPORT',entityType:'Report',entityId:log.id,organizationId,after:{report:kind,format,recordCount:rows.length,filename}});return{body,filename,contentType,recordCount:rows.length};}
}
