'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { api,unwrapList } from '../_lib/api';
type Meeting={id:string;title:string;startAt:string;endAt?:string;objective?:string;agenda?:string;outcome?:string;notes?:string;preMeetingBrief?:string;organization?:{name:string};participants:{person:{firstName:string;lastName:string}}[];actions:any[];commitments:any[]};
export default function MeetingsPage(){const [items,setItems]=useState<Meeting[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [upcoming,setUpcoming]=useState(false);const [form,setForm]=useState({title:'',startAt:new Date(Date.now()+3600000).toISOString().slice(0,16),endAt:'',objective:'',agenda:'',location:'',meetingUrl:'',organizationId:'',relationshipId:''});const [outcomeDrafts,setOutcomeDrafts]=useState<Record<string,string>>({});
const load=()=>{setLoading(true);return api<Meeting[]>(`/meetings?upcoming=${upcoming}`).then(x=>setItems(unwrapList<Meeting>(x))).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[upcoming]);
async function submit(e:FormEvent){e.preventDefault();try{await api('/meetings',{method:'POST',body:JSON.stringify({...form,startAt:new Date(form.startAt).toISOString(),endAt:form.endAt?new Date(form.endAt).toISOString():undefined,organizationId:form.organizationId||undefined,relationshipId:form.relationshipId||undefined})});setForm({...form,title:'',objective:'',agenda:''});await load()}catch(e:any){setError(e.message)}}
async function outcome(id:string){const value=(outcomeDrafts[id]??'').trim();if(!value)return;try{await api(`/meetings/${id}/outcome`,{method:'POST',body:JSON.stringify({outcome:value})});setOutcomeDrafts(d=>({...d,[id]:''}));await load()}catch(e:any){setError(e.message)}}
return <main className="shell"><header className="topbar"><strong>SRIP</strong><nav><a href="/">Dashboard</a><a href="/interactions">Interactions</a><a href="/relationships">Relationships</a></nav></header><section className="hero"><p className="eyebrow">Meeting Workspace</p><h1>Meetings</h1><p>Agenda, participants, outcomes, decisions and linked actions/commitments.</p></section>{error&&<section className="card"><strong>Unable to complete request</strong><p>{error}</p></section>}
<section className="card"><h2>Schedule meeting</h2><form onSubmit={submit} className="form-grid"><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Start<input type="datetime-local" value={form.startAt} onChange={e=>setForm({...form,startAt:e.target.value})}/></label><label>End<input type="datetime-local" value={form.endAt} onChange={e=>setForm({...form,endAt:e.target.value})}/></label><label>Organization ID<input value={form.organizationId} onChange={e=>setForm({...form,organizationId:e.target.value})}/></label><label>Relationship ID<input value={form.relationshipId} onChange={e=>setForm({...form,relationshipId:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label className="full">Objective<textarea value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/></label><label className="full">Agenda<textarea value={form.agenda} onChange={e=>setForm({...form,agenda:e.target.value})}/></label><button>Schedule meeting</button></form></section>
<section className="toolbar"><button onClick={()=>setUpcoming(false)} aria-pressed={!upcoming}>All</button><button onClick={()=>setUpcoming(true)} aria-pressed={upcoming}>Upcoming</button></section> {loading?<p>در حال بارگذاری…</p>:items.length===0?<p className="empty-state">جلسه‌ای ثبت نشده است.</p>:<section className="grid">{items.map(m=><article className="card" key={m.id}><span className="badge">{new Date(m.startAt).toLocaleString()}</span><h2><Link href={`/meetings/${m.id}`}>{m.title}</Link></h2><p>{m.objective||'No objective recorded.'}</p><p><strong>Participants:</strong> {m.participants.map(p=>`${p.person.firstName} ${p.person.lastName}`).join(', ')||'None'}</p><p><strong>Actions:</strong> {m.actions.length} · <strong>Commitments:</strong> {m.commitments.length}</p>{m.agenda&&<details><summary>Agenda</summary><p>{m.agenda}</p></details>}{m.outcome&&<p><strong>Outcome:</strong> {m.outcome}</p>}<div className="inline-form"><input className="inline-input" placeholder="Record outcome" value={outcomeDrafts[m.id]??''} onChange={e=>setOutcomeDrafts(d=>({...d,[m.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter')outcome(m.id)}}/><button onClick={()=>outcome(m.id)}>Save</button></div></article>)}</section>}</main>}
