// نمایش فارسی برای مقادیر و برچسب‌های انگلیسی — فقط لایهٔ نمایش؛ مقادیر ارسالی به API تغییری نمی‌کند.
export const STATUS_FA: Record<string, string> = {  ACTIVE:'فعال',
  ON_HOLD:'متوقف',
  DONE:'انجام‌شده',
  COMPLETED:'تکمیل‌شده',
  APPROVED:'تأییدشده',
  EXECUTED:'اجرا شده',
  SUCCESS:'موفق',
  OPEN:'باز',
  FULFILLED:'انجام‌شده',
  HEALTHY:'سالم',
  REJECTED:'ردشده',
  CANCELLED:'لغوشده',
  FAILED:'ناموفق',
  BLOCKED:'مسدود',
  ARCHIVED:'بایگانی‌شده',
  LOST:'از دست رفته',
  OVERDUE:'عقب‌افتاده',
  CRITICAL:'بحرانی',
  WATCH:'تحت نظر',
  PENDING:'در انتظار',
  SNOOZED:'به تعویق افتاده',
  AT_RISK:'در معرض ریسک',
  IN_PROGRESS:'در حال انجام',
  PLANNED:'برنامه‌ریزی‌شده',
  WARNING:'هشدار',
  PROPOSED:'پیشنهادی',
  ASSIGNED:'اختصاص‌یافته',
  DEVELOPING:'در حال توسعه',
  INTRODUCED:'معرفی‌شده',
  IDENTIFIED:'شناسایی‌شده',
  INITIAL_CONTACT:'تماس اولیه',
  STRATEGIC:'راهبردی',
  MITIGATED:'کاهش‌یافته',
  ACCEPTED:'پذیرفته‌شده',
  ERASED:'پاک‌شده',
  GRANTED:'اعطاشده',
  PROCESSING:'در حال پردازش',
  SATISFIED:'برآورده‌شده',
  UNENGAGED:'بدون درگیری',
  ENGAGED:'پیوند فعال',
  DORMANT:'خفته',
  PROSPECTIVE:'آینده‌نگر',
  RISING:'رو به رشد',
  DECLINING:'در حال افول',
  STABLE:'پایدار',
  NEGOTIATION:'در حال مذاکره',
  LOYAL:'وفادار',
  NEW:'جدید',
  TRANSITION:'در گذار',
  EXPANDING:'در حال گسترش',
  CLOSED:'بسته',
  ERASURE:'پاک‌سازی',
  EXPORT:'خروجی',
  ACCESS:'دسترسی',
  NEGATIVE:'منفی',
  POSITIVE:'مثبت',
  NEUTRAL:'خنثی',
  LOW:'کم',
  MEDIUM:'متوسط',
  HIGH:'زیاد',
  INACTIVE:'غیرفعال',
  ON_LEAVE:'در مرخصی',
  WON:'برنده شده',
  LOST_OPP:'از دست رفته',
  QUALIFYING:'در حال ارزیابی',
  CLOSING:'در حال بستن',
  DELIVERING:'در حال تحویل',
  PROPOSAL:'پیشنهاد',
  EVALUATION:'ارزیابی',
  INTERESTED:'علاقه‌مند',
  NOT_INTERESTED:'بی‌علاقه',
  UNREACHABLE:'غیرقابل دسترس',
  ACTIVE_ENGAGEMENT:'درگیر فعال',
  PASSIVE:'منفعل',
  PHONE:'تلفن',
  EMAIL:'ایمیل',
  ADDRESS:'نشانی',
  WEBSITE:'وب‌سایت',
  LINKEDIN:'لینکدین',
  OTHER:'سایر',
  INTERNAL:'داخلی',
  CONFIDENTIAL:'محرمانه',
  RESTRICTED:'محدود',
  PUBLIC:'عمومی',
  READY:'آماده',
  CLEAN:'پاک',
  NOT_REQUIRED:'غیرضروری',
  QUARANTINED:'قرنطینه‌شده',
  INFECTED:'آلوده',
  ERROR:'خطا',
  CUSTOMER:'مشتری',
  SUPPLIER:'تأمین‌کننده',
  PARTNER:'شریک',
  COMPETITOR:'رقبا',
  INVESTOR:'سرمایه‌گذار',
  REGULATOR:'ناظر',
  GOVERNMENT:'دولت',
  MEDIA:'رسانه',
  NGO:'سازمان مردم‌نهاد',
  MEETING:'جلسه',
  INTERACTION:'تعامل',
  COMMITMENT:'تعهد',
  EVENT:'رویداد',
  ACTION:'اقدام',
  OPPORTUNITY:'فرصت',
  PROJECT:'پروژه',
  RISK:'ریسک',
  MILESTONE:'مرحله',
  REQUIREMENT:'الزام',
  HOLDING:'هلدینگ',
  SUBSIDIARY:'شرکت تابعه',
  BANK:'بانک',
  ALL:'همه',
  ORGANIZATION:'سازمان',
  PERSON:'شخص',
  RELATIONSHIP:'رابطه',
  RECOMMENDATION:'پیشنهاد',
  DOCUMENT:'سند',
  NOTE:'یادداشت',
  WORKFLOW:'گردش کار',
  REFERRAL:'معرفی',
  CONNECTIONPATH:'مسیر ارتباطی',
  ORGANIZATIONUNIT:'واحد سازمانی',
  KEY:'کلید',
  TEXT:'متن',
  NUMBER:'عدد',
  DATE:'تاریخ',
  BOOLEAN:'بله/خیر',
  SELECT:'انتخابی',
  TEXTAREA:'متن بلند',
  FIELD:'فیلد',
  GROUP:'گروه',
  TITLE:'عنوان',
  URL:'نشانی',
  ICON:'آیکون',
  HIDDEN:'پنهان',
  INFO:'اطلاع',
  DANGER:'خطر'};
export const REL_TYPE_FA: Record<string, string> = {
  PARTNERSHIP:'مشارکت', JOINT_VENTURE:'سرمایه‌گذاری مشترک', CUSTOMER:'مشتری', SUPPLIER:'تأمین‌کننده',
  INVESTOR:'سرمایه‌گذار', COMPETITOR:'رقابت', STRATEGIC_ALLIANCE:'اتحاد راهبردی', COMMERCIAL:'تجاری',
  INTERNAL:'داخلی', REGULATORY:'نظارتی', DISTRIBUTION:'توزیع', OTHER:'سایر', ACQUISITION:'تملیک',
  MERGER:'ادغام', STRATEGIC:'راهبردی', PARTNER:'شریک', INVESTMENT:'سرمایه‌گذاری',
  PARENT_SUBSIDIARY:'مادر-تابعه', SHAREHOLDER:'سهام‌داری', COLLABORATION:'همکاری', OUTSOURCING:'برون‌سپاری',
  SCANNING:'در حال اسکن',
  CONNECTED:'متصل',
  DISCONNECTED:'قطع‌شده',
  PARTIAL:'بخشی',
  RUNNING:'در حال اجرا',
  CALENDAR:'تقویم',
  EMAIL:'ایمیل',
  GOOGLE:'گوگل',
  MICROSOFT:'مایکروسافت',
  REVOKED:'ابطال‌شده',
  EXPIRED:'منقضی‌شده',
  DELETED:'حذف‌شده',
  DUPLICATE:'تکراری',
  VALID:'معتبر',
  INVALID:'نامعتبر',
  SENT:'ارسال‌شده',
  READ:'خوانده‌شده',
  UNREAD:'خوانده‌نشده',
  ENABLED:'فعال',
  DISABLED:'غیرفعال',
  BUSINESS:'تجاری',
  TECHNICAL:'فنی',
  PROCESS:'فرایندی',
  COMPLIANCE:'مقرراتی',
  RESOURCE:'منابعی',
  SATISFIED:'برآورده‌شده',
  QUALIFYING:'در حال ارزیابی',
  WON:'موفق',
  LOST:'از دست رفته',
  UNENGAGED:'بدون درگیری',
  DATETIME:'تاریخ و زمان',
  MULTISELECT:'چندگزین‌های',
  INTERACTION:'تعامل',
  MEETING:'جلسه',
  ACTION:'اقدام',  DUE_SOON:'به‌زودی',
  REMINDER:'یادآوری',
  SYSTEM:'سیستمی',
  IMPORTANT:'مهم',
  INFORMATION:'اطلاع',
  VISIT:'بازدید',
  SUPPLY:'تأمین',
  BANKING:'بانکی',
  STRATEGIC_PARTNERSHIP:'مشارکت راهبردی',
  FOLLOW_UP:'پیگیری',
  RISK_MITIGATION:'کاهش ریسک',
  DIVERSIFICATION:'تنوع‌بخشی',
  DEPARTMENT:'دپارتمان',
  DIVISION:'بخش',
  BRANCH:'شعبه',
  BUSINESS_UNIT:'واحد کسب‌وکار',
  LOCATION:'مکان',
  UPCOMING:'پیشِ رو',
  MOBILE:'تلفن همراه',

};
export const fa = (v: unknown): string => {
  if (v == null) return '—';
  const s = String(v);
  return STATUS_FA[s.toUpperCase()] ?? REL_TYPE_FA[s.toUpperCase()] ?? s;
};

export const KEY_FA: Record<string, string> = {
  id:'شناسه', key:'کلید', name:'نام', title:'عنوان', description:'توضیح', status:'وضعیت', type:'نوع',
  kind:'نوع', state:'وضعیت', priority:'اولویت', category:'دسته', severity:'شدت', effect:'اثر', role:'نقش',
  source:'منبع', purpose:'هدف', version:'نسخه', label:'برچسب', value:'ارزش', score:'امتیاز',
  createdAt:'تاریخ ایجاد', updatedAt:'تاریخ به‌روزرسانی', createdBy:'ایجادشده توسط',
  email:'ایمیل', phone:'تلفن', url:'نشانی', country:'کشور', city:'شهر', address:'نشانی',
  organizationId:'شناسه سازمان', organizationName:'نام سازمان', organization:'سازمان',
  personId:'شناسه شخص', person:'شخص', relationshipId:'شناسه رابطه', relationship:'رابطه',
  meetingId:'شناسه جلسه', meeting:'جلسه', projectId:'شناسه پروژه', project:'پروژه',
  action:'عملیات', entityType:'نوع نهاد', entityId:'شناسه نهاد', userId:'کاربر', reason:'دلیل',
  ipAddress:'نشانی IP', userAgent:'مرورگر', permissionKey:'کلید مجوز', isActive:'فعال',
  emailVerifiedAt:'تأیید ایمیل', lastLoginAt:'آخرین ورود', entityName:'نام نهاد',
  fileName:'نام فایل', mimeType:'نوع فایل', sizeBytes:'حجم', classification:'طبقه‌بندی',
  scanStatus:'وضعیت اسکن', uploadStatus:'وضعیت بارگذاری', flagged:'علامت‌خورده',
  channels:'کانال‌ها', eventType:'نوع رویداد', active:'فعال', enabled:'فعال', rollout:'گسترش',
  policyKey:'کلید خط‌مشی', effectType:'نوع اثر', condition:'شرط', rule:'قاعده', matchType:'نوع تطبیق',
  fieldKey:'کلید فیلد', fieldType:'نوع فیلد', entityTypes:'انواع نهاد', displayName:'نام نمایشی',
  firstName:'نام', lastName:'نام خانوادگی', department:'بخش', title_job:'سمت',
  startAt:'شروع', endAt:'پایان', dueAt:'سررسید', completedAt:'تاریخ تکمیل', occurredAt:'زمان وقوع',
  lastLogin:'آخرین ورود', expiresAt:'انقضا', revokedAt:'زمان ابطال', device:'دستگاه',
  browser:'مرورگر', os:'سیستم عامل', location:'مکان', sessionId:'شناسه نشست', ip:'نشانی IP',
  total:'کل', count:'تعداد', limit:'محدودیت', page:'صفحه', offset:'آفست',
  approvalStatus:'وضعیت تأیید', decidedBy:'تصمیم‌گیرنده', decidedAt:'زمان تصمیم',
  risk:'ریسک', probability:'احتمال', impact:'تأثیر', mitigation:'پایش', healthScore:'امتیاز سلامت',
  riskScore:'امتیاز ریسک', strategicScore:'امتیاز راهبردی', influenceScore:'امتیاز نفوذ',
  decisionPower:'قدرت تصمیم', relationshipType:'نوع رابطه', interactionType:'نوع تعامل',
  sensitivity:'حساسیت', lastInteractionAt:'آخرین تعامل', nextMeetingAt:'جلسهٔ بعدی',
  objective:'هدف', agenda:'دستور کار', outcome:'نتیجه', notes:'یادداشت‌ها', summary:'خلاصه',
  decisions:'تصمیم‌ها', transcript:'متن مذاکره', followUpRequired:'نیازمند پیگیری',
  followUpAt:'موعد پیگیری', assignedTo:'واگذار شده به', ownerId:'شناسه مالک',
  reminderAt:'یادآور', sourcePersonId:'شناسه معرف', targetPersonId:'شناسه معرفی‌شونده',
  sourceOrganizationId:'سازمان مبدأ', targetOrganizationId:'سازمان مقصد',
  weightedOpportunityValue:'ارزش موزون فرصت', peopleCount:'تعداد اشخاص', opportunityCount:'تعداد فرصت‌ها',
  successProbability:'احتمال موفقیت', targetFit:'تناسب هدف', pathStrength:'قدرت مسیر',
  hopCount:'تعداد گام‌ها', connectorPerson:'شخص اتصال‌دهنده',
};
export const labelKey = (k: string): string => KEY_FA[k] ?? k.replace(/[A-Z]/g, c => ' ' + c.toLowerCase()).replace(/_/g, ' ');
