// AUTO-GENERATED by scripts/gen-pages-ids.mjs — do not edit by hand.
// Ids come from scripts/mock-api.mjs so every dynamic route can be
// statically pre-rendered (GitHub Pages export, SRIP_PAGES=1).
export const pageIds: Record<string, string[]> = {
  organizations: ["org-1","org-2","org-3","org-4","org-5","org-6","org-7","org-8","org-9","org-10","org-11","org-12","org-x","org-pars","org-pars-01","org-pars-02","org-pars-03","org-pars-04","org-pars-05","org-pars-06","org-pars-07","org-pars-08","org-pars-09","org-pars-10","org-pars-11","org-pars-12","org-inst-01","org-inst-02","org-inst-03","org-inst-04","org-inst-05","org-inst-06","org-inst-07","org-inst-08","org-inst-09","org-inst-10","org-reg-energy","org-reg-oil","org-reg-energy-eff","org-reg-edu","org-reg-science","org-reg-welfare","org-reg-health","org-reg-fda","org-reg-agri","org-reg-cbi","org-reg-roads","org-reg-industry","org-reg-standard","org-reg-transport","org-reg-culture","org-ac-tehran","org-ac-amirkabir","org-ac-iust","org-ac-kntu","org-ac-sbu","org-ac-ferdowsi","org-ac-shiraz","org-ac-nlpic","org-ac-csi","org-ac-ai","org-ac-iscisc","org-ac-med-tehran","org-ac-tarbiat","org-ac-petrol","org-ac-allameh","org-ac-edu-research","org-ac-art","org-eco-tse","org-eco-ifb","org-eco-cvc-kerman","org-eco-vc-pasargad","org-eco-chamber-ir","org-ecx-pardis","org-ecx-innofactory","org-ecx-jahesh","org-ecx-utpark","org-ecx-sharifpark","org-ecx-avatech","org-ecx-finnova","org-ecx-maintech","org-ecx-sarava","org-ecx-digikala","org-ecx-snapp","org-ecx-divar","org-ecx-tapsi","org-ecx-arvan","org-ecx-mci","org-ecx-ecommerce"],
  people: ["p-1","p-2","p-3","p-4","p-5","p-6","p-7","p-8","p-9","p-10","p-11","p-12","p-13","p-14","p-15","p-16","p-17","p-18","p-19"],
  relationships: ["r-1","r-2","r-3","r-4","r-5","r-6","r-7","r-8","r-9","r-10","r-11","r-12"],
  meetings: ["m-1","m-2","m-3","a-x1","c-x1","m-4","m-5","m-6"],
  actions: ["a-1","a-2","a-3","a-4","a-5","a-6"],
  commitments: ["c-1","c-2","c-3","c-4","c-5","c-6"],
  projects: ["pr-1","pr-2","pr-3"],
  opportunities: ["o-1","o-2","o-3","o-4"],
  interactions: ["i-1","i-2","i-3","i-4","i-5","i-6","i-7","i-8","i-9","i-10","i-11","i-12","i-13"],
  notifications: ["n-1","n-2","n-3"],
  recommendations: ["rec-1","rec-2","rec-3","rec-4","rec-5"],
};
