'use client';
import {use,useCallback,useEffect,useState} from 'react';
import {api} from '../../_lib/api';
import {Badge,ErrorCard,Loading,PageHeader} from '../../_components/page-ui';
const REQ_STATUS=['OPEN','IN_PROGRESS','SATISFIED','BLOCKED','CANCELLED'];
const PRIORITY=['LOW','MEDIUM','HIGH','CRITICAL'];
const MILESTONE_STATUS=['PLANNED','IN_PROGRESS','COMPLETED','BLOCKED','CANCELLED'];
const RISK_STATUS=['OPEN','MITIGATED','ACCEPTED','CLOSED'];
type Panel='requirement'|'risk'|'milestone';
export default function Page({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);
 const [p,setP]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[panel,setPanel]=useState<Panel|null>(null);
 const [req,setReq]=useState({title:'',description:'',category:'',status:'OPEN',priority:'MEDIUM'});
 const [risk,setRisk]=useState({title:'',description:'',probability:'',impact:'',mitigation:'',status:'OPEN'});
 const [ms,setMs]=useState({title:'',description:'',status:'PLANNED',dueAt:''});
 const load=useCallback(async()=>{setError('');try{setP(await api(`/projects/${id}`))}catch(e){setError((e as Error).message)}},[id]);
 useEffect(()=>{load()},[load]);
 async function doIt(label:string,fn:()=>Promise<any>){setBusy(label);setError('');try{await fn();await load()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function addReq(e:React.FormEvent){e.preventDefault();await doIt('req',()=>api('/projects/requirements',{method:'POST',body:JSON.stringify({...req,projectId:id})}));setReq({title:'',description:'',category:'',status:'OPEN',priority:'MEDIUM'});setPanel(null)}
 async function addRisk(e:React.FormEvent){e.preventDefault();await doIt('risk',()=>api(`/projects/${id}/risks`,{method:'POST',body:JSON.stringify({...risk,probability:Number(risk.probability)||0,impact:Number(risk.impact)||0})}));setRisk({title:'',description:'',probability:'',impact:'',mitigation:'',status:'OPEN'});setPanel(null)}
 async function addMilestone(e:React.FormEvent){e.preventDefault();await doIt('milestone',()=>api(`/projects/${id}/milestones`,{method:'POST',body:JSON.stringify({...ms,dueAt:ms.dueAt?new Date(ms.dueAt).toISOString():undefined})}));setMs({title:'',description:'',status:'PLANNED',dueAt:''});setPanel(null)}
 async function patch(path:string,body:any){await doIt('patch',()=>api(path,{method:'PATCH',body:JSON.stringify(body)}))}
 async function linkRelationship(relationshipId:string){await doIt('link',()=>api(`/projects/${id}/relationships`,{method:'POST',body:JSON.stringify({relationshipId})}))}
 async function unlink(relationshipId:string){if(!confirm('این رابطه از پروژه جدا شود؟'))return;await doIt('unlink',()=>api(`/projects/${id}/relationships/${relationshipId}`,{method:'DELETE'}))}
 const info=p?Object.entries(p).filter(([k])=>!['requirements','risks','milestones','relationships','opportunities','actions','commitments','organization','owner'].includes(k)&&typeof p[k]!=='function').slice(0,24):[];
 return <main className="feature-page">
  <PageHeader eyebrow="PROJECT" title={p?.name??'Project'} description={`شناسه: ${id}`} actions={<div className="toolbar"><button className="secondary-action" onClick={load} disabled={!!busy}>بازخوانی</button><button className="primary-action" onClick={()=>setPanel('requirement')} disabled={!!busy}>+ الزام</button><button className="primary-action" onClick={()=>setPanel('risk')} disabled={!!busy}>+ ریسک</button><button className="primary-action" onClick={()=>setPanel('milestone')} disabled={!!busy}>+ مرحله</button><button className="danger-action" disabled={!!busy} onClick={()=>{if(confirm('این پروژه حذف شود؟'))doIt('del',()=>api(`/projects/${id}`,{method:'DELETE'}))}}>حذف</button></div>}/>
  <ErrorCard message={error}/>
  {!p&&!error?<Loading/>:p&&<>
   <section className="panel"><div className="panel-title"><div><h2>اطلاعات پروژه</h2><p>{p.objective??'بدون هدف ثبت‌شده'}</p></div><Badge tone={p.status?.toUpperCase()==='COMPLETED'?'success':'neutral'}>{p.status??'—'}</Badge></div><div className="detail-grid">{info.map(([k,v])=>{if(v==null)return null;return <div className="detail-item" key={k}><small>{k}</small><strong>{typeof v==='object'?JSON.stringify(v):String(v)}</strong></div>})}</div></section>
   <div className="split-panels">
    <section className="panel"><div className="panel-title"><div><h2>الزامات (Requirements)</h2><Badge>{(p.requirements??[]).length}</Badge></div></div>{(p.requirements??[]).length?<div className="list">{(p.requirements??[]).map((r:any)=><div className="listRow" key={r.id}><span><Badge tone={r.status==='SATISFIED'?'success':'neutral'}>{r.status}</Badge> <Badge tone={r.priority==='HIGH'||r.priority==='CRITICAL'?'danger':'neutral'}>{r.priority}</Badge></span><span><strong>{r.title}</strong><small>{r.description||'—'}{r.category?` · ${r.category}`:''}</small></span><span className="resource-row-actions"><select value={r.status} disabled={!!busy} onChange={e=>patch(`/projects/requirements/${r.id}`,{status:e.target.value})}>{REQ_STATUS.map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={()=>doIt('delReq',()=>api(`/projects/requirements/${r.id}`,{method:'DELETE'}))}>حذف</button></span></div>)}</div>:<p className="empty-state">الزامی ثبت نشده است.</p>}</section>
    <section className="panel"><div className="panel-title"><div><h2>ریسک‌ها</h2><Badge>{(p.risks??[]).length}</Badge></div></div>{(p.risks??[]).length?<div className="list">{(p.risks??[]).map((r:any)=><div className="listRow" key={r.id}><Badge tone={r.status==='CLOSED'||r.status==='MITIGATED'?'success':r.score>=50?'danger':'neutral'}>{r.score}</Badge><span><strong>{r.title}</strong><small>{r.description||'—'}{r.mitigation?` · پایش: ${r.mitigation}`:''} · P×I = {r.probability}×{r.impact}</small></span><span className="resource-row-actions"><select value={r.status} disabled={!!busy} onChange={e=>patch(`/projects/risks/${r.id}`,{status:e.target.value})}>{RISK_STATUS.map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={()=>doIt('delRisk',()=>api(`/projects/risks/${r.id}`,{method:'DELETE'}))}>حذف</button></span></div>)}</div>:<p className="empty-state">ریسکی ثبت نشده است.</p>}</section>
   </div>
   <div className="split-panels">
    <section className="panel"><div className="panel-title"><div><h2>مراحل (Milestones)</h2><Badge>{(p.milestones??[]).length}</Badge></div></div>{(p.milestones??[]).length?<div className="list">{(p.milestones??[]).map((m:any)=><div className="listRow" key={m.id}><Badge tone={m.status==='COMPLETED'?'success':'neutral'}>{m.status}</Badge><span><strong>{m.title}</strong><small>{m.description||'—'}{m.dueAt?` · سررسید ${new Date(m.dueAt).toLocaleDateString()}`:''}</small></span><span className="resource-row-actions"><select value={m.status} disabled={!!busy} onChange={e=>patch(`/projects/milestones/${m.id}`,{status:e.target.value})}>{MILESTONE_STATUS.map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={()=>doIt('delMs',()=>api(`/projects/milestones/${m.id}`,{method:'DELETE'}))}>حذف</button></span></div>)}</div>:<p className="empty-state">مرحله‌ای ثبت نشده است.</p>}</section>
    <section className="panel"><div className="panel-title"><div><h2>روابط مرتبط</h2><Badge>{(p.relationships??[]).length}</Badge></div><button className="secondary-action" onClick={()=>{const v=window.prompt('Relationship ID');if(v)linkRelationship(v)}} disabled={!!busy}>پیوند رابطه</button></div>{(p.relationships??[]).length?<div className="list">{(p.relationships??[]).map((pr:any)=>{const rel=pr.relationship;return <div className="listRow" key={pr.relationshipId}><Badge tone="neutral">{pr.status??'UNENGAGED'}</Badge><span><strong>{rel?.sourceOrganization?.name} ↔ {rel?.targetOrganization?.name}</strong><small>{pr.relevance?'اهمیت '+pr.relevance:''}{pr.required?' · حیاتی':''}</small></span><span className="resource-row-actions"><button onClick={()=>unlink(rel?.id??pr.relationshipId)}>حذف پیوند</button></span></div>})}</div>:<p className="empty-state">رابطه‌ای پیوند نشده است.</p>}</section>
   </div>
   {panel==='requirement'&&<section className="panel"><div className="panel-title"><h2>الزام جدید</h2><button onClick={()=>setPanel(null)}>انصراف</button></div><form className="entity-form" onSubmit={addReq}><label>عنوان<input required value={req.title} onChange={e=>setReq({...req,title:e.target.value})}/></label><label>توضیحات<textarea value={req.description} onChange={e=>setReq({...req,description:e.target.value})}/></label><label>دسته<select value={req.category} onChange={e=>setReq({...req,category:e.target.value})}><option value="">—</option>{['BUSINESS','TECHNICAL','PROCESS','COMPLIANCE','RESOURCE'].map(c=><option key={c} value={c}>{c}</option>)}</select></label><label>وضعیت<select value={req.status} onChange={e=>setReq({...req,status:e.target.value})}>{REQ_STATUS.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>اولویت<select value={req.priority} onChange={e=>setReq({...req,priority:e.target.value})}>{PRIORITY.map(s=><option key={s} value={s}>{s}</option>)}</select></label><button className="primary-action" disabled={!!busy}>{busy==='req'?'در حال ذخیره…':'ثبت الزام'}</button></form></section>}
   {panel==='risk'&&<section className="panel"><div className="panel-title"><h2>ریسک جدید</h2><button onClick={()=>setPanel(null)}>انصراف</button></div><form className="entity-form" onSubmit={addRisk}><label>عنوان<input required value={risk.title} onChange={e=>setRisk({...risk,title:e.target.value})}/></label><label>توضیحات<textarea value={risk.description} onChange={e=>setRisk({...risk,description:e.target.value})}/></label><label>Probability (0-10)<input type="number" min={0} max={10} value={risk.probability} onChange={e=>setRisk({...risk,probability:e.target.value})}/></label><label>Impact (0-10)<input type="number" min={0} max={10} value={risk.impact} onChange={e=>setRisk({...risk,impact:e.target.value})}/></label><label>پایش (Mitigation)<textarea value={risk.mitigation} onChange={e=>setRisk({...risk,mitigation:e.target.value})}/></label><label>وضعیت<select value={risk.status} onChange={e=>setRisk({...risk,status:e.target.value})}>{RISK_STATUS.map(s=><option key={s} value={s}>{s}</option>)}</select></label><button className="primary-action" disabled={!!busy}>{busy==='risk'?'در حال ذخیره…':'ثبت ریسک'}</button></form></section>}
   {panel==='milestone'&&<section className="panel"><div className="panel-title"><h2>مرحله جدید</h2><button onClick={()=>setPanel(null)}>انصراف</button></div><form className="entity-form" onSubmit={addMilestone}><label>عنوان<input required value={ms.title} onChange={e=>setMs({...ms,title:e.target.value})}/></label><label>توضیحات<textarea value={ms.description} onChange={e=>setMs({...ms,description:e.target.value})}/></label><label>وضعیت<select value={ms.status} onChange={e=>setMs({...ms,status:e.target.value})}>{MILESTONE_STATUS.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>سررسید<input type="datetime-local" value={ms.dueAt} onChange={e=>setMs({...ms,dueAt:e.target.value})}/></label><button className="primary-action" disabled={!!busy}>{busy==='milestone'?'در حال ذخیره…':'ثبت مرحله'}</button></form></section>}
  </>}
 </main>;
}